### PR TITLE
Small caps in Bracketed Spans

### PR DESCRIPTION
**Pull request by ickc**
I adapted the relevant code from `spanHtml` into `bracketedSpan` to check if small caps style is used in bracketed spans.

I then update the `MANUAL.txt` accordingly to reflect this use.

I tested and it compile successfully. The code I used to test if the small caps with bracketed span works is:

``` markdown
1. HTML:
    - <span style="font-variant:small-caps;">Small caps</span>
    - <span style="font-variant:small-caps">Small caps</span>
    - <span style="font-variant: small-caps">Small caps</span>
2. markdown:
    - [Small caps]{style="font-variant:small-caps;"}
    - [Small caps]{style="font-variant:small-caps"}
    - [Small caps]{style="font-variant: small-caps"}
```

I don't know anything about the tests yet so I didn't modify any of the test to test this.

Edit: this should partially resolves issue #2761

### CODE REVIEW

**Comment by ousia** [comment]
@ickc, sorry if I’m not getting everything right (Haskell is really Greek to me). I think the following is an important issue.

Please, don’t hard code CSS code into Markdown syntax. Using a class such as `[small caps]{.small-caps}` is better. So we achieve:

* Cleaner and clearer writing and a more proper Markdown syntax.

* Depending on your scenario, with a class you might use:

    * Another font. _Adobe Reader Mobile_ doesn’t comply with `font-variant:small-caps`, at least in previous versions and this is the software for e-ink readers. And this is also the way to get real small caps when OpenType features aren’t an option.

    * Fake small caps, such as the ones with `font-variant: small-caps;`.

    * With the proper font and rendering engine, the OpenType `smcp` feature (which are real small caps).

Sorry, but I don’t think this is the right approach. Markdown should not mimic CSS or TeX (to name two), but it should use classes in the syntax itself.

Otherwise, OpenType usage would be problematic in this case. Keeping open options (i think) is a much better idea.

**Comment by ickc** [comment]
I am aware of the issue #1592 you described. However, this pull request is to make sure the bracketed span behaves the same way as the html span in the markdown reader. Currently the "font variant" is still the only and recommended small cap syntax in pandoc according to the manual.

**Comment by ickc** [comment]
About the test: actually when I dig a bit deeper it doesn't seem like to have a test of SmallCaps in markdown reader.

**Comment by ickc** [comment]
I just made one more commit to correct the code I wrote in the markdown reader: bracketedSpan functions *truly exactly* the same as spanHtml. Previously I didn't check id and class are empty.

Regarding the test, since the test didn't test for smallcaps, so writing a test for small caps for both bracketed_spans and native_spans should belongs to a separate pull request.

**Comment by ickc** [comment]
Are there any concerns about this pull request? Since what it does is basically to make sure the **`bracketed_span` functions exactly as a `native_span` would**, it seems it shouldn't be too much problem with it?

Until a better small-caps syntax is settled, at least we can make sure we can use `bracketed_span` to specify small-caps in the way `native_span` is already doing?

**Comment by jgm** [comment]
Thanks.  I do like @ousia's suggestion to use a "small-caps" class.
Perhaps the condition could be:  if the span (whether HTMLish or bracket) has *either* the class "small-caps" (and no other attributes) or style="font-variant:small-caps" (and no other attributes), it's treated as a small caps element.

**Comment by jgm** [comment]
Although perhaps @ousia is more concerned with HTML output than with how these things are input.

**Comment by jgm** [comment]
In any case, this discussion should proceed on another (open) issue.

**Pull request merged**
