### PR TITLE
fixes HTML Reader: tables

### PR DESCRIPTION
**Pull request by mb21**

### CODE REVIEW

**Comment by mpickering** [comment]
Can you add a test please?

**Comment by jgm** [comment]
@mb21, thanks, this looks good!  It would be lovely if you could:

1. rebase the code changes into a single commit, so the history is easier to survey,
2. add a test or two for this kind of case (you could just add them to `tests/html-reader.{html,native}`) in the tables section.
3. if anything about the code might be hard to understand for someone coming to this later, consider adding a brief explanatory comment

**Comment by mb21** [comment]
sure, I should get around to it in the next couple of days...

**Comment by mb21** [comment]
There we go!

**Comment by jgm** [comment]
Great, thanks!

**Comment by ronanpaixao** [comment]
Any chance of including this for the Markdown reader?

**Comment by mb21** [comment]
@ronanpaixao Please ask on the pandoc-discuss mailing list. This is an old pull request and it's not clear what you mean.

**Pull request merged**
