### PR TITLE
Add the `description` meta tag to the HTML templates

### PR DESCRIPTION
**Pull request by jerry-sky**
The `description` meta tag will make the generated HTML documents more complete and SEO-friendly.

### CODE REVIEW

**Comment by mb21** [comment]
Weird that we didn't have that already... then again, from https://moz.com/learn/seo/meta-description:

> Google [announced](https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html) in September of 2009 that neither meta descriptions nor meta keywords factor into Google's ranking algorithms for web search. 

Although sometimes it's indeed used for the text snippet displayed in Google's search results page.

**Comment by jerry-sky** [comment]
> Although sometimes it's indeed used for the text snippet displayed in Google's search results page.

Yes, that’s what I’m aiming for, and I’m aware that Google does not take those meta tags into consideration, but from what I have found it seems that the `description` meta tag is in fact used when displaying the website in Google Search.

**Comment by jgm** [comment]
No objections to providing a way to get descriptions in there.  But this way of doing it is likely to cause problems.  The `descriptions` metadata field will be rendered as HTML, and would need escaping to be put into an attribute, wouldn't it?  What if the quotes or emphasis occur in it, for example?

This makes me think we should provide a doctemplates `pipe` to escape HTML; it would simplify these templates.

**Comment by jgm** [comment]
In the HTML writer we'll need something like
```
maybe id (defField "description-meta") descriptionMeta .
```
(around line 325) and then (around line 257)
```
let descriptionMeta = stringifyHTML <$> lookupMetaInlines "description" meta
```
and then you'd use `description-meta` in the template.  This will ensure that the values there are properly escaped.

**Comment by jgm** [comment]
If you don't have a Haskell development environment set up, I can do that part for you.

**Comment by jerry-sky** [comment]
> If you don't have a Haskell development environment set up, I can do that part for you.

Yes, I would really appreciate that, because I’ve never had any experiences with Haskell development. This PR is more of a _suggestion_.

**Comment by jgm** [comment]
OK, I'll merge this then and add something to the writer.

**Pull request merged**
