### PR TITLE
RST Writer: Normalize headings to sequential levels

### PR DESCRIPTION
**Pull request by lierdakil**
This is pretty much required by docutils.

First level will be interpreted as level 1 anyway, and subsequent levels must be sequential.

See [pandoc-discuss thread][1] for background.

I'm not entirely sure it's OK to handle this in such way, since heading level information is irreversibly lost during conversion, but I see no other option really.

[1]: https://groups.google.com/d/msg/pandoc-discuss/mTG4phv5roA/ljApKvFDrY4J

### CODE REVIEW

**Comment by jgm** [comment]
Are headers allowed in block quotes and list items in reST?  If not, maybe we should remove them (convert them to regular paragraphs, perhaps in a Strong) as well.

**Comment by lierdakil** [comment]
Well, technically there is a `rubric` directive, which is described as "informal section", i.e. a heading with no relation to document structure, which *can* be included in block quotes and lists. Its exact semantics are a little fuzzy though, f.ex. there is no obvious way to denote rubric level.

Proper sections (i.e. headings) are not allowed anywhere except at top level though.

**Comment by jgm** [comment]
I'd be fine with making all non-outside headers into rubrics.
Or just making them paragraphs.  But we should do one or the other, to
avoid creating invalid rst.

**Comment by lierdakil** [comment]
Please hold off on merging until I add some tests for this.

**Comment by atorin** [comment]
FWIW, in my experience _rubrics_ tend to pollute the RST output with useless information. 
Would it not be easier to just use bold instead?

**Pull request merged**
