### PR TITLE
Subdivide Text.Pandoc.Class into small modules

### PR DESCRIPTION
**Pull request by tarleb**
The module `Text.Pandoc.Class` is large and combines different aspects, making it difficult to understand and extend. The module is split and spread over (unexported) submodules `CommonState`, `PandocMonad`, `IO`, and `Pure`.

### CODE REVIEW

**Comment by tarleb** [comment]
Motivation: I'm trying to create a new type `PandocLua`, which would be a PandocMonad instance and should simplify our Lua code.

**Comment by jgm** [comment]
Nice idea!  I agree that this is beneficial.

**Comment by tarleb** [comment]
It is only a first step, but I think this would be ok to merge. I have also added haddock comments for all functions in module `PandocMonad`, just in case we choose to expose the module at some point.

**Comment by jgm** [comment]
looks good to me!

**Pull request merged**
