### PR TITLE
Add FB2 reader

### PR DESCRIPTION
**Pull request by labdsf**
Not ready, PR is just to make sure nobody else starts from scratch

### CODE REVIEW

**Comment by labdsf** [comment]
@jgm 
This PR is ready for merge.

What is not supported yet (as listed in the comment in the code):

- Tables: nothing is produced for them at all. FBReader does not display them anyway (while CoolReader does) and they are rarely used
- Named styles (have not seen them used anyway, don't know what they are for)
- ID attribute for some elements (e.g. paragraphs, should add <span> to them in this case probably)

Reader errs out on `writer.fb2`, but that is the problem of FB2 writer, see issue #2424 Problems are `<empty-line/>` inside paragraph (fixed by #4522, not merged), nested `<cite>` and markup outside paragraphs (after "Interpreted markdown in a table"). Once these 3 places are manually corrected, reader parses the file successfully.

**Comment by jgm** [comment]
OK, great. I merged the other change as well.

**Comment by jgm** [comment]
I'm getting:
```
% pandoc -f fb2 test/writer.fb2 
Couldn't parse FB2 file: unexpected element cite in cite.
```
Can't FB2 handle nested block quotes?
If not, is there a more graceful way of handling this?

**Comment by labdsf** [comment]
FB2 schema does not allow `<cite>` in `<cite>`. It should be fixed in writer instead.

In reader it may be better to output "skipped content" warning instead of error. The problem is that it accepts Parsec's SourcePos. But I don't use Parsec in FB2 reader and I don't know the position in file.

I may add yet another `LogMessage` constructor, similar to `DocxParserWarning String`. Is it a good solution?

**Comment by murrrf** [comment]
There are some problems with the conversion from fb2.

1. The <id> tag specified by the author, since version 2.2, is not recognized by the conversion, causing the message "Could not parse FB2 file: unexpected element id in author."
2. The sections of the fb2-file are converted to <div class = "section"> </ div>, and this text needs to be deleted manually.

**Comment by labdsf** [comment]
@murrrf Please file new issues instead of commenting in closed PRs, it is easier to track that way.

> The tag specified by the author, since version 2.2, is not recognized by the conversion, causing the message "Could not parse FB2 file: unexpected element id in author."

IDs are not parsed indeed, there is even a TODO in the source file.

> The sections of the fb2-file are converted to </ div>, and this text needs to be deleted manually.

You can remove them with a filter, not manually. It is not a bug, FB2 may contain section with an ID but without a title, and it is the only way to represent it.

**Pull request merged**
