### PR TITLE
New defaults files documentation

### PR DESCRIPTION
**Pull request by allefeld**
I took a stab at integrating the new defaults file documentation, as discussed in #5990, into the Pandoc manual.

I took out the original example defaults file code close to the beginning, and added the tables in subsections at the end. In the process, I slightly changed the text which was referencing the example before, and added some text referencing the tables after. It could probably be done more smoothly, but I didn't want to modify the existing text more than minimally. Please have a look.

I also noticed an inconsistency in the manual; it uses 5 times the term "default file" and 9 times the term "defaults file". I took the liberty to change that to always use "defaults file".

I checked the new version by `make man/pandoc.1` as well as `pandoc -s MANUAL.txt -o MANUAL.html`. It displays decently, but not perfectly. As mentioned in the issue, the different tables appear at different width, in both the man page and the HTML. That's though they are grid tables with exactly the same width and column width in the Markdown source. I don't know how to fix that.

### CODE REVIEW

**Comment by allefeld** [comment]
The second commit includes information from comments in the example defaults file. I omitted a few where the information can be obtained from the corresponding command line option documentation.

**Comment by jgm** [comment]
Great! Let me take a look and see if I can fix the table issue.

**Comment by jgm** [comment]
OK, when used in the context of the website (with the CSS we have there), the tables all look the same width, so I don't think this will be a problem.  Same with PDF output.  The man page, though, doesn't look good; this may require some work on the man writer.

**Comment by jgm** [comment]
The problem in the man output is that the code blocks get turned into .IP (indented paragraph), which looks really bad in this particular context.

**Comment by jgm** [comment]
OK, I've got a solution to the man page issue.
(A bit of hackery in the manfilter.lua.)

**Comment by allefeld** [comment]
Great, that was fast! I'm looking forward to the new documentation to get onto the website...

**Comment by jgm** [comment]
It should be there now...

**Pull request merged**
