### PR TITLE
LaTeX writer: support colspans and rowspans in tables.

### PR DESCRIPTION
**Pull request by tarleb**
See also: #6313

### CODE REVIEW

**Comment by tarleb** [comment]
- [ ] add tests
- [ ] fix big producing invalid LaTeX for some tables

**Comment by tarleb** [comment]
Potentially controversial choices in this PR:
- Package `multirows` is now required in the default template.
- Content of row-spanning cells is centered vertically. This is the default, but doesn't always look good in the resulting PDF.
- Tables with colspans or rowspans always fill the full columnwidth. Otherwise cells tend to get too wide.

**Comment by jgm** [comment]
> Tables with colspans or rowspans always fill the full columnwidth. Otherwise cells tend to get too wide.

I'm not sure what you mean here.  Why would forcing tables to fill the full columnwidth make cells narrower?  Wouldn't it make them wider?

Seems to me there are cases where you'd want a narrow table with a colspan or rowspan.
 
> multirow

Slight drawback to this is that it's in texlive-latex-extra on debian, so bringing it in requires bringing in a lot else. I've tried to avoid requiring things in texlive-latex-extra so far -- though maybe we already depend on something there.

I assume there's no good way to do rowspan without this package?

I suppose one option would be to include the package only if rowspans are actually used.  Or we could just bite the bullet. It's entirely possible that we already require packages in texlive-latex-extra.

**Comment by tarleb** [comment]
The multirow package is now only loaded if really needed.

Please ignore my previous comment about table widths. I found that this was based on a faulty test of mine.

**Comment by jgm** [comment]
Great, thanks!

**Pull request merged**
