### PR TITLE
Docx Writer: add borders in table cell

### PR DESCRIPTION
**Pull request by Meow-z**

### CODE REVIEW

**Comment by cj1324** [comment]
Link #3275

**Comment by Meow-z** [comment]
image

**Comment by mb21** [comment]
AFAIK this shouldn't be needed since we have http://pandoc.org/MANUAL.html#custom-styles-in-docx-output

**Comment by agusmba** [comment]
I agree with @mb21 , the possibility to define your default table style should be enough (you can define one with borders if you like).
Of course it will be nice when we are also able to specify a different custom table style in our Markdown as we can do already with divs etc.

**Comment by agusmba** [comment]
@Meow-z specifically have a look at `--reference-doc=FILE` under http://pandoc.org/MANUAL.html#options-affecting-specific-writers

You only need to modify the "Table" table style.

**Pull request closed without merging**
