### PR TITLE
Remove unsupported element from pptx reference doc

### PR DESCRIPTION
**Pull request by LunkRat**
Addresses #6338 by removing the misleading text from the pptx reference doc.

### CODE REVIEW

**Comment by jgm** [comment]
Can you explain more fully what you've removed and why?

**Comment by LunkRat** [comment]
Sure, I removed a bit of text from Slide 3 of the pptx reference doc, which was a small bit that appeared above the H1 on the 'Section Header' slide, which said:

> Some explanatory text

As pointed out in #6338 this example slide is misleading because it suggests that there is some Markdown mechanism for getting such text to appear on your Section Heading slides. As there is no such mechanism, I removed the example text so that others are not led astray trying to get their Markdown slides to appear in that text box.

**Comment by jgm** [comment]
OK, thanks!

**Comment by StianBerger** [comment]
Not that it matters so much, but I can say that just the presence of that text box is enough for "someone" :sweat_smile:  to spend hours figuring out how to use it...

**Pull request merged**
