### PR TITLE
Add an option to parse-before-combining.

### PR DESCRIPTION
**Pull request by jkr**
This is more of an RFC than a ready-to-go PR. It's my attempt to deal with the issue of footnotes in multiple documents, which is just enough of an issue to keep me from regularly using pandoc/markdown for article-length work. These two commits add an option to parse documents before combining. This allows multiple documents with footnotes starting at `[^1]` to combine as expected, and also allows us to combine files from different input formats, or multiple binary files. The trade-off is that we can't link across multiple files, and auto-identified headers don't always work as expected if the name is repeated. This is an option (`--parse-first` flag) that defaults to off (i.e., default behavior is normal).

For all that, the change is fairly unintrusive. The vast majority of the lines of code are option boilerplate.

More detailed info is in the message for the first commit. Thoughts?

### CODE REVIEW

**Comment by jgm** [comment]
I think there might be others who'd like this feature, too.
Maybe worth posting on pandoc-discuss describing the proposed
feature and linking here?

+++ Jesse Rosenthal [Feb 13 16 13:08 ]:

**Comment by jkr** [comment]
Good idea -- note posted to the list.

**Comment by jkr** [comment]
Actually, it occurs to me that Binary readers should probably default to this. In the single-source case (which is all that is allowed for binaries at the moment) it is the same. But this would allow multiple sources (provided they're the same format).

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Feb 14 16 05:13 ]:
>   Actually, it occurs to me that Binary readers should probably default
>   to this. In the single-source case (which is all that is allowed for
>   binaries at the moment) it is the same. But this would allow multiple
>   sources (provided they're the same format).

Yes, that makes sense, I suppose.

**Comment by jkr** [comment]
And the option name seems wrong: too implementation specific. Something more like `--file-scope` (as opposed to document-scope) seems preferable.

**Pull request closed without merging**
