### PR TITLE
Removed unused extensions

### PR DESCRIPTION
**Pull request by Anabra**
Removed most unused extensions from the modules in the src directory. This has been done using the OrganizeExtensions refactoring of the Haskell-Tools framework.

### CODE REVIEW

**Comment by Anabra** [comment]
Looks like the pre8 GHC doesn't like the changes. Could add a conditional block with FlexibleContexts in it, or just FlexibleContexts itself.

**Comment by jgm** [comment]
Thanks! I hadn't heard of this tool.  Can you give a link to it?

Comments:

- We should keep NoImplicitPrelude, even where it is not strictly needed, because we're using a custom prelude and importing it explicitly.

- I prefer having these pragmas one per line as before, rather than all on one line.

**Comment by Anabra** [comment]
This is a little demo for the tool: http://www.haskelltools.org/
Since then, the OrganizeExtensions refactoring has improved quite a bit. Some other features have been added as well.

**Comment by jgm** [comment]
Great, thanks for doing this!

**Pull request merged**
