### PR TITLE
Add support for <mark>

### PR DESCRIPTION
**Pull request by cideM**
It is a bit hard to believe that this is all it takes and since this is my first PR on any meaningful project I'm still somewhat skeptical :thinking: but the tests pass and manual testing in the shell also seemed fine. Thanks to the groundwork from #5796 

I don't quite understand the meaning of the numbered `*.md` files for command and couldn't find any info on whether they're generated based on some source. Anyway, let me know if anything's wrong :pray: and thanks for tagging with good first issue and for `pandoc` in general <3

### CODE REVIEW

**Comment by jgm** [comment]
Yep, it's that simple!

I would only suggest renaming the command test.  `kbd.md` doesn't make sense; use the issue number that the commit closes, `5797.md`.

My other suggestion would be to revise the commit message so it gives a clearer idea of what the change does (including which issue it closes and how the behavior will change).  Say that it causes `<mark>` elements to be parsed from HTML as a Span with class `mark`, and renders such spans into HTML using the `<mark>` element.  This is important because when I construct the changelog for a new release, I need to describe all the important changes that have been made.

**Comment by cideM** [comment]
Ha, I must've spent so much time looking at the kbd PR that I eventually confused the name. I mean to call it `mark.md`. Anyway thanks for the quick and thorough feedback :bowing_man: I changed the commit message and renamed the file.

One thing: maybe if I hadn't looked at it late in the evening I might have made the connection between file name and issue for the `test/command`s but it might not hurt to add one sentence about this to the `CONTRIBUTING.md`. Is this something you'd want and if so would you want me to do it in this PR in another commit?

**Comment by mb21** [comment]
Indeed, it only says:

> Alternatively, you may add a "command test" to the /test/command/ hierarchy, following the pattern of the tests there.

a new pull request for that would be great.

**Comment by cideM** [comment]
Added in #5829

**Pull request merged**
