### PR TITLE
Rename README to README.md

### PR DESCRIPTION
**Pull request by mathiasrw**
Get a great looking README for at great project

---
This change is [Reviewable](https://reviewable.io/reviews/jgm/pandoc/3028)

### CODE REVIEW

**Comment by jgm** [comment]
See e.g. https://github.com/jgm/pandoc/issues/2361

+++ Mathias Rangel Wulff [Jul 18 16 10:58 ]:

**Comment by tarleb** [comment]
@jgm: Since this comes up quite often lately, a third way of handling this might make sense: I've seen other projects have a `README.md` whose only obviously purpose is to look good on GitHub.  Those files usually contain only a brief description, some fancy-looking badges, test-status indicators, and a link to the *real* documentation.  I feel like that's a light misuse of the name `README`, but as long as it helps people to click through to the actual docs, it doesn't seem so bad.

**Comment by jgm** [comment]
I thought about this too.  Might be a good option, I'll
think more.

+++ Albert Krewinkel [Jul 18 16 11:44 ]:

**Comment by mathiasrw** [comment]
> I'll think more.

Sounds good. Ill close this one.

**Pull request closed without merging**
