### PR TITLE
use lookupMeta* functions wherever possible

### PR DESCRIPTION
**Pull request by mb21**
~~depends on https://github.com/jgm/pandoc-types/pull/51~~

### CODE REVIEW

**Comment by mb21** [comment]
Okay, this is now changed to include the new functions in `Text.Pandoc.Writers.Shared` instead of pandoc-types.

**Comment by mb21** [comment]
@jgm, due to https://github.com/jgm/pandoc/commit/d7263a7e5fb1ba53465099c6f1be7a85e05564f8, there was a conflict again. You added `metaValueToString` there, analogous to the `metaValueToInlines` functions which I removed in favour of the `lookupMetaInlines`. (I don't really feel strongly either way, but most usage makes this variant simpler.)

So I rebased once more. Would be really good to merge this, since otherwise people will continue adding stuff that transforms the metadata inconsistently to string/inline/block/bool, etc. like just happened now.

**Comment by jgm** [comment]
@mb21, sorry about that.  I'll merge!

**Comment by mb21** [comment]
Thanks!

**Pull request merged**
