### PR TITLE
Lint code in PRs and when committing to master

### PR DESCRIPTION
**Pull request by tarleb**
This adds a new GitHub Actions workflow which checks the code with HLint for all PRs and commits to master. Most linter annotations in the code are resolved; the remaining warnings are disabled via configs.

### CODE REVIEW

**Comment by tarleb** [comment]
This is a bit of an experiment. I have generally had good experiences using linters in other projects, but there is always the danger that it gets in the way more than it helps.

**Comment by jgm** [comment]
Yeah, I'm not sure.  I normally don't *always* apply hlint's suggestions, so I'm not sure I'd want to make it a requirement for commits.

Sometimes I find that some parentheses that aren't strictly necessary are helpful to make the code more readable by humans, for example.

**Comment by tarleb** [comment]
That's very true. The PR disables multiple hints because they would have made things worse (IMHO).

I am using automatic linting checks in hslua; so far the experience has been good. However, my feeling is that unnecessary warnings happen more often than in other languages. Maybe this *would* get annoying quickly when used in a project of pandoc's size.

I haven't tried it yet, but maybe the [hint-man](https://github.com/apps/hint-man) bot could be a good alternative.

**Comment by mb21** [comment]
Not sure if this has already been discussed, but we could also go full blown with https://github.com/tweag/ormolu

**Comment by tarleb** [comment]
Ormolu and similar tools are great in a company environment IMHO. I wouldn't want to use them in pandoc though.

**Comment by jgm** [comment]
Let's try it.  If the automatic lint action gets to be a pain, we can disable it.  But even if we do, these changes to hlint config and to the code are useful.

**Comment by jgm** [comment]
I'm confused about how this works!  (Background: I was trying to add a matching lint step to my pre-push procedure.)
Can you explain it?
The main action is
```
curl -sSL "${hlint_script}" | sh -s .
```
where `hlint_script` = `https://raw.github.com/ndmitchell/hlint/master/misc/run.sh`.
Now if I got to that URL, I see
```
#!/bin/sh
curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/run.sh | sh -s -- hlint $*
```
So, we download a script and run it, and the script says to download itself and pipe itself to hlint?  What is going on here?
I tried doing `hlint .` in the pandoc source directory, but I got many more warnings than the CI gives.

**Comment by tarleb** [comment]
I took that line from the hlint docs' [https://github.com/ndmitchell/hlint#running-with-continuous-integration](CI section). Following all URL redirects and indirections, I end up at https://raw.githubusercontent.com/ndmitchell/neil/master/misc/run.sh, which downloads hlint from its GitHub release page. This *does* seem overly convoluted.

> I tried doing `hlint .` in the pandoc source directory, but I got many more warnings than the CI gives.

That's weird, I'm not getting any warnings right now. I don't know what's going on there.

**Comment by tarleb** [comment]
FWIW, I'm running hlint 3.2.

**Comment by tarleb** [comment]
My pre-commit hook is

``` shell
#!/bin/sh
git diff --cached --name-only | grep '.hs$' | xargs hlint --hint .hlint.yaml
```

**Comment by jgm** [comment]
I've got an older hlint, that may be the issue.

**Comment by jgm** [comment]
Upgraded hlint.  That did it. Thanks for the pre-commit hook.

**Pull request merged**
