### PR TITLE
[RST Writer] Don't normalize heading levels below input minimum

### PR DESCRIPTION
**Pull request by lierdakil**
Hopefully helps with #2394

A test included.

### CODE REVIEW

**Comment by lierdakil** [comment]
@mscuthbert, could you possibly test this fork? I'm especially interested in how would it handle inconsistent heading levels, like this:

```markdown

## Heading 2

text

##### Heading 5

text

### Heading 3

text
```

**Comment by mscuthbert** [comment]
Hi @lierdakil -- thank you! Unfortunately I can't test this because I'm on the El Capitan beta and the rootless problems on building cabal projects (https://github.com/haskell/cabal/issues/2653) are preventing the building from source.  Since I've never developed a Haskell project (didn't know what Cabal was until this download) it's probably going to be beyond my abilities to make a test w/o a binary.

**Comment by jgm** [comment]
You could try building with the new stack tool.
(That may or may not run into the same problem.)
https://github.com/commercialhaskell/stack

+++ Michael Scott Cuthbert [Sep 19 15 12:09 ]:

**Comment by lierdakil** [comment]
Stack will run into the same problem, since this is ghc 7.8 issue. @mscuthbert, you *could* get your hands on ghc 7.10, which, according to [this](https://ghc.haskell.org/trac/ghc/blog/weekly20150721#MacOSXElCapitansupport), should work.

I'd be happy to provide a binary, but I have no access to OSX environment whatsoever, so that would be a bit complicated.

**Comment by jgm** [comment]
I compiled and tested.  Here's the reST output for the input you
provided:

```
Heading 2
---------

text

Heading 5
~~~~~~~~~

text

Heading 3
~~~~~~~~~

text
```

+++ Nikolay Yakimov [Sep 19 15 07:50 ]:

**Comment by lierdakil** [comment]
Thanks, @jgm, but that's something I could've done myself, and it's exactly the expected output. What I'm interested in is how this interacts with nbconvert, and that's not someting I can readily test.  As far as I gather, nbconvert splits input text into sections and feeds those to pandoc. I'm quite positive this input won't produce intuitively expected output in this case...

**Pull request merged**
