### PR TITLE
[WIP] Add Muse reader

### PR DESCRIPTION
**Pull request by labdsf**
I have created a basic Muse reader.  It supports headings, inline markup and footnotes, but no tables and lists. It is far from full markup support, but it satisfies my needs so I plan to continue development slowly from now on. Hope it gets merged.

### CODE REVIEW

**Comment by jgm** [comment]
I'd rather not merge until this has support for tables and lists.

**Comment by labdsf** [comment]
@jgm Ok, will make them high priority then.

**Comment by tarleb** [comment]
Regarding tables: My understanding is that Muse supports tables.el and org tables.  The org reader should be able to read tables.el formatted tables as well (#3314). It seems to me that a simple way to do this would be to extract the grid table parser from the markdown reader into a separate module. Same for the org table parser. @jgm, would you be okay with a separate `Table` module, collecting all (shared) table parsers?

**Comment by jgm** [comment]
Text.Pandoc.Parsing already contains gridTableWith.
Can you just use that?

+++ Albert Krewinkel [May 01 17 07:43 ]:

**Comment by tarleb** [comment]
> Text.Pandoc.Parsing already contains gridTableWith. Can you just use that?

Ah, yes. I had missed that.

I generalized the signature of `tableWith` to

``` haskell
tableWith :: (Stream s m Char, HasReaderOptions st, Monad mf)
          => ParserT s st m (mf [Blocks], [Alignment], [Int])
          -> ([Int] -> ParserT s st m (mf [Blocks]))
          -> ParserT s st m sep
          -> ParserT s st m end
          -> ParserT s st m (mf Blocks)
```

i.e. the state is no longer fixed to `ParserState` and table-cell block parsers must return values wrapped in a monad.  This requires a bit of `Identity` wrapping and unwrapping in the RST reader, but seems to work well.

**Comment by jgm** [comment]
Oh, good.  I wonder if your generalization of gridTableWith
would allow it to be used in the Markdown reader?

Currently we don't use it there, mostly because of the
F monad, if I recall.

(But part of the reason is also that in Markdown grid
tables we support alignments now.  Actually, it should
be fairly harmless to allow those in the RST reader, since
an actual RST document wouldn't have alignment markings.)

**Comment by tarleb** [comment]
I've pushed the changes and can take a look into merging the Markdown-specific gridTable parser into the generic parser.

**Comment by labdsf** [comment]
Added tables support. It is aimed to be compatible with Emacs Muse, not Text::Amuse, as Text::Amuse differences are considered a bug: melmothx/text-amuse#14

For example, tables are not required to be indented with a space, although writer indents them now for compatibility with Text::Amuse #3649.

**Comment by labdsf** [comment]
One bug remains: tables that consist only of caption crash because `museToPandocTable` tries to compute `maximum` over empty list.

**Comment by labdsf** [comment]
Added bullet lists. It always produces loose lists, just like A Muse Wiki. AFAIR Emacs Muse distinguishes between tight and loose lists, but I would rather follow A Muse Wiki here and avoid overcomplicating things complexity just for backwards compatibility.

**Comment by labdsf** [comment]
@jgm Tables and lists are now supported. I rebased against master and removed all hlint warnings. No definition lists and Org tables (A Muse Wiki does not support them either, though) yet.

**Comment by jgm** [comment]
Great, thanks!

**Comment by melmothx** [comment]
Text::Amuse does support definition lists https://amusewiki.org/library/manual#toc16 (documented since February 2016).

https://amusewiki.org/git/amw/commit/m/ml/manual.muse?id=73579f4c26aa047742cb319f3661a203b2fc7eb7

**Comment by labdsf** [comment]
@melmothx "A Muse Wiki does not support them either, though" was related to Org tables only.

**Pull request merged**
