### PR TITLE
Move section numbering code and enable for beamer

### PR DESCRIPTION
**Pull request by twsh**
This means that `--number-sections` will now number sections in beamer.

### CODE REVIEW

**Comment by twsh** [comment]
I'm not sure why this fails some test. I tried to update the relevant 'writer' files.

**Comment by jgm** [comment]
Look at the test output; it will show you what is expected (looks like a line moved to a different location).

**Comment by twsh** [comment]
I fixed the test, I just need to work out how to shorten the commit message that's too long.

**Comment by jgm** [comment]
Don't worry, I'll squash and edit the commit msg.

**Pull request merged**
