### PR TITLE
Adding fenced div blocks to markdown reader

### LINKED ISSUE #168: Syntax for divs
<pre>
I've been missing a way to specify a div markdown
without using HTML tags.  The (relatively) new 
delimited code block syntax gave me an idea however.
Consider using a line of four or more periods to
start a div:

    Para before div

    ....
    First para inside div

    Second para inside div

    Third para inside div
    ....

Since one will often want and need to apply an ID
and/or class to a div one should be able specify
those.  I suggest a CSS-like syntax inside braces
after the opening line of periods

    .... {#id .class}
    div content
    ....

One problem would be nested divs.  I suggest marking
those by indenting.  A code/pre block containing div
syntax would need to be doubly indented, similar to 
such blocks inside lists:

    .... {#outer_div}
    
    Para of outer div

        .... {#nested_div}
        
        Para of nested div.

        A code block illustrating div syntax
        (a most unusual thing!):

                ....{#example_div}
                This is how you specify a div
                ....

        Another para in nested div

        ....

    Another para in outer div

    ....
markdown
Of course one could mark nested divs by more periods in the
line (and then at least two more!):

    .... {#outer_div}
    
    Para of outer div

    ...... {#nested_div}
    
    Para of nested div.

    A code block illustrating div syntax
    (a most unusual thing!):

        ....{#example_div}
        This is how you specify a div
        ....

    Another para in nested div

    ......

    Another para in outer div

    ....

But I think indenting makes things cleaner, making it
easier to remember closing the divs you have opened, and not 
to close more divs than you have opened.  If you have very 
many nested divs you should probably pause and consider why 
anyway!

Google Code Info:
Issue #: 195
Author: bpjonsson
Created On: 2010-01-07T13:54:47.000Z
Closed On: 
</pre>

### PR DESCRIPTION
**Pull request by mpickering**
This is speculative - I want to move discussion forward by having something concrete to talk about. 

Closes #168

### CODE REVIEW

**Comment by ousia** [comment]
@mpickering, many thanks for this. It looks really awesome.

Contributing to the discussion (although I’m not sure whether this is the best place to do it): would it be possible to have also fenced spans (such as in `^span^{.class #identifier lang="grc"}`?

**Comment by bpj** [comment]
@mpickering: please note what @jgm said at <https://github.com/jgm/pandoc/issues/168#issuecomment-65944322>.  I don't think 'uparrow' makes very much sense in this context.
Note that we already have `^superscript^` and I think `^^smallcaps^^` would be nice, the 'uparrows' being iconic for 'kind of uppercase'.
(Also it so happens that since they are 'accents' all of `` ~ ` ^ `` are shift/altgr deadkeys on my Swedish keyboard, so I must hold down shift/altgr and hit one of those keys six times to get three of those characters For some odd reason hitting the same key more than three or four times in a row is annoying. :-)  So I for one would be very grateful for `:::` instead of `^^^`!  I would be even more grateful if you implement `[span text]{ATTRIBUTES}` as well (and `^^smallcaps^^` if I dare ask! :-).

**Comment by ousia** [comment]
@mpickering, I agree with both proposals from @bpj: `[span]{.class #identifier lang="grc"}` and `^^small caps^^`.

In that case, a more consistent syntax for fenced blocks would be:

```
[[[ {.warning #fenced-block-1}
This is a fenced div block.

With multiple pagragraphs.
]]]
```

Using different starting and closing characters makes nesting easier for the end user (so that indentation isn’t mandatory for nesting).

**Comment by tarleb** [comment]
Superseded by fda0c0119f415c6df95b20730650388c0471241d.

**Pull request closed without merging**
