### PR TITLE
Fix for #2083 (citation suffix clashes with links and footnotes)

### LINKED ISSUE #2083: Citation - footnote collision
Placing a footnote after a citation results in unexpected output.

For example, suppose I have the following in demo.md

    Source materials include @fenner2012a[^1] and class notes.

    [^1]: Subscription required.

and process it with

    $ pandoc demo.md --from=markdown+citations --filter pandoc-citeproc -o demo.pdf

The result in the pdf looks like

    Source materials include Fenner (2012 ˆ1) and class notes.

    Fenner, Martin. 2012. “One-Click Science Marketing.” Nature Materials 11 (4).
    Nature Publishing Group: 261–63. doi:10.1038/nmat3283.

Notice that there is no footnote, and `^1` appears in the citation.  Putting a space between the citation and the footnote gives the same result.

The full `demo.md` for my test is as follows:

```
Source materials include @fenner2012a[^1] and class notes.

[^1]: Subscription required.

---
references:
- id: fenner2012a
  title: One-click science marketing
  author:
  - family: Fenner
    given: Martin
  container-title: Nature Materials
  volume: 11
  URL: 'http://dx.doi.org/10.1038/nmat3283'
  DOI: 10.1038/nmat3283
  issue: 4
  publisher: Nature Publishing Group
  page: 261-263
  type: article-journal
  issued:
    year: 2012
    month: 3
...
```

### PR DESCRIPTION
**Pull request by lierdakil**
Closes #2083

Footnotes: check if '^' follows '['
Links: check if '[' or '(' follows ']'

### CODE REVIEW

**Comment by lierdakil** [comment]
Okay, so shorthand links are fixed as well, although I'm not sure if it's a good way to do it (essentially duplicating code from `referenceLink` parser)

**Comment by jgm** [comment]
If code is being duplicated, can the duplicated part be factored out into a separate function that is used both by `referenceLink` and here?

**Comment by lierdakil** [comment]
I figured out that I can simply use `referenceLink` and still stay lazy enough. This is probably a little suboptimal, but alternative is somewhat convoluted.

**Comment by jgm** [comment]
+++ Nikolay Yakimov [Apr 17 15 21:07 ]:
>   I figured out that I can simply use referenceLink and still stay lazy
>   enough. This is probably a little suboptimal, but alternative is
>   somewhat convoluted.

Are you going to submit a revised PR?

**Comment by lierdakil** [comment]
I did (forced update). However, now that you reverted back to F monad, I
have to revise this again... I'll get to it in a day or two.
19 апр. 2015 г. 1:06 пользователь "John MacFarlane" <
notifications@github.com> написал:

**Comment by lierdakil** [comment]
Ok, this should work. Wait for Travis just in case.

**Comment by lierdakil** [comment]
Travis looks happy. I think you can merge this now.

**Comment by jgm** [comment]
Great, just merged.

**Pull request merged**
