### PR TITLE
Latex template hyperref last

### PR DESCRIPTION
**Pull request by chroetz**
In the default.latex template, the hyperref package is moved down to be loaded last.

As mentioned in the [manual](https://ctan.net/macros/latex/contrib/hyperref/doc/hyperref-doc.html#x1-50003) of the LaTeX package [hyperref](https://ctan.org/pkg/hyperref), this package should be loaded last. 
This rule is applied to the default.latex template.

This fixes a bug: Links in the table of contents of PDF output referred to one page before the page where the respective section begins, if that section begins at the very top of the page.

### CODE REVIEW

**Comment by jgm** [comment]
Thanks.  See #5811 for a discussion of whether hyperref should go before or after header-includes.
There are some reasons to put it before, so that hyperref commands can be used in header-includes.
Since we also want header-includes to come before title, author, etc. (see #7295 for discussion), this means also before `\title`.

It seems to me that it should be safe to move header-includes forward, so they come right before `\title`, etc., and to move hyperref so it comes right before header-includes.

More radically, we could consider moving hyperref after header-includes but before `\title`.  This would have advantages if people load packages in header-includes that need to be modified by hyperref.  The drawback mentioned in #5811 is that users couldn't use hyperref commands in their header-includes. But, as noted in the comment there, it seems that an author could simply put `\usepackage{hyperref}` in header-includes if it's needed there; the redundant `\usepackage` that comes later wouldn't cause problems.

Comments welcome!

**Comment by chroetz** [comment]
Thanks for the comment. Sorry that I didn't see that this issue was already discussed.

My original problem of links in the toc that point to the wrong page is caused by using
```
\usepackage{titlesec}
\titleformat{...}
```
in *header-includes*. It can be solved by putting `\usepackage{hyperref}` only after that.

So, I think it would be best to put `\usepackage{hyperref}` after *header-includes* and let users use `\usepackage{hyperref}` in the *header-includes* if they need it there. As was mentioned and according to [this](https://tex.stackexchange.com/questions/79110/loading-a-package-more-than-once), only the first `\usepackage{hyperref}` is loading the package.

I close the PR as this was obviously a bit premature and I don't think I have the necessary insight to make sure that the change is robust.

**Comment by jgm** [comment]
@chroetz I think that's a good suggestion.  Are you planning to submit a new PR?
Alternatively, I could just make the change.

**Comment by chroetz** [comment]
> Are you planning to submit a new PR?
> Alternatively, I could just make the change.

I'd prefer if you make the change. 
Thanks!!

**Comment by jgm** [comment]
Done.

**Comment by memeplex** [comment]
I'm not entirely sure but I think this change may be causing some trouble. I'd like to configure hyperref to show underlined links, but my `\hypersetup` fragment specified in `header-includes` comes before this fragment introduced by pandoc at the end:

```
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
```

For now I think `boxlinks: true` is good enough for my needs, so this is just to notice that `\hypersetup` is perhaps being introduced too late in the preamble (maybe it fixes worse issues that way, I don't know).

**Comment by jgm** [comment]
See above https://github.com/jgm/pandoc/pull/7960?notification_referrer_id=NT_kwDNC-SvMzI1MjU5NzY4ODozMDQ0#issuecomment-1065334769
which I believe includes a workaround for you.

**Pull request closed without merging**
