### PR TITLE
Work in progress: Asciidoc reader

### PR DESCRIPTION
**Pull request by gbataille**
John, as discussed, this is a starting work on an asciidoc parser

### CODE REVIEW

**Comment by mpickering** [comment]
Hi @gbataille, here is how far I got implementing an asciidoc reader if it is useful for you. 

I remember that the list parsing rules are never properly specified which stalled me and eventually caused my to lose interest.

Here is the [branch](https://github.com/mpickering/pandoc/tree/asciidoc), it's been several months since I last touched it so my memory is faint about what I did and didn't implement!

**Comment by mpickering** [comment]
Although, I would urge you to try and avoid `F` at all costs!

**Comment by gbataille** [comment]
Funny about F. Gave me problem at the start to understand what it did but
actually ended up being ok (for what we did so far)

I'll try to have a look and see how we moght merge the effort. Just need to
find some time ;)

thanks

**Comment by arnaldorusso** [comment]
Does this commit related to the substitution of Title, section, subsection symbols used by pandoc?

    Title
    -------
    1. Introduction
    ~~~~~~~~~~~~~~~
    Subsection
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Used by pandoc to convert `asciidoc`

**Comment by gbataille** [comment]
@arnaldorusso I'm not understanding your question. This commit is about creating a brand new parser for the asciidoc format
It is actually a WIP

**Comment by arnaldorusso** [comment]
Hi @gbataille, sorry for not explain it more detailed. I saw that is a parser for asciidoc, but I would like to know if this parse code, will insert on the generated asciidoc the correct symbols for `Title`, `subtitle`, etc, as `=` to title (instead the usage of  `----` for title, `~~~~~` for section, etc; as is still occuring while parsing the .html to .asciidoc).
Sorry if this is not the place to ask this. 
Situations like this should be reported in a new ticket?

**Comment by gbataille** [comment]
Hey,

So this is just the parser. It does not generate any asciidoc artifact. The
writer for asciidoc has been there for a while and is on master already.

Cheers
Greg

**Comment by jgm** [comment]
It sounds as if you think there's a bug in the asciidoc *writer*.

So, you could open a new ticket, giving the pandoc version you're
using, the html input you used, the exact pandoc command line you
used, the actual and expected asciidoc output, and a link to
relevant asciidoc documentation.

Thanks!

+++ Arnaldo Russo [May 18 15 11:56 ]:

**Comment by pbronez** [comment]
Has work on this stalled? Looks like @gbataille made solid progress but the feature hasn't reached production.

**Comment by gbataille** [comment]
Hey Peter,

unfortunately it has completely stalled yes.
The 2 main reasons to that:
- I have had other side projects and a change of job that took a lot of time
- I had made (I think) a good first version that would serve a markdown
equivalent set of features (while missing the more advanced feature). I had
proposed it for inclusion to get feedback, check interest and maybe get
help also, but it was never merged so I got a bit discouraged.

I have just given my last conference of the year and am out of side
project, so if there is interest I might get back on it, but I can't
guarantee anything right now.

Cheers

**Comment by pbronez** [comment]
Thanks for the update @gbataille, sorry you weren't able to get the basic parser merged. Looks like @tarleb has pushed forward with a similar effort called [huskydoc](https://github.com/tarleb/huskydoc), but [isn't ready](https://github.com/jgm/pandoc/issues/1456#issuecomment-248406135) to merge it into pandoc.

I'm certainly interested in finding a full-fidelity way to get AsciiDoc into pandoc. My current use case is authoring legal documents on technical subjects. I need a robust AsciiDoc <--> MS Word capability to interface with lawyers and other muggles. Pandoc seems like the way to go for this. In the interim, even a one way AsciiDoc --> MS Word capability would be really useful, since it would let you do your initial draft more easily and start the email version control catastrophe with a healthy `.docx`.

The best solution I've found so far is:

- Write AsciiDoc
- Use [Asciidoctor](http://asciidoctor.org/) to create HTML
- Open HTML directly in MS Word.

The main challenge here is style sheets / templating... need to put more effort in there. My documents use several advanced AsciiDoc features that tend to get mangled when using pandoc's `docbook` and `html` support:

- Numbered section titles
- Tables with merged cells
- Internal links (particularly challenging!)

If someone's up to attack this I would be happy to contribute some tests.

P.S. I also considered [Legal Markdown](https://github.com/compleatang/legal-markdown) for this use case, but it's completely unmaintained.

**Comment by mb21** [comment]
> I have just given my last conference of the year and am out of side
project, so if there is interest I might get back on it, but I can't
guarantee anything right now.

There seems to be plenty of interest! Maybe you could rebase from master and remove the seemingly unrelated changes (e.g. `src/Text/Pandoc/Parsing.hs`, `.gitignore`, the dokuwiki and twiki stuff).

Not sure what exactly @jgm's policy is on `Test.Framework`... seems to be used in older tests, but since you've already written some tests... otherwise we just do something like using the existing asciidoc writer to generate a testfile with good coverage:

    pandoc -f native tests/writer.native -t asciidoc -o tests/asciidoc-reader.asciidoc

and then use your asciidoc reader to generate:

    pandoc tests/asciidoc-reader.asciidoc -o tests/asciidoc-reader.native

and check that file very carefully for errors before committing it as well.

**Comment by tarleb** [comment]
Most of my free coding time currently goes into the org reader and the lua interface, so huskydoc is stuck as well. I second what @mb21 stated, it would be great if you'd continue with your the reader @gbataille. I could try to help out if I find the time.

**Comment by gbataille** [comment]
Closing to remove pollution. Maybe I'll get back to it one day...

**Pull request closed without merging**
