### PR TITLE
Check if supplied FORMAT matches with an HTML slide deck value. Return True for isRawHtml.

### PR DESCRIPTION
**Pull request by coatless**
This PR attempts to close out the `HTML` writer portion of #8880. 

The change implement seeks to check whether `f` is part of the supported HTML slide formats. Thus, if we have a code block in `revealjs` of:

````md
```{=revealjs}
Hello there!
```
````

The text will be retained and treated as raw in the output format, e.g. 

```
Hello there!
```

Presently, the text will be deleted in the output, e.g. 

````md
````

We've supplied a sample test document.

If this is okay, we can submit a follow-up PR to address the EPUB issue or add it into this PR.

<details>
<summary> Test Markdown Document </summary>

````markdown
---
title: Test HTML Raw Fix
author: JJB
date: Sept 29, 2023
---

# Test Slide Format Retention

```{=revealjs}
Retain this text as we're under `revealjs`
```

```{=s5}
Retain this text as we're under `s5`
```

```{=slidy}
Retain this text as we're under slidy
```

```{=slideous}
Retain this text as we're under slideous
```

```{=dzslides}
Retain this text as we're under dzslides
```

# Verify HTML content is retained

```{=html}
Retain Hard `html` tag content
```

```{=html4}
Retain Hard `html4` tag content
```

```{=html5}
Retain Hard `html5` tag content
```

# Verify LaTeX via MathJax is okay

Verify we're okay with Math/LaTeX blocks.

$1 + 1$

# Check other raw block formats do not come through

There should be no warning after this ... 

```{=toad}
WARNING CONTENT WAS NOT DROPPED 
```
````
</details>

### CODE REVIEW

**Comment by coatless** [comment]
Note, the CI linux stack failure is related to the prior dependency update that was committed into the master branch earlier today. 

Dependency up issue:
https://github.com/jgm/pandoc/commit/2c6f22d2b4edd9fb8b8576995d7aece99feef207

CI Noting the dependency:
https://github.com/jgm/pandoc/actions/runs/6333279364/job/17201158316?pr=9110#step:6:26

**Comment by dlsun** [comment]
I just wanted to signal-boost this pull request, as it is blocking https://github.com/coatless/quarto-webr/issues/14, which would be really useful for my teaching!

**Comment by jgm** [comment]
thanks!

**Comment by dlsun** [comment]
This patch is needed to make WebR usable in slides [coatless/quarto-webr#14](https://github.com/coatless/quarto-webr/issues/14). A number of us are trying to use this in our classes right now, so we are eagerly awaiting the next point release of Pandoc so that this patch can be incorporated into Quarto. Is there an ETA on the next release?

**Comment by jgm** [comment]
No specific ETA, no.  But you should be able to work around this issue by specifying `{=html}` in the slide decks.

**Comment by coatless** [comment]
@jgm unfortunately, we're locked with supplying `{=revealjs}` due to Quarto c.f. initial discussion by @cderv in https://github.com/jgm/pandoc/issues/8880. Based on the previous release cadence, wouldn't you aim for a new release on the 8th of October or so?

**Comment by jgm** [comment]
No previous quick release cadence was because I prioritize fixing regressions.

**Comment by coatless** [comment]
Ah, well whenever you have an opportunity, it would be great to get a new point release. 

No rush as we'll have to update the included copy of pandoc in Quarto.

**Pull request merged**
