### PR TITLE
default.latex: Do not apply linestretch to title

### PR DESCRIPTION
**Pull request by karland**
See: Kohm, M. (2018). KOMA-Script. p45.

### CODE REVIEW

**Comment by jgm** [comment]
This is a fairly verbose change in the generated latex.

See #5179, which proposes putting the setspace command after `\begin{document}` in order to handle a mysterious bug that arises with asian languages.  If we put the setspace command after `\maketitle`, then I believe it would handle this issue too, in a much less verbose way.

**Comment by karland** [comment]
Well, I was working through the KOMA-Script book and came across this issue. Kohm suggests the solution that is in this PR, so I just took it over. I was not so concerned about verbosity, but fair enough. 

I understand the issue because the generation of the title page is quite some piece of code and it seems to be negatively impacted by a line spacing larger than 1.

**Comment by adunning** [comment]
In testing this further, I've realized that not only `\maketitle` but also `\tableofcontents`, `\listoffigures`, and so forth are also affected negatively by changing the line spacing. I've added a new PR at <https://github.com/jgm/pandoc/pull/5378> to allow for testing this.

**Comment by adunning** [comment]
I need to test this theory, but logically, using `\setstretch` outside the preamble will probably cause the height of the text block to come out unrounded to the number of lines, which can leave extra space between paragraphs. This isn't terrifically noticeable unless one is using indented paragraphs, and I doubt whether many people are using the `heightrounded` option in geometry in any case. But it might be better to manually set areas to single spacing, as this proposes. We need to balance the tradeoffs between partially dealing with #5179 and simplicity of code on the one hand, and adding an extra environment on the other hand.

Another consideration: should the abstract be single-spaced, or should single spacing be applied only to `\maketitle` and the various lists in the front matter?

**Comment by karland** [comment]
@adunning Thanks for working on this.

**Comment by jgm** [comment]
The issue is fixed by #5378.
If the fix in #5378 turns out to be a bad idea, we can revisit.

**Pull request closed without merging**
