### PR TITLE
add template variables for source and destination filename

### PR DESCRIPTION
**Pull request by rohieb**
see #3431

### CODE REVIEW

**Comment by jgm** [comment]
I'd prefer:

- `sourcefile`, a list of the input file names (empty if stdin)
- `outputfile`, the output file name

If you want to have it print `(stdin)`, this can be done with a conditional in the template.

```
$if(sourcefile)$
$for(sourcefile)$
$sourcefile$
$endfor$
$else$
(stdin)
$endif$
```

What do you think?

**Comment by rohieb** [comment]
Yes, this makes the code simpler, and simplicity is always a good idea. I've allowed myself to put your template snippet into the manual as an example how to handle the variables.

Looking at the tests, I find it a bit annoying that conversion to markdown now writes the sourcefile and outputfile into the Markdown output – I really only had intended them to be used in user-defined templates. What do you think, does that bother you?

**Comment by rohieb** [comment]
(see [Travis log, L705](https://travis-ci.org/jgm/pandoc/jobs/205154181#L705))

**Comment by jgm** [comment]
+++ Roland Hieber [Feb 24 17 18:34 ]:
>   (see [1]Travis log, L705)

This is precisely why you need to add them as variables,
not as metadata.

**Comment by rohieb** [comment]
On 25.02.2017 12:50, John MacFarlane wrote:
> +++ Roland Hieber [Feb 24 17 18:34 ]:
>> (see [1]Travis log, L705)
> 
> This is precisely why you need to add them as variables,
> not as metadata.

Wait, I'm confused. In [1] you said I should add them to
writerVariables, and I think that's what I did here. Is there some place
else where I should add them?

[1] https://github.com/jgm/pandoc/issues/3431#issuecomment-279236546

**Comment by jgm** [comment]
No, you did the right thing. I jumped to conclusions from the travis output, but in fact this seems to point to a bug somewhere else... I'll investigate.

**Comment by jgm** [comment]
OK, this should be fixed now.

**Comment by jgm** [comment]
I fixed a few more things with subsequent commits.  Glad you unearthed that bug; the Markdown writer was leaking variables in metadata blocks.

**Comment by rohieb** [comment]
Happy to help :smile: But more importantly, happy for your help and patience, @jgm and @mb21! This was a great opportunity for me to get to know Haskell and pandoc more :smiley:

**Comment by jgm** [comment]
We're always on the lookout for new contributors!

+++ Roland Hieber [Feb 25 17 18:05 ]:
>   Happy to help 😄 But more importantly, happy for your help and patience,
>   [1]@jgm and [2]@mb21! This was a great opportunity for me to get to
>   know Haskell and pandoc more 😃

**Pull request merged**
