### PR TITLE
OpenDocument Writer: Implement span with ident support

### PR DESCRIPTION
**Pull request by pyssling**
Spans containing an ident in the Attr will become bookmarks
in OpenDocument format.

### CODE REVIEW

**Comment by jgm** [comment]
Could you do the same for Divs?

**Comment by pyssling** [comment]
Please don't merge yet - I need to verify this a bit.

**Comment by pyssling** [comment]
Ok, this should be correct - and is in fact better than what I hoped for - Divs in Pandoc are now (if they contain an ident) mapped to a section in OpenDocument. This is very clean and seems to be completely consistent with the intention of Div.

**Comment by jgm** [comment]
Divs can be used for a number of things that might not be considered sections -- e.g., sidebars.  I don't know what the semantics of "section" is in opendocument, though -- if it's generic enough, this is probably right.

**Comment by pyssling** [comment]
It seems to be very generic (though of course with more uses than this one):

The <text:section> element represents a named portion of content in a document.

Sections specify formatting properties for a region of text or  text that is automatically acquired from an external data source or document, or another text section.

https://docs.oasis-open.org/office/OpenDocument/v1.3/cs01/part3-schema/OpenDocument-v1.3-cs01-part3-schema.html#element-text_section

**Comment by pyssling** [comment]
@jgm this one should be ready to go now - added a test case.

**Comment by jgm** [comment]
looks good!

**Pull request merged**
