### PR TITLE
LaTeX writer: convert zero width non-joiner char into TeX command

### PR DESCRIPTION
**Pull request by tarleb**
Closes: #6639

### CODE REVIEW

**Comment by tarleb** [comment]
Please read https://github.com/jgm/pandoc/issues/6639#issuecomment-841722028 before merging.

**Comment by jgm** [comment]
The original issue has the babel definition
```
\def\ZWNJ{%
  \texorpdfstring{%
    \TextOrMath{%
      \penalty\@M
      \discretionary{-}{}{\kern.03em}%
      \ifvmode
      \else
        \nobreak
        \hskip\z@skip
      \fi}{}%
  }{}%
}
```
The definition you use here is simpler. How did you arrive at it?  Are the simplifications okay?

**Comment by tarleb** [comment]
I *think* it's ok, but it might not be. The simplification of leaving out `\TextOrMath` is ok, because we don't emit the command in math mode; also `\nobreak` is in the TeX core and defined as `\penalty\@M`. I get less sure when it comes to the missing `\nobreak\hskip\z@skip`: it *might* be ok. Maybe I don't understand TeX well enough to see why it would be needed in this position, and my tests all returned the expected result. If we want to play it safe, we could use `\nobreak\hskip\skip11`, which should have the same meaning, to avoid a pesky `\makeatletter`. I'm also slightly unsure about `\ifvmode`, as I fail to see how the engine could be in vertical mode at that point, but this might also just show my limited understanding of TeX.

**Comment by tarleb** [comment]
To expand on the `\nobreak\hskip\z@skip` info a little: This command sequence comes from the babel macro `\def\bbl@allowhyphens{\ifvmode\else\nobreak\hskip\z@skip\fi}`, which is documented as follows:

> In several languages compound words are used. This means that when TeX has to hyphenate such a compound word, it only does so at the `-` that is used in such words. To allow hyphenation in the rest of such a compound word, the macro `\bbl@allowhyphens` can be used.

All my tests (as well as my limited understanding of the matter) indicate that the macro is not necessary in this case. E.g., hyphenation of `Dorf&zwnj;idyllengenießerin` works as expected for various box sizes.

**Comment by tarleb** [comment]
Argh. Made an error while testing: turns out the `\nobreak\hskip\skip11` *is* needed for proper hyphenation. I've amended the commit.

**Comment by tarleb** [comment]
Closing in favor of #7291.

**Pull request closed without merging**
