### PR TITLE
ConTeXt writer: attempt to generate PDF/A

### LINKED ISSUE #3215: Option to convert to PDF/A
The PDF/A standard is designed for the archival of information, i.e. it ensures that there are no dependencies in the way the file is created, which would prevent it from remaining viewable, over time, exactly as it was when it was created. It is especially important for libraries, governments, and any entity interested in ensuring that information remains accessible over long periods of time. A Description of the PDF/A standard is available here:
https://en.wikipedia.org/wiki/PDF/A

It would be great to have an optional parameter on Pandoc, which would create PDF/A files without requiring the end-user to understand its technical requirements.

### PR DESCRIPTION
**Pull request by hmenke**
Adresses #3215 

---

As a demo I used this minimal markdown example:
```markdown
# First section

Hello World!
```
I generated ConTeXt source using
```bash
pandoc -f markdown -t context -s -o test.tex test.md
```
and produced a PDF using ConTeXt standalone with the required ICC profiles installed.  The resulting PDF can be verified using the [Apache PDFBox](https://pdfbox.apache.org/) preflight app.
```
$ java -jar preflight-app-2.0.8.jar test.pdf 
The file test.pdf is a valid PDF/A-1b file
```
Instructions on how to install the ICC profiles on ConTeXt standalone can be found in the wiki: http://wiki.contextgarden.net/PDFX#ICC_profiles

---

If the ICC profiles are not available the log will contain messages like these
```
backend         > profiles > profile specification 'sRGB.icc' loaded from '/usr/local/texlive/2017/texmf-dist/tex/context/colors/icc/context/colorprofiles.xml'
backend         > profiles > error, couldn't locate profile 'srgb.icc'
backend         > profiles > no default profile 'srgb.icc' for colorspace 'rgb'
backend         > profiles > profile specification 'sRGB IEC61966-2.1' loaded from '/usr/local/texlive/2017/texmf-dist/tex/context/colors/icc/context/colorprofiles.xml'
backend         > profiles > error, couldn't locate profile 'srgb.icc'
backend         > profiles > invalid output intent 'sRGB IEC61966-2.1'
```
and the resulting PDF will not be valid PDF/A
```
$ java -jar preflight-app-2.0.8.jar test.pdf 
The file test.pdf is not a valid PDF/A-1b file, error(s) :
2.4.3 : Invalid Color space, The operator "g" can't be used without Color Profile on page 1
2.4.3 : Invalid Color space, The operator "G" can't be used without Color Profile on page 1
2.4.3 : Invalid Color space, /DeviceGray default for operator "TJ" can't be used without Color Profile on page 1
2.4.3 : Invalid Color space, /DeviceGray default for operator "TJ" can't be used without Color Profile on page 1
2.4.3 : Invalid Color space, The operator "g" can't be used without Color Profile on page 1
2.4.3 : Invalid Color space, The operator "G" can't be used without Color Profile on page 1
2.4.3 : Invalid Color space, /DeviceGray default for operator "TJ" can't be used without Color Profile on page 1
```
but the PDF will still be generated and the "errors" shown in the log do not break anything.

### CODE REVIEW

**Comment by jgm** [comment]
Would it be cleaner to make this conditional on the `pdfa` variable?

**Comment by hmenke** [comment]
That is a good idea.  I also added some docs.

**Comment by wilx** [comment]
What colour profile it is looking for?

**Comment by wilx** [comment]
sRGB? Can't we ship sRGB profile from http://www.color.org/srgbprofiles.xalter? It seems to have very permissive license:

> To anyone who acknowledges that the file "sRGB_v4_ICC_preference.icc" is provided "AS IS" WITH NO EXPRESS OR IMPLIED WARRANTY, permission to use, copy and distribute this file for any purpose is hereby granted without fee, provided that the file is not changed including the ICC copyright notice tag, and that the name of ICC shall not be used in advertising or publicity pertaining to distribution of the software without specific, written prior permission. ICC makes no representations about the suitability of this software for any purpose.

**Comment by jgm** [comment]
I'd rather not get into the business of distributing such files with pandoc, even if the licensing terms allow it.

**Comment by hmenke** [comment]
@wilx I have documented which color profiles you need and where to get them.

https://github.com/jgm/pandoc/blob/0ef56657edc84654a00fe609b432b15271349c26/MANUAL.txt#L1627-L1645

**Pull request merged**
