### PR TITLE
DocBook reader: bibliomisc and anchor support

### PR DESCRIPTION
**Pull request by pyssling**
Support for bibliomisc and anchors which are used to link into
bibliomisc. Also refactor the bibliography into a bulletin list
(each under a bibliodiv if present). This is more consistent with
other DocBook behavior than just using paragraphs for each entry.

### CODE REVIEW

**Comment by jgm** [comment]
I'm not sure about using bullet lists for the bibliography. In general, this looks bad -- hardly any real bibliography styles would want bullets.  Can you link to something that explains the behavior you're trying to be consistent with?

**Comment by pyssling** [comment]
Asciidoctor default output - but honestly - the bulleted list is unimportant to me. I can as well go for distinct paragraphs - or please suggest something.

**Comment by pyssling** [comment]
Ok, I reverted to the previous behavior. If someone in my organization wants it in a bulletin list I think we can do that through a custom filter or similar. Now it's just paragraphs.

**Comment by jgm** [comment]
thanks!

**Pull request merged**
