### PR TITLE
latex.default: add fontfamilydefault option.

### PR DESCRIPTION
**Pull request by karland**
This allows the font to be changed for the whole document.

+ [https://www.latex-project.org/help/documentation/fntguide.pdf](https://www.latex-project.org/help/documentation/fntguide.pdf)
    See: p8.

+ [https://tex.stackexchange.com/questions/58833/effect-of-changing-fontfamily-and-familydefault](https://tex.stackexchange.com/questions/58833/effect-of-changing-fontfamily-and-familydefault)

+ [https://texwelt.de/wissen/fragen/785/wie-stelle-ich-alle-schrift-in-meinem-dokument-auf-serifenlos](https://texwelt.de/wissen/fragen/785/wie-stelle-ich-alle-schrift-in-meinem-dokument-auf-serifenlos)
    (in German)

### CODE REVIEW

**Comment by jgm** [comment]
@adunning - could I get your feedback on this proposal?

**Comment by adunning** [comment]
@karland Would you mind illustrating the functionality that this would add? This is more easily specified through fontspec and/or KOMA-Script, though you can always add a line such as this through the `header-includes` variable.

**Comment by karland** [comment]
pandoc is great! In the context of LaTeX is amongst other things so great because people can go from Markdown to PDF (via LaTeX) without knowing very little about LaTeX. 

In addition, KOMA classes are probably the standard in the meantime. However, other then standard LaTeX, titles and section headers are in sans serif whereas text is in roman. Even though there are good typographical reasons for it as described by the author of KOMA-script sometimes articles or books need to use the same font type. When I was researching this issue, I found that the **easy option** to achieve this was missing in pandoc. Of course there might be other possibilities to get this done, however, I feel, fonts in LaTeX already require some deeper knowledge, so I felt this option would make it easier for the user and provide some guidance.

**Comment by adunning** [comment]
If your aim is to use a serifed font for the KOMA-Script headings, it's much more reliable to add its own command for taking care of this using `header-includes` (plus the same mechanism allows you to achieve many other things):

```shell
pandoc -o test.pdf << EOT

---
documentclass: scrartcl
title: Test
header-includes:
- \setkomafont{disposition}{\normalfont}
---

# A test

Test

EOT
```

**Comment by karland** [comment]
@adunning Thanks.

**Pull request closed without merging**
