### PR TITLE
Implement changes in ScriptingEngine

### PR DESCRIPTION
**Pull request by jgm**
See #8417.

@tarleb I left the changes to pandoc-lua-engine to you (I made the most obvious ones).
The second commit in this draft PR outlines what remains to be done.

### CODE REVIEW

**Comment by tarleb** [comment]
Will do. I'm currently knee-deep in figure handling; trying to finish that first.

**Comment by tarleb** [comment]
I started to work on this. One question I have is how we should handle files in the `$DATADIR/readers` and `$DATADIR/writers` directories. Should we simply check both for suitable scripts? Also should we start to search `$DATADIR/custom` for .lua files when running `customLoadScript`?

**Comment by jgm** [comment]
>  One question I have is how we should handle files in the $DATADIR/readers and $DATADIR/writers directories. Should we simply check both for suitable scripts? Also should we start to search $DATADIR/custom for .lua files when running customLoadScript?

Yes, I wondered about this too.  How long ago did we add support for `readers` and `writers` directories?  Was it in a released version?  It is tempting to consolidate and just have a `custom` directory that could contain either a reader or a writer or a reader/writer.

**Comment by tarleb** [comment]
Checking the changelog it seems that this feature was released in pandoc 2.19. Probably fine if we phase that out over the next year or so.

**Comment by jgm** [comment]
For now we could search in both places and deprecate use of readers/writers?
But actually I'd be tempted just to make a clean break (3.0 after all) and document the change prominently.  I doubt too many people are using it yet.

**Comment by tarleb** [comment]
Sounds good. Hope it's ok that I've pushed a rebased and updated version to your branch.

I've dropped the fallback handling of custom readers that expect string input instead of the actual Sources list, but could also put that code back.

**Pull request closed without merging**
