### PR TITLE
Add chromium pdf engine

### PR DESCRIPTION
**Pull request by arsalan0c**
Hi. This PR adds Chromium as a supported HTML pdf engine. 
Chromium's headless mode and pdf printing switch is used.

Example usage:
`cabal run pandoc-cli -- --pdf-engine=chromium -o test.pdf test.html`

### CODE REVIEW

**Comment by jgm** [comment]
Thanks! Can you say a bit about the comparative advantages/disadvantages of chromium compared to the other html->pdf engines?

**Comment by jgm** [comment]
Two more places that need updating:

- MANUAL.txt (under `--pdf-engine`)
- src/Text/Pandoc/App/CommandLineOptions.hs htmlEngines line 218

**Comment by arsalan0c** [comment]
> Two issues here:
> 
> * Chromium binaries go by a lot of different names on different systems, and the FOSS builds go by different names than the upstream-built binary Chrome builds. Any attempt to assume one name is bound to bring up questions about why they aren't all supported, and this has no configuration mechanism.
> * Specifically why would it by advantageous to use a headless chromium over and above `paged-js` which is already an option which also uses headless Chromium under the hood but wraps it in a bunch of typesetting related features and style improvements targeting PDFs as a print or at least paged medium? Stock chromium print output leaves a lot to be desired along those lines.

Thanks for pointing these out. 

For the first, I've added a commit ([597515b](https://github.com/jgm/pandoc/pull/8609/commits/597515b677b0209e5adef2a9303f8705ed9e16e7)) to allow the path to the binary to be specified. 

I wasn't aware of `pagedjs-cli` offering improvements over chromium, it does seem to be a better option in every situation. I see motivation for adding chromium as a convenient alternative, in case one already has chromium installed would prefer not to install another engine. Or in the unlikely event there are installation issues with the other engines. This perhaps may not be a compelling reason for the addition although I think the changes are minor and will not add burden for maintenance.

**Comment by jgm** [comment]
I'll close this because paged-js just seems a better option.

**Pull request closed without merging**
