### PR TITLE
ImageSize: add derived Eq instance to Dimension

### PR DESCRIPTION
**Pull request by jkr**
@jgm: Any objections? It will allow me to derive Eq on some picture props in the Powerpoint writer. (With given caveat that pixel equality depends on dpi).

### CODE REVIEW

**Comment by jgm** [comment]
My only reservation is that with the derived instance, `Centimeter 10.0` won't be equal to `Millimeter 100.0`.  But maybe this is desirable?

**Comment by jkr** [comment]
I think it would probably be desirable, since it would distinguish between comparing `Dimension` (i.e. something set in attributes) and measurement (which depends on dpi in some cases, meaning of percentage). It might or might not be meaningful that one thing is in inches, the other is in cm. The measurement might be the same, the dimension different.

**Comment by jgm** [comment]
OK, no objections then.

+++ Jesse Rosenthal [Jan 15 18 10:37 ]:

**Comment by jkr** [comment]
Cool -- it's part of another series of changes that I don't quite have working yet, so I'll add it with those.

**Pull request closed without merging**
