### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by deining**
This PR fixes a few typos I spotted in the project.

### CODE REVIEW

**Comment by jgm** [comment]
Thanks!  Looks like the reflowing changed in one of the test files, this should be easy to fix.
https://github.com/jgm/pandoc/actions/runs/11654732857/job/32448590526?pr=10349#step:9:4251

**Comment by deining** [comment]
> Thanks!

You are welcome!

> Looks like the reflowing changed in one of the test files,
this should be easy to fix.

I had a short glimpse at it, but wasn't able to resolve that issue immediately.
@jgm: Can you step in please? I'm not familiar with the project internals at all, so feel free to take this task over. Adding another commit that resolves the issue is highly appreciated!

**Comment by jgm** [comment]
Easiest way to fix it is:
```
make TESTARGS=--accept
```
Then `git diff` to make sure the changes look right.

**Comment by jgm** [comment]
I edited the file right in GH, let's see if it checks now.

**Comment by jgm** [comment]
Merged, thank you!

**Pull request merged**
