### PR TITLE
Docbook writer: handle admonitions

### PR DESCRIPTION
**Pull request by jtojnar**
Similarly to https://github.com/jgm/pandoc/commit/d6fdfe6f2bba2a8ed25d6c9f11861774001f7a91, we should handle admonitions in Docbook writer as well.

### CODE REVIEW

**Comment by jtojnar** [comment]
Seems to work fine with `docbook`→`docbook` conversion:

```ShellSession
$ cabal run pandoc -v0 -- test.xml -f docbook -t docbook5
<section xml:id="sect">
  <title>sect</title>
  <note xml:id="foo">
    <title>foo</title>
    <para>
      content
    </para>
  </note>
</section
```

And markdown too, as long as I do not use a title:

```markdown
# sect
::: note
content
:::
```

```ShellSession
$ cabal run pandoc -v0 -- test.md -f markdown -t docbook
<section xml:id="sect">
  <title>sect</title>
  <note>
    <para>
      content
    </para>
  </note>
</section>
```

but once I add a heading it breaks:

```markdown
# sect
::: note
# foo
content
:::
```

```ShellSession
$ cabal run pandoc -v0 -- test2.md -f markdown -t docbook
<section xml:id="sect">
  <title>sect</title>
  <para>
  </para>
</section>
<section xml:id="foo">
  <title>foo</title>
  <para>
    content
  </para>
</section>
```

It does not even seem to visit the `Div` branch of `blockToDocbook`.

If I use the block syntax for the title too, as expected by the AST, it is parsed as `note` but then there is a paragraph in the title. And it is also quite ugly:

```markdown
# sect
::: note
:::: title
foo
::::
content
:::
```

```ShellSession
<section xml:id="sect">
  <title>sect</title>
  <note>
    <title><para>
      foo
    </para></title>
    <para>
      content
    </para>
  </note>
</section>
```

**Comment by jgm** [comment]
It would be good to have some tests for this feature. (At least command tests (see test/command).)

**Comment by jtojnar** [comment]
Thanks, wanted to ask about how to best test this but forgot about it. Command tests will work great, I think. Actually, just noticed `test/Tests` directory, which I somehow missed when looking the last time. I might just create unit test instead.

**Comment by jtojnar** [comment]
I have added unit tests for the admonitions as well as the rest of the `Div` handling code paths. That should be nicer than command tests.

I have not added tests for `xml:id` usage since it is straightforward and the tests would be the same, except for using `xml:id` and `version = DocBook5`.

**Comment by jtojnar** [comment]
I have also removed the attempt at specifying admonition titles from Markdown as they are not actually defined anywhere and my attempt fails for reasons I do not understand:

```patch
diff --git a/src/Text/Pandoc/Writers/Docbook.hs b/src/Text/Pandoc/Writers/Docbook.hs
index 398920839..c5c3f4208 100644
--- a/src/Text/Pandoc/Writers/Docbook.hs
+++ b/src/Text/Pandoc/Writers/Docbook.hs
@@ -203,6 +203,8 @@ blockToDocbook opts (Div (ident,classes,_) bs) = do
                 case bs of
                   -- Matches AST produced by the Docbook reader.
                   (Div (_,["title"],_) ts : rest) -> (Just (blocksToDocbook opts ts), rest)
+                  -- Matches AST generated from Markdown, TODO: I was not able to trigger this branch.
+                  (Header _lvl _ ts : rest) -> (Just (inlinesToDocbook opts ts), rest)
                   _ -> (Nothing, bs)
         admonitionTitle <- case mTitleBs of
                               Nothing -> return mempty
diff --git a/test/Tests/Writers/Docbook.hs b/test/Tests/Writers/Docbook.hs
index 1d53dcfe7..a0fc2736e 100644
--- a/test/Tests/Writers/Docbook.hs
+++ b/test/Tests/Writers/Docbook.hs
@@ -93,6 +93,19 @@ tests = [ testGroup "line blocks"
                                     , "  </para>"
                                     , "</attention>"
                                     ]
+          , "admonition-with-heading" =:
+                            divWith ("foo", ["attention"], []) (
+                              header 1 (text "This is title") <>
+                              para "This is a test"
+                            )
+                              =?> unlines
+                                    [ "<attention id=\"foo\">"
+                                    , "  <title>This is title</title>"
+                                    , "  <para>"
+                                    , "    This is a test"
+                                    , "  </para>"
+                                    , "</attention>"
+                                    ]
           , "single-child" =:
                             divWith ("foo", [], []) (para "This is a test")
                               =?> unlines
```


```haskell
admonition-with-heading: FAIL
  test/Tests/Helpers.hs:50:
  
  -------------------------------------------------------------- input ---
  [Div ("foo",["attention"],[])
   [Header 1 ("",[],[]) [Str "This",Space,Str "is",Space,Str "title"]
   ,Para [Str "This",Space,Str "is",Space,Str "a",Space,Str "test"]]]
  ------------------------------------------------------------- result ---
  - <attention id="foo">
  + <sect1 id="foo">
      <title>This is title</title>
      <para>
        This is a test
      </para>
  - </attention>
  + </sect1>
  ------------------------------------------------------------------------
```

It would be nice to be able to use admonition titles from Markdown but we only have four admonitions with titles in Nixpkgs docs so getting much more common general admonitions merged takes priority.

**Comment by jtojnar** [comment]
I guess it makes most sense to handle the AST produced by the Markdown reader so I have started stripping the `Para` inside `Div.title`.

Alternative would be changing the Docbook reader to use a `Header 1` for the admonition title but that would be potentially confusing or invalid for some readers/writers like it is for the `makeSections` function called by the DocBook writer. We would need to make sure all readers and writers support sectioning as described, for example, in the [HTML 5 specification](https://html.spec.whatwg.org/multipage/sections.html#headings-and-sections):

> Sections may contain headings of any rank, but authors are strongly encouraged to either use only `h1` elements, or to use elements of the appropriate rank for the section's nesting level.

**Comment by jgm** [comment]
This looks good to me -- thanks!

**Pull request merged**
