### PR TITLE
Lua: add function `pandoc.make_writer`.

### PR DESCRIPTION
**Pull request by tarleb**
This can be used to reduce boilerplate in custom writers.

Closes: #8373

### CODE REVIEW

**Comment by tarleb** [comment]
Left to do:

- [ ] add default functions
- [ ] add warnings
- [ ] possibly rename items.
- [ ] more usability improvements, if any

Example use in djot: https://github.com/tarleb/djot/commit/d6a2d934d44bbe69b69c72fead6a995a4dfbb026
There's a minor difference in that the `Inline` rendering functions are collected in table `Inline`, vs. `Inlines` in the djot writer. The `Writer.Inline` function can then be used to render any Inline element, similar to what we do in filters.

A minor usability improvement: `return pandoc.layout.concat{...}` seems like such a common pattern that the function call to `concat` can now be omitted.

Performance is roughly unchanged to the manual version.

Happy to add more features were possible.

**Comment by tarleb** [comment]
The filter currently doesn't enforce the division of `Inline` and `Block` functions: defining `Writer.Emph` is equivalent to setting `Writer.Inline.Emph`. Not sure I like that though.

**Comment by tarleb** [comment]
Additional changes:

- We allow `Writer.Inline.Space` etc. to be plain `Doc` values; saves a little bit of typing and gives a small performance boost (it saves the marshaling step each time a Space is converted.
- All functions get `WriterOptions` as the second parameter. E.g., SoftBreak in `djot` would read
    ``` lua
    Inlines.SoftBreak = function (el, opts)
      if opts.wrap_text == "wrap-preserve" then
        return cr
      else
        return space
      end
    end
    ```

djot: https://github.com/tarleb/djot/commit/d682d018f8c8fd26e7bd40aef64b1bfdca2b8441

**Comment by jgm** [comment]
This is looking good!

**Comment by jgm** [comment]
I don't think I can be much help here, I don't know much about Lua stack tracing!

**Comment by jgm** [comment]
Your HsLua suggestion sounds worth a try, but I don't know enough about it to offer an informed opinion!
What do the error messages above look like after your cleanup?

**Comment by tarleb** [comment]
Error message when there's an error in `Str` for input `Emph [Str ""]`:

```
Error running Lua:
../testing/custom-writer.lua:18: intentional error
stack traceback:
        ../testing/custom-writer.lua:18: in function <../testing/custom-writer.lua:17>
        [C]: in field 'Inlines'
        ../testing/custom-writer.lua:15: in function <../testing/custom-writer.lua:14>
        [C]: in field 'Inlines'
        ../testing/custom-writer.lua:9: in function <../testing/custom-writer.lua:8>
        while rendering Inline `Str`
        while rendering Inlines
        while rendering Inline `Emph`
        while rendering Inlines
        while rendering Block `Para`
        while rendering Blocks
        while rendering Pandoc
stack traceback:
```

When there's no render function for an element:

```
Error running Lua:
No render function for Inline value 'Link';
define a function `Writer.Inline.Link` that returns a string or Doc.
stack traceback:
        ../testing/custom-writer.lua:9: in function <../testing/custom-writer.lua:8>
        while rendering Block `Para`
        while rendering Blocks
        while rendering Pandoc
stack traceback:
```

**Comment by tarleb** [comment]
I went with `pandoc.make_writer` for now, but I'm still conflicted about this choice.

Other than that it should be good to go.

**Comment by jgm** [comment]
To me they look equally clean.  So if the module approach gives better error messages, I'd say that gives it an edge.

**Comment by tarleb** [comment]
I've renamed it to `pandoc.writer_scaffolding` to make the intend of this construct a little clearer. The error message is now

```
Error running Lua:
../testing/custom-writer.lua:19: intentional error
stack traceback:
        ../testing/custom-writer.lua:19: in function <../testing/custom-writer.lua:18>
        [C]: in function 'pandoc.writer_scaffolding.Inlines'
        ../testing/custom-writer.lua:10: in function <../testing/custom-writer.lua:8>
        [C]: in function 'pandoc.writer_scaffolding.Blocks'
        [C]: in function 'pandoc.writer_scaffolding.Pandoc'
        while rendering Inline `Str`
        while rendering Inlines
        while rendering Block `Header`
        while rendering Blocks
        while rendering Pandoc
stack traceback:
```

**Comment by tarleb** [comment]
I'm thinking about naming it just `pandoc.scaffolding`; not sure if we'd want to add a different type of scaffolding at some point.

**Comment by tarleb** [comment]
I went with `pandoc.scaffolding.Writer`, even though it's quite a mouthful.

The error message looks like this now:

```
Error running Lua:
../testing/custom-writer.lua:19: intentional error
stack traceback:
        ../testing/custom-writer.lua:19: in function 'pandoc.scaffolding.Writer.Inline.Str'
        [C]: in function 'pandoc.scaffolding.Writer.Inlines'
        ../testing/custom-writer.lua:10: in function 'pandoc.scaffolding.Writer.Block.Header'
        [C]: in function 'pandoc.scaffolding.Writer.Blocks'
        [C]: in function 'pandoc.scaffolding.Writer.Pandoc'
        while rendering Inline `Str`
        while rendering Inlines
        while rendering Block `Header`
        while rendering Blocks
        while rendering Pandoc
stack traceback:
```

**Comment by jgm** [comment]
OK!  Should these commits all be squashed into one, or did you want to arrange them in some other way?

**Comment by tarleb** [comment]
Just squashing is fine, the individual commits have no real relevance other than making it easier for me to experiment.

**Pull request merged**
