### PR TITLE
Lua: add new module `pandoc.zip`

### PR DESCRIPTION
**Pull request by tarleb**
Allows to handle docx and epub files.

### CODE REVIEW

**Comment by tarleb** [comment]
Todo:

- [ ] Documentation
- [ ] Better module interface

The main use-case that I see for this module is in custom writers, to modify docx and epub files that were generated with `pandoc.write`. However, the module is probably not that useful yet, as custom writers are `TextWriter`s, not `ByteStringWriter`s, so the modified archive cannot be the result of a `Writer` function.

**Comment by jgm** [comment]
What's the status of this?  Is it something we should aim to include in 3.0?
What is holding it up?

**Comment by tarleb** [comment]
I based it on the next HsLua version and haven't backported it yet. Should happen later this week.

**Comment by tarleb** [comment]
Good to go, I think.

Example use to write just the main body of a docx:

``` lua
local zip = require 'pandoc.zip'

function Writer (doc, opts)
  local docx = pandoc.write(doc, 'docx', opts)
  local archive = zip.Archive(docx)
  local document_entry = archive.entries:find_if(
    function (entry) return entry.path == 'word/document.xml' end
  )
  local body = document_entry:contents()
    :gsub('.*<w:body>(.*)<w:sectPr ?%/></w:body>.*', '%1')
  return body
end
```

**Pull request merged**
