### PR TITLE
Docx Writer: support for --toc option

### PR DESCRIPTION
**Pull request by lierdakil**
Creates a "dirty" TOC at the beginning of document, before abstract, as per #458

### CODE REVIEW

**Comment by lierdakil** [comment]
Failed on Travis side... let's try again.

**Comment by mpickering** [comment]
Does this use word's built in TOC feature?

**Comment by lierdakil** [comment]
Yes, it does. See discussion in #458 for implementation details and caveats, and https://groups.google.com/forum/#!topic/pandoc-discuss/ki-TlLGcgDM for @jgm's comment on the idea.

**Comment by jmuheim** [comment]
Am I missing something? I have `pandoc 1.13.2`, and while using the `--toc` option adds a TOC to a generated PDF, it doesn't do so for a Word file.

**Comment by lierdakil** [comment]
@jmuheim it's in `master`, a.k.a. 1.14. Not yet released.

**Comment by jmuheim** [comment]
Thank you!

**Comment by jgm** [comment]
This feature has been implemented in master and will be in the next
released version of pandoc.

+++ Joshua Muheim [May 05 15 09:06 ]:

**Pull request merged**
