### PR TITLE
Speed up Travis

### PR DESCRIPTION
**Pull request by ickc**
- travis use `fast_finish`
- cabal uses `-j`

I added the comments on fast_finish into the file directly for future reference. This will gives the most "speed up" since it will returns the "green light" when the 2 `allow_failure` builds aren't finished (useful for pull request when waiting for the green light).

The cabal `-j` means it will set parallel jobs according to the number of CPUs. It only speed ups when there're multiple dependencies that can be installed at the same time. I noticed that gitit's travis build uses `-j2` while it isn't used in pandoc. So may be there's a reason behind that?

### CODE REVIEW

**Comment by ickc** [comment]
Another possible "speed up" is to drop the cabal build with HEAD: I noticed that build almost always fails. It might just well be dropped to save travis' computer time (and to devote more thread to other builds by any of the projects under jgm).

**Comment by ickc** [comment]
Another possible drop: `stack nightly osx`, since `stack nightly` is already tested in Ubuntu. As far as testing "if it works for OS X" is concerned, the one `stack 8.0.1 osx` build already shows that.

As far as I know, Travis's OS X builds uses a completely different service, has 1 core only, and is not as reliable as the Ubuntu images. (more down time; and as seen in previous cases, "mysteriously" failed a build).

**Comment by jgm** [comment]
I'd be okay with dropping the osx nightly build, if you want to add that to this PR.
I'd prefer to keep the HEAD build for now.

**Comment by ickc** [comment]
I remove the stack nightly in osx build by commenting it, so it is easier to get it back in the future if needed.

**Comment by jgm** [comment]
OK let's see how much this helps!

**Pull request merged**
