### PR TITLE
Use crypton-connection instead of connection

### PR DESCRIPTION
**Pull request by felixonmars**
Follows the change introduced in tls 1.7.0. Fixes building.

Should be merged after https://github.com/snoyberg/http-client/pull/506

### CODE REVIEW

**Comment by jgm** [comment]
I want to wait for a release of http-client first on Hackage.

**Comment by felixonmars** [comment]
http-client-tls 0.3.6.2 has been released with the change.

**Comment by jgm** [comment]
Probably also need to explicitly set versions for tls, http-client, connection-crypton, and anything else that departs from the lts release we're targeting in stack.yaml.

**Comment by jgm** [comment]
Still one failing build.
```
       In the dependencies for pandoc-3.1.3(+embed_data_files):
           crypton-connection must match >=0.3.1, but the Stack configuration has no specified
                              version (latest matching version is 0.3.1)
```
Add this to stack.yaml?

**Comment by jgm** [comment]
I'll fix the stack build after merging.

**Pull request merged**
