### PR TITLE
Add appveyor artefacts for pandoc.exe

### PR DESCRIPTION
**Pull request by janschulz**
As discussed in https://github.com/jgm/pandoc/issues/2903#issuecomment-218214394

Example builds in https://ci.appveyor.com/project/JanSchulz/pandoc

### CODE REVIEW

**Comment by janschulz** [comment]
Oh my, that's the commit history you get when you have no idea about the language and the build tools and try them for the first time and only on the CI platform because your local build doesn't work...

**Comment by janschulz** [comment]
squashed it down to two commits... The build, tests and in the end the artifact works, but there is some red in the build logs...

**Comment by janschulz** [comment]
I think you have to log in at appveyor and enable the project there, too (or I didn't see a PR which was build after this :-)). First build takes almost an hour. second is much faster.

**Comment by jgm** [comment]
OK, great, it built!  I did get a strange error message, though (see attached image).  Do you understand why?  It still seems to have created the zip file.
screen shot 2016-05-12 at 11 21 05 am

**Comment by janschulz** [comment]
I've seen that too. Not sure what is causing this not how to fix it. I've seen appveyor examples where the stack command was used ot copy the result to a predefined dir and the 7z command can then take it from there.

E.g. this:

> --local-bin-path global option. Use to change where binaries get placed on a --copy-bins 

https://github.com/commercialhaskell/stack/blob/ff7a54e3d3b3c4f1a863377d068c65d383093ef9/ChangeLog.md

I'm trying that on https://github.com/janschulz/pandoc/ (master branch) -> https://ci.appveyor.com/project/JanSchulz/pandoc/build/1.0.28

**Comment by janschulz** [comment]
See #2919 for a PR

**Comment by jgm** [comment]
Sorry, made my last comment before seeing that your PR
addresses the build issue.

+++ Jan Schulz [May 12 16 16:28 ]:

**Pull request merged**
