### PR TITLE
Make multiple initial list levels work for docx

### PR DESCRIPTION
**Pull request by brisad**
Hi, is this an okay way to solve #5948 ?
I'm not sure how what the best way to test this would be. The existing docx tests seem to use golden copies, is that the way to go here too?

### CODE REVIEW

**Comment by lierdakil** [comment]
> The existing docx tests seem to use golden copies, is that the way to go here too?

Most certainly. How else would one check that the docx produced by pandoc matches the expected? Granted, not very flexible, but neither is docx.

The code looks fine (provided Word renders the document as expected), although I'd suggest using record syntax for matching `OrderedList`, i.e. use `OrderedList{}` instead of `OrderedList _ _`. That way even if the number of argument changes, the code will still work.

Also, why `OrderedList` specifically? Doesn't this also happen with `BulletList`? Pretty sure it does.

**Comment by brisad** [comment]
Sorry for the long delay. I have updated the PR with your suggestions and added tests. The resulting docx-file rendered fine in Word.

**Comment by brisad** [comment]
I realized this PR has been lying here for a while now. It is ready for review, how would I best notify someone that it can be looked at? Should I assign someone myself? I'm pinging you here now, but I'm asking for future contributions I hope to make :-) @lierdakil @jgm

**Review by tarleb — APPROVED** [review]
Looks good to me.

One could remove a tiny bit of repetition by defining

```haskell
let isListBlock = \case
      BulletList {}  -> True
      OrderedList {} -> True
      _              -> False
```

and using an `if ... then ... else ...` term instead of a `case`. I think that's a little cleaner, but it's a matter of taste.

**Comment by jgm** [comment]
@brisad - up to you whether you want to implement @tarleb's stylistic suggestion.
Let me know and I can merge.

**Comment by brisad** [comment]
@jgm I'll implement the suggestion. Thanks @tarleb!

**Comment by brisad** [comment]
I've updated the PR :)

**Comment by jgm** [comment]
Perfect, thank you!

**Pull request merged**
