### PR TITLE
Docx writer: keep raw openxml strings verbatim

### PR DESCRIPTION
**Pull request by tarleb**

### CODE REVIEW

**Comment by jjallaire** [comment]
I tried this out and it works exactly as expected. IMO this opens up a huge solution space for docx/pptx as you can now create arbitrarily sophisticated openxml structures and render markdown within them. Tables are certainly one example but you can imagine many others, especially within pptx.

**Comment by tarleb** [comment]
Great to hear, thanks for testing. The remaining cleanup should be done within the next days.

**Comment by tarleb** [comment]
Should be good now.

**Comment by jgm** [comment]
Excellent!

**Pull request merged**
