### PR TITLE
Lua: support format extensions in custom writers.

### PR DESCRIPTION
**Pull request by tarleb**
Custom writers can define the extensions that they support via the
global `writer_extensions`. The variable's value must be a table with
all supported extensions as keys, and their default status as values.

E.g., the below specifies that the writer support the extensions `smart`
and `sourcepos`, but only the `smart` extension is enabled by default:

    writer_extensions = {
      smart = true,
      sourcepos = false,
    }

### CODE REVIEW

**Comment by tarleb** [comment]
Here it is in action, based on the example in #8120:

``` lua
writer_extensions = {
  smart = true,
}

function Writer (doc, opts)
  local filter = {
    Math = function (elem)
      local raw_md = elem.mathtype == 'DisplayMath'
        and '\n$$' .. elem.text ..'$$\n\n'
        or '$$' .. elem.text ..'$$'
      return pandoc.RawInline('markdown', raw_md)
    end
  }
  local exts = pandoc.List{}
  local enabled_exts = pandoc.List(opts.extensions)
  for ext in pairs(writer_extensions) do
    local polarity = enabled_exts:includes(ext) and '+' or '-'
    exts:insert(polarity .. ext)
  end
  return pandoc.write(doc:walk(filter), 'markdown' .. table.concat(exts), opts)
end
```

It get's the job done, but feels rather clunky.

**Comment by tarleb** [comment]
Another downside: the following assert may fail:

``` lua
function Writer (_, opts)
  assert(pandoc.List(PANDOC_WRITER_OPTIONS.extensions) ==
         pandoc.List(opts.extensions))
  return ''
end
```

The value in `PANDOC_WRITER_OPTIONS.extensions` is computed in `getWriter`, *before* the Lua file is loaded, but `opts.extensions` is not know till *after* the file was loaded.

**Comment by jgm** [comment]
Let me know if this is ready.
Re the downside mentioned above:  should we deprecate the globals like PANDOC_WRITER_OPTIONS? They should not be necessary with new-style writers, right?

**Comment by tarleb** [comment]
Ready from my side.

The handling of `PANDOC_WRITER_OPTIONS` already changed in #8343 (support for bytestring writers). There docs mentioned the new behavior, but I've now added a deprecation note as well.

**Comment by jgm** [comment]
Excellent!

**Pull request merged**
