### PR TITLE
WIP: extensions in custom readers/writers

### PR DESCRIPTION
**Pull request by jgm**
For #8378

### CODE REVIEW

**Comment by jgm** [comment]
@tarleb how do we make the ExtensionsDiff available in the custom reader/writer?
Is this a matter of setting a global variable? If so, what should it be?  Is there already code for marshalling an ExtensionsDiff?

**Comment by tarleb** [comment]
I've been wondering about this, too. A few options:

1. `WriterOptions` could get a new field `writerFormat`, then `writerExtensions` in `WriterOptions` would become a function that calculates the value from the format. This would be quite clean, I think, but might be a little bothersome to work with in the non-custom writers.
2. We set `INPUT_FORMAT` and `OUTPUT_FORMAT` globals.
3. The format gets passed as a third parameter to the `Reader` and `Writer` functions..
4. We do 1., but only on the marshaled Lua object; the Haskell structure stays as it is.

My current order of preference is 1, 4, 3, 2.

**Comment by tarleb** [comment]
Marshal functions would be something like

``` haskell
pushExtDiff = pushAsTable
  [ ("enable", pushList pushExtension . extsToEnable)
  , ("disable", pushList pushExtensions . extsToDisable)
  ]
```

which would get a structure very close to what we have in Haskell.

Alternatively, we could build a table with extensions as keys and a boolean value to indicate whether it should be enabled or disabled.

``` haskell
pushExtDiff diff = pushKeyValuePairs $ (map (,True) (extsToEnable diff)) ++ map (,False) (extsToDisable diff)
```

**Comment by jgm** [comment]
We don't really need FORMAT; we just need ExtensionsDiff.
Why not make it available as a global, say,
```
EXTENSIONS = { 'foobar': true, 'smart': false }
```
where true and false indicate set/unset?  Or we could just use `'enabled'`/`'disabled'`, which might cause less confusion.

**Comment by tarleb** [comment]
Sounds good. Boolean keys would be easier to use, I think. We could also add a module `pandoc.Set` (or, more general, `pandoc.Map`) that makes it easier to work with Lua sets.

**Comment by jgm** [comment]
> Boolean keys would be easier to use, I think. 

My worry is that we need a threefold distinction:  enabled, disabled, not mentioned.  Boolean keys make sense with a twofold distinction, since `extensions.smart` will be treated as a false value whether `smart` is `false` or simply unspecified.  Of course, you can test for `== false` as opposed to `== nil` and get the distinction, but my worry is that this might be too subtle.

**Comment by jgm** [comment]
Alternatively we could have something like
```
extensions = {
  enabled = {
    smart: true 
  },
  disabled = {
    foo: true
  }
}
```

**Comment by jgm** [comment]
Another alternative would be to keep the original plan, in which the custom writer defines its own defaults for extension, returning ExtensionsConf.  If we did that, then the only change needed would be to add the ability to handle custom extensions (and maybe very little or nothing would be needed for that).

**Comment by tarleb** [comment]
I'm ok with both; users have to learn about another global either way. I agree that `Extensions` would be a better name.

> However, if we go this way, we should also have custom readers define their own extensions and return ExtensionsConf.

I think that's covered by 253d2e768a43c8ab3ad8e1c46b2bc4a02acec946.

I keep wondering if it could make sense to implement JSON filters as a scripting engine. That would then also add JSON readers and writers. Maybe that would help us to make design decisions.

**Comment by jgm** [comment]
> I keep wondering if it could make sense to implement JSON filters as a scripting engine. That would then also add JSON readers and writers. Maybe that would help us to make design decisions.

Interesting idea.  What sorts of design constraints would this impose, do you think?

**Comment by tarleb** [comment]
Not really sure, but I assume that passing data to the readers/writers is easier than retrieving config data from the writers. It would be interesting to see how easy or difficult it would be to support custom default templates: e.g., would pandoc call the writer twice, once for the template and once for the conversion, or would it try to communicate via a pipe, or would we rather define a default location where the template would be expected. Likewise for readers and extensions. There would also be the challenge of making the mediabag content available to the writer and to retrieve it from the reader, but that's orthogonal to what we're discussing here. 

I believe that we already arrived at a good abstraction, and that the small changes that we are discussing would not change the implementation in any significant way. The idea may therefore be more trouble than it's worth. It might increase the usefulness of panflute and the like, but not sure.

**Comment by jgm** [comment]
I changed the names to `Extensions`.

**Comment by jgm** [comment]
Our present abstraction:
```hs
  , engineWriteCustom :: forall m. (PandocMonad m, MonadIO m)
                      => FilePath
                      -> m (Writer m, ExtensionsConfig, m (Template Text))
```
One thing I wonder about here: for the template, we return an action that will fetch the template if run.  For the ExtensionsConfig, we just return the ExtensionsConfig directly.  Why the difference?

**Comment by tarleb** [comment]
With the current implementation, the ExtensionsConfig is always required, while the Template is retrieved on demand. Not sure if this is a good reason though.

**Pull request closed without merging**
