### PR TITLE
Add jira reader

### PR DESCRIPTION
**Pull request by tarleb**
Closes: #5556

### CODE REVIEW

**Comment by tarleb** [comment]
It's not perfect yet, as some corner-cases are handled incorrectly, but I believe it to be usable.

**Comment by tarleb** [comment]
Missing:

- Block quotes
- HTML-entities

**Comment by tarleb** [comment]
Found more issues, closing till those are fixed.

**Comment by jgm** [comment]
Is this ready to go?

**Comment by tarleb** [comment]
This gives good results when parsing `test/writer.jira`, so I'm confident that it's ready.

**Comment by jgm** [comment]
Would it be worth adding some "old-style" tests like we have for the other readers?
`jira-reader.jira` -> `jira-reader.native` -- perhaps just using `writer.jira`, and carefully checking the output?  This gives more complete test coverage than the unit tests.

**Comment by tarleb** [comment]
True, I'll do that. I assume this won't be part of 2.8, so we could also wait till the printer part of jira-wiki-markup is done. This will allow me to do roundtrip tests, which should uncover problems and inconsistencies.

**Comment by jgm** [comment]
OK, I'll wait til after 2.8 then.

**Comment by tarleb** [comment]
Should be good now.

**Comment by jgm** [comment]
Great, merged!

**Pull request merged**
