### PR TITLE
Move Input/Output operations to module T.P.IO

### PR DESCRIPTION
**Pull request by tarleb**

### CODE REVIEW

**Comment by tarleb** [comment]
My intent is to make this accessible to Lua scripts. It should be noted that functions and structures are not ideal yet.

**Comment by jgm** [comment]
Did you plan to make further changes, or should I review this for merge?

**Comment by tarleb** [comment]
I intend to make more changes, but wanted to outline the bigger changes first. I'd prefer not to merge this yet, unless other work on App makes conflicts more likely (e.g., #5045).

**Comment by jgm** [comment]
Albert Krewinkel <notifications@github.com> writes:

> I intend to make more changes, but wanted to outline the bigger changes first. I'd prefer not to merge this yet, unless other work on App makes conflicts more likely (e.g., #5045).

That's fine, just let me know when you're ready.
I have no urgent need to work on App.

**Comment by tarleb** [comment]
Closing, I've grown increasingly dissatisfied with the approach. An Text.Pandoc.IO module still seems like an ok idea, but the implementation is too ad-hoc. I'm trying to clean up other parts of App first and might revisit this later.

**Pull request closed without merging**
