### PR TITLE
Derive from Data and Typeable for libpandoc

### PR DESCRIPTION
**Pull request by ShabbyX**
See https://github.com/jgm/highlighting-kate/pull/64

### CODE REVIEW

**Comment by ShabbyX** [comment]
Thanks! This was quick!

**Comment by jgm** [comment]
Easy fix.  By the way, in the old libpandoc repo
https://github.com/t0yv0/libpandoc
I note that libpandoc.cabal says the license is BSD3.
This is, at the very least, highly misleading.  Pandoc is GPL,
and anything that links with it needs to be GPL too.  Someone
might look at libpandoc, see it's BSD3, and not realize this.
Can this be fixed?

**Comment by ShabbyX** [comment]
@jgm, a GPL library can be linked with any GPL-compatible library/application. If I understand correctly, BSD3 means _Modified BSD License_ otherwise known as _3-clause BSD license_, which according to [Wikipedia](https://en.wikipedia.org/wiki/BSD_licenses) is compatible with GPL.

Since I am not the copyright holder (that would be t0yv0) and my edits haven't been very extensive either, I don't think I have the rights to relicense the library. If it's legal issues you are worried about, there are none because the licenses are compatible.

If you just want people to know that Pandoc itself is licensed under GPL, I can make it clear in the README.

**Comment by jgm** [comment]
I think @t0yv0 should relicense it.  I think it's legal for him to license his own code BSD3, but, as I said, it's incredibly misleading for others if the pandoc binding (which is only useful when linked with pandoc) is BSD3 licensed.  People who do not check the license of pandoc itself may think they're only linking with BSD3 licensed libraries, when in fact they aren't.  At the very least, there should be a very visible statement on the README, in the cabal file, and in the C header file that any library that links with libpandoc must comply with the terms of pandoc's license, the GPL.  But it would avoid much confusion simply to license the library as GPL.

+++ Shahbaz Youssefi [Mar 19 15 09:41 ]:

**Comment by ShabbyX** [comment]
I will try to get a hold of him, but given his unresponsiveness regarding the PR on libpandoc itself, I wouldn't count on any response from him.

In the meantime, I would add the license information on the source files (in the README I already have). In the cabal file, I'm not sure how one can indicate that (Put under `Description:` maybe?).

**Comment by ShabbyX** [comment]
@jgm t0yv0 was nice enough to transfer copyright of libpandoc to me. I relicensed it to GPLv2+ to clear the confusion.

**Comment by jgm** [comment]
Great!

+++ Shahbaz Youssefi [Mar 21 15 10:56 ]:

**Pull request merged**
