### PR TITLE
ConTeXt writer: support complex table structures.

### PR DESCRIPTION
**Pull request by tarleb**
The following table feature are now supported in ConTeXt:

- Colspans,
- rowspans,
- multiple bodies,
- row headers,
- multi-row table head and foot.

### CODE REVIEW

**Comment by tarleb** [comment]
@denismaier it'd be great if you could have a look when time permits.

**Comment by tarleb** [comment]
Missing: 

- [ ] column widths,
- [ ] table widths, and
- [ ] table references.

**Comment by tarleb** [comment]
Implementation details:

-  I also switched to a modern syntax for Natural Tables.
- With xtables, the last row in each body part is now marked as `lastrow`, so it can be styled with `\setupxtable[lastrow][...]`. This is helpful when handling border settings.

**Comment by jgm** [comment]
@denismaier if you're able to look next week, we can always make adjustments.

**Comment by denismaier** [comment]
I've had a quick look. I usually don't really use extreme tables, but from AFAICS this looks reasonable.

**Pull request merged**
