### PR TITLE
Docx reader styles

### PR DESCRIPTION
**Pull request by lierdakil**
This is a quick stab at resolving #5523, #5052, #5074 and probably others. This more or less follows the option (1) outlined in https://github.com/jgm/pandoc/issues/5523#issuecomment-528813371

Seems to work fine, and it's not as much work as I initially feared.

I might have missed some corner case or another, so it's probably better if someone with a good understanding of the reader code will review this.

One important change is related to #5074, which is reflected in the tests, is that Docx Reader now outputs style _display name_ in as the "custom style". This should be generally more consistent with the Writer code, but I did not verify this thoroughly (the question is, does Writer expect the style name consistently, or does it use styleId in some cases)

I might have made more changes to the Docx Reader architecture than strictly necessary, for instance, I changed `ParStyle` and `CharStyle` to be records instead of synonyms for 2-tuples. I find this makes the code a little cleaner, but YMMV. I have also removed strictly duplicate fields from the `ParagraphStyle`, and made it carry complete information about associated styles instead of only the `styleId`s. Let me know if you disagree with any of those, so that we can discuss this further.

Some things that still might need to be done:

- [x] Perhaps block quote detection code should be moved from parser to reader, and the code detecting those based on `styleId` can be removed.
- [x] ~~The same applies to heading level detection.~~ Parser needs this information in one place, no reason to duplicate the code. The code detecting header styles based on `styleId` has been removed in d490df4
- [x] Documentation might need updating, wrt. #5074 
-  ~~I'm not entirely clear on the use of `List Paragraph` style (mostly used in `Readers.Docx.Lists`). At the first glance, it seems like a bit of a hack. This code could perhaps use a bit of a revision.~~ Won't be doing that here. Changing this requires sizable changes to the code, so it's going to be a separate PR if I ever get to it anyway.
- [x] Styles missing the `w:name` property are currently handled very, ahem, ungracefully. Technically, one could argue that styles missing `w:name` aren't proper OOXML, but it's probably not a good idea to fail on those altogether. On the other hand, returning "Missing style name" as the style name is not a good idea either. The choice is between two options, either (a) styles missing `w:name` will be ignored, or (b) styles missing `w:name` will get assigned a name matching their `w:styleId`. Let me know what is preferable, I should be able to implement either rather quickly. UPD: Since there was no input, I've gone with (b) in https://github.com/jgm/pandoc/pull/5732/commits/892c5b61f0e963f5b00b46ab46c021b1cbb9ae0a as probably the more robust option. It can potentially lead to unintuitive behaviours on malformed docx files though.
- [x] Remove obsolete (?) `list-item` style from `divsToKeep`?
- [x] ~~Remove obsolete (?) `Block Quotation` style from `isBlockQuote`?~~ Going to leave this in. Not much overhead, and removing it can potentially break some workflows.
- [x] Filter `Compact` style from output?
- [x] ~~Fix `Definition`/`Definition Term` classes bleeding to output in compact definition lists? (auto-fixed if `Compact` is filtered from output at a certain point)~~ This is a much more involved thing that I thought initially, so that will go as a separate pull request

Hopefully this proves useful in some way.

#### Docx Reader
1. Reader now consistently uses docx style names instead of ids for recovering semantic information. Practically, this means that built-in Word styles should be recognized regardless of Word locale.
2. With `docx+styles` output, `custom-style` will contain the docx style display name instead of id. For Word built-in styles, this means consistent style names regardless of Word locale. For custom styles, this means the `custom-style` content will be identical to style's name displayed in Word interface.
3. `Verbatim Char`, `Source Code` and various block quote styles (notably, `Block Text`) now honour inheritance. That is, if you create a custom docx character/paragraph style inherited from respectively `Verbatim Char` or `Source Code` (defined in `reference.docx`), characters/paragraphs using that custom style will be respectively recognized as inline code or code block by pandoc.
4. Reader now honours `Compact` style (defined in `reference.docx`). Any paragraphs having the `Compact` paragraph style, or any custom style inherited from `Compact` will be interpreted as `Plain` instead of `Para` by pandoc. This is mostly relevant for tight lists. A side effect of this is that `Compact` style will _not_ show up in `docx+styles` output. Notice that styles _inherited_ from `Compact` _will_ show up in `docx+styles` output.
5. Custom header styles will gain a class matching the style display name (previously, internal docx style identifier). One caveat is that pandoc classes, unlike docx style display names, can't have spaces in them, so spaces are replaced with dashes (`-`).

#### Docx Writer
1. Writer now consistently uses docx style names instead of ids. In particular, this means that any custom styles used by the writer will be detected by their name as seen in Word, not the internal id. Styles that this change affects: paragraph styles: `Author`, `Abstract`, `Compact`, `Figure`, `Captioned Figure`, `Image Caption`, `First Paragraph`, `Source Code`, `Table Caption`, `Definition`, `Definition Term`; character styles: `Verbatim Char`, token styles (those with names ending in `Tok`)

### CODE REVIEW

**Comment by jgm** [comment]
Great!  @jkr it would be nice to have your thoughts on this.

**Comment by jkr** [comment]
Looks good to me -- this has always been the area that I was the most unsure of, and that was built by other folks the most in the past. Everything certainly scans.

@lierdakil : The `ListParagraph` style is indeed a hack, as the whole list-processing step is. It all comes from the weirdness of ooxml's non-nesting lists, where each item and sub-paragraph of an item is its own `<w:p>`. To keep things confined, I repeated the docx structure in the docx type, and parsed it in `T.P.R.Docx`, which requires handing stuff off to the list module. This was the way to overload the information channels we had available (since it was already being translated into Pandoc-native) to communicate that "this is a further paragraph within the same item."

Frankly, the whole list-processing module, which only processes this stuff as a second pass at the end of conversion,is an ugly hack. I've abandoned a couple of more elegant approaches because I couldn't iron out all the issues.

**Comment by jkr** [comment]
See the `bodyToOutput` function, which runs `blocksToBullets` and `blocksToDefinitions` after all the other work is done.

**Comment by lierdakil** [comment]
@jkr, what is the purpose of `"list-item"` in `divsToKeep`? As far as I can tell, `divsToKeep` is only ever compared against `w:styleId` (in `master` branch that is), and I don't think there is such a style? More than that, I don't think Word allows dash `-` in `styleId` in the first place.

**Comment by lierdakil** [comment]
For context, this is what I'm referring to:
https://github.com/jgm/pandoc/blob/f0577fe3609e81f653570e3e8e164be1d3ddbcef/src/Text/Pandoc/Readers/Docx.hs#L138-L139

And here's where it's used:
https://github.com/jgm/pandoc/blob/f0577fe3609e81f653570e3e8e164be1d3ddbcef/src/Text/Pandoc/Readers/Docx.hs#L528-L535

**Comment by lierdakil** [comment]
Also, while at it, not entirely sure on `Block Quotation` style name. I've managed to track the original `BlockQuotation` thingy back to https://github.com/jgm/pandoc/pull/1529 and subsequently [this mailing list thread](https://groups.google.com/forum/#!searchin/pandoc-discuss/before$3A2014$2F08$2F13$20docx|sort:date/pandoc-discuss/3d9e0gtg4Nk/_xDrNCREJSgJ). The original message was, regrettably, deleted since then, so I can't check what's in there exactly, but the following quote makes me think that it was originally a user-defined style (it's a quote of a quote, yes; emphasis mine):

> > \- 191–205, 568–70, 576–79: A block quotation is not picked up, but
 *that’s my fault for using a non-standard style name*. I only bring it
 up because it seems odd that the one block quotation that was picked
 up was the one that didn’t use ***my** ‘Block Quotation’ style.*

**Comment by lierdakil** [comment]
@jgm, I've made a small change in 7da6a21 to honor `Compact` style, which signals that a given paragraph was originally a `Plain` in pandoc-generated Docx. But now we have a bit of a snag: with  `+styles`, this style is passed through; this, however, is not the case with other "semantic" styles: like headings, block quotes, definition lists, etc. Should we perhaps remove the `Compact` style from the output as well?

As a side note, I've found a curious bug: `Definition` and `DefinitionTerm` classes don't get stripped from compact definition lists. I'll try to figure out what happens and fix it here as well.

**Comment by jgm** [comment]
>  But now we have a bit of a snag: with +styles, this style is passed through; this, however, is not the case with other "semantic" styles: like headings, block quotes, definition lists, etc. Should we perhaps remove the Compact style from the output as well?

@lierdakil I'm not sure I follow, can you explain a bit more?

**Comment by lierdakil** [comment]
@jgm, well, the issue's easy to demonstrate. Run:
`echo "1. One" | pandoc -t docx -o- | pandoc -f docx+styles -t markdown`
You will get
```markdown
1.  ::: {custom-style="Compact"}
    One
    :::
```
As you can see, the list of one item is treated like a tight list, hence docx writer adds `Compact` style to list items. Docx writer then sees it and interprets it as a "custom style".

Also of note, if you run `echo "1. One" | pandoc -t docx -o- | pandoc -f docx+styles -t native` on pandoc 2.7 (or master), you'll see
```markdown
[OrderedList (1,Decimal,Period)
 [[Div ("",[],[("custom-style","Compact")])
   [Para [Str "One"]]]]]
```
Notice how the list item is in `Para` instead of `Plain`. This behaviour is actually changed by https://github.com/jgm/pandoc/pull/5732/commits/7da6a214b7ce642ea85796ef67336b9b24f02098 (currently the last commit on this PR). `Compact` is still passed through, so with https://github.com/jgm/pandoc/pull/5732/commits/7da6a214b7ce642ea85796ef67336b9b24f02098 the output would be
```markdown
[OrderedList (1,Decimal,Period)
 [[Div ("",[],[("custom-style","Compact")])
   [Plain [Str "One"]]]]]
```

The question is, should we also remove the `custom-style=Compact` div from the output in this case? I'm leaning to "yes", after all `Definition`, `Definition Term` and `Source Code` styles that also serve as semantic markers _are_ removed from `docx+styles` output. But I thought I might as well ask.

**Comment by agusmba** [comment]
Thank you for all the work on this! It looks great!

As long as you're discussing also lists, might I ask if https://github.com/jgm/pandoc/issues/4321 is relevant here? or is it a completely different beast best left undisturbed?

**Comment by jkr** [comment]
@lierdakil not sure if you already go past this point, but the `list-paragraph` class was to pass along the fact that this particular paragraph came out of a paragraph (`<w:p>`) with list info (which is translated in the parser into a `ListItem`, which is essentially a paragraph with the necessary list info pulled from the numbering xml file). In other words, this is again temporarily holding onto info, *in pandoc format*, for the list parser, since that comes at the end, and works on pandoc format. It doesn't make it out of this temporary usage into the output.

Why use lowercase and a `Div` while the paragraph uses camelcase and a `pPr`? Seems lost to time

**Comment by jgm** [comment]
We shouldn't omit a div with custom-style="Compact".  Compact is used to distinguish between Para and Plain, if I recall.  The reader should presumably do some kind of Para -> Plain transformation and not render the Compact style as a custom style, right?

**Comment by lierdakil** [comment]
@jkr, you've missed the point of the question. I wasn't asking what's the purpose of `list-item`. I was asking why is `list-item` in `divsToKeep`? That's a list of style names. Those values are compared against Word style names/ids. `list-item` doesn't seem like it's can ever appear in a Word document.

@jgm, I'm not sure if I failed to communicate on some level, but could you please carefully re-read my previous comment, including the last few paragraphs? Because it feels like you didn't really read it. Perhaps that's because I've used misleading phrasing? By "remove div" I meant "drop the div, but leave its contents", as in
```haskell
stripCompactDiv :: Block -> Block
stripCompactDiv (Div ("", [], [("custom-style", "Compact")]) content) = content
stripCompactDiv x = x
```
(not actual code, just something to help communicate my point)

@agusmba, #4321 would be related to the Writer. I'm primarily concerned with the Reader here.

**Comment by jgm** [comment]
Sorry @lierdakil - somehow my fingers wrote something different from what I meant to say.
I meant to say "we *should* omit a div," not *shouldn't*.  I meant to be agreeing with you: we should use something like the `stripCompactDiv` as you suggest.

**Comment by jkr** [comment]
@lierdakil because div (style) names get dropped at the `parStyleToTransform` step, which is in `bodyPartToBlocks`, while that needs to survive until `blocksToDefinitions/Bullets`, which comes later:

~~~haskell
bodyToOutput :: PandocMonad m => Body -> DocxContext m (Meta, [Block])
bodyToOutput (Body bps) = do
  let (metabps, blkbps) = sepBodyParts bps
  meta <- bodyPartsToMeta metabps
  blks <- smushBlocks <$> mapM bodyPartToBlocks blkbps
  blks' <- rewriteLinks $ blocksToDefinitions $ blocksToBullets $ toList blks
  blks'' <- removeOrphanAnchors blks'
  return (meta, blks'')
~~~

**Comment by jkr** [comment]
So it does get dropped, but in the list module.

**Comment by lierdakil** [comment]
@jkr. Okay. Let's try this one more time, I feel like I'm failing to communicate my point here. 

`divsToKeep`'s name is a bit misleading. _At no point in time an actual `Div` is compared against `divsToKeep`._ More accurately, this should perhaps be named `paragraphStylesToKeep`. When a paragraph style is in that list, a `Div ("", [styleName], [])` gets created at some step of output transformation (`parStyleToTransform` does this actually). That's currently the _only_ purpose `divsToKeep` serves. Still with me? Cool. Now the issue is, at no point there is a paragraph style named `"list-item"`. The `Div ("", ["list-item"], kvs)` is created in `bodyPartToBlocks`, sure. But that is not predicated on any style names in the source docx, and that `Div` will never be compared against `divsToKeep`, since `divsToKeep` is only ever compared against paragraph style names _that are present in the original docx_. Does that make sense? So, based on this, it would seem to me that `"list-item"` in `divsToKeep` is completely extraneous and should probably be removed to avoid further confusion.

So the question is, am I being an idiot and missing something really obvious, or is this `"list-item"` an artefact from some old version of the Reader code? FWIW, removing it from `divsToKeep` does not affect tests at all (that said, some docx reader tests seem a wee bit outdated themselves). I'm asking because the code is a wee bit too complicated to run it in my head entirely, so I can't be 100% sure I'm not missing some arcane piece of code that does something underhanded somewhere (and that is not covered by tests)

For reference, here's where `Div ("", ["list-item"], kvs)` is created:
https://github.com/jgm/pandoc/blob/f0577fe3609e81f653570e3e8e164be1d3ddbcef/src/Text/Pandoc/Readers/Docx.hs#L642-L659
`parStyleToTransform` is not (can not) be applied to that for obvious technical reason, types don't match: `parStyleToTransform` accepts `ParagraphStyle` as argument, while `bodyPartToBlocks` returns `Blocks`.
https://github.com/jgm/pandoc/blob/f0577fe3609e81f653570e3e8e164be1d3ddbcef/src/Text/Pandoc/Readers/Docx.hs#L528
https://github.com/jgm/pandoc/blob/f0577fe3609e81f653570e3e8e164be1d3ddbcef/src/Text/Pandoc/Readers/Docx.hs#L574

**Comment by jgm** [comment]
@lierdakil is this ready to merge now?

**Comment by lierdakil** [comment]
@jgm, I'm going to go over the code once more, then it'll be good to go I think.

**Comment by lierdakil** [comment]
Okay, I'm done with this one for the time being. Feel free to review/merge/etc whenever. Another PR or a couple related to this will be inbound at some point after this is merged.

I've added the primary changes which happened in this PR to the opening post.

I might've got carried away slightly with refactoring, sorry about that. All non-trivial changes are useful in one way or another, but the diff ended up being rather noisy.

The build failure is not my fault, apparently something broke in `statistics-0.15.1.0`

**Comment by jgm** [comment]
This looks good to me!  @jkr , @mb21 do you agree this is okay to merge?

One question is whether these separate commits should be squashed, or is there value in keeping them separate in the history?  It would be good to have the motivating issues listed in the commit messages, if they aren't already, and it seems to me that at least some squashing would be a good idea.

**Comment by lierdakil** [comment]
@jgm I tried to clean up the commit history as far as possible. Hopefully that's good enough.

**Comment by mb21** [comment]
@jgm Unfortunately, I don't know the docx reader that well...

**Comment by conklech** [comment]
I've confirmed that this branch resolves #5074; in particular, I can now successfully round-trip docx files that contain source text in styles with spaces in the name, using the original docx as the reference-doc. (In reality I am doing intermediary processing; docx->docx roundtripping is not a crazy use-case.) Furthermore, pandoc no longer creates duplicate styles in the output document's styles.xml, which was likely caused by the inconsistent styleId/styleName treatment.

Thanks very much—I was just about to undertake this same project myself.

**Comment by jgm** [comment]
I've merged these commits manually (some conflicts had to be resolved), so closing this PR!
Thank you, this seems like a big improvement.

**Comment by jgm** [comment]
It would be helpful if someone could check the motivating issues, to make sure the issues are resolved, and if so close them.

**Pull request closed without merging**
