### PR TITLE
implemented #3663

### PR DESCRIPTION
**Pull request by Drezil**
#3663 sounded reasonable for me so i just implemented it because it was mostly search/replace in the UTF8-Module.

Sadly Mac (cr) is not in System.IO in GHC. Otherwise it should be caught in https://github.com/jgm/pandoc/compare/master...Drezil:issue3663?expand=1#diff-5da4b57212f9458ea23f6f27f62bfd87R971

Also: Errors and other things now get rendered with `\r\n` under windows (due to the usage of `nativeNewline` in those calls) and so the console-output should look better there.

### CODE REVIEW

**Comment by jgm** [comment]
How are templates dealt with?  If your templates are stored with LF line breaks, and you select CRLF line breaks for output, do you get a mix of different line break styles, or does everything go CRLF?

**Comment by jgm** [comment]
I answered my own question.

Thanks for this!  I've made a few changes and I'll push this shortly.

Changes:

- instead of changing types of functions exported from Text.Pandoc.UTF8, I now export new functions parameterized on Newline, leaving the old ones as they are. This minimizes API change disruption.

- Added to manual.

- Fixed help text for --eol option.

**Comment by jgm** [comment]
Closing this, as I've now merged a rebased and slightly revised version.

**Comment by tajmone** [comment]
Thanks for implementing this feature @Drezil !

I saw it with some delay because my Internet connection didn't work for a few days.

**Pull request closed without merging**
