### PR TITLE
Default latex template: patch for fixing spacing problem on CJK language.

### PR DESCRIPTION
**Pull request by jeongminkim-islab**
Issue and solution is from below.
https://tex.stackexchange.com/questions/17292/how-to-write-spaces-between-korean-words-with-xecjk

### CODE REVIEW

**Comment by jgm** [comment]
Thanks. I'd like to get feedback from other CJK users about this proposed change in the default.
Could you post something on pandoc-discuss?
I'm curious why it's the default to ignore spaces.

**Comment by jgm** [comment]
well, nobody has objected, so I'm merging it!  Thanks.

**Comment by annProg** [comment]
This may be problem when documentclass already load xeCJK with no option.  
```
! LaTeX Error: Option clash for package xeCJK.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.19     \setCJKmainfont
                        [BoldFont=Source Han Serif SC Heavy,ItalicFont=Fando...

? H
The package xeCJK has already been loaded with options:
  []
There has now been an attempt to load it with options
  [space]
Adding the global options:
  ,space
to your \documentclass declaration may fix this.
Try typing  <return>  to proceed.
```

May use `\xeCJKsetup { CJKspace = true }` to do this. Code from `ctex-engine-xetex.def`

```
\keys_define:nn { ctex }
  {
    space .choice: ,
    space / true  .code:n =
      { \xeCJKsetup { CJKspace = true } } ,
    space / auto  .code:n =
      { \xeCJKsetup { CJKspace = false } } ,
    space / false .code:n =
      { \xeCJKsetup { CJKspace = false } } ,
    space .default:n = { true } ,
    space .initial:n = { auto }
  }
```

**Comment by jgm** [comment]
@annProg thanks for this; could you create a new issue so we don't lose track?
You can link back here.

**Pull request merged**
