### PR TITLE
[latex] forced linebreaks for fenced code using

### PR DESCRIPTION
**Pull request by jannick0**
Per suggestion in #4302. The patch makes sure that long lines of fenced code are broken (LaTeX). The solution requires the additional package [fvextra](https://ctan.org/pkg/fvextra) which nicely collaborates with `fancyvrb`.

@jgm I hope this is the correct place to make these innocent edits. I am not sure if additional commits are needed in the documentation area.

### CODE REVIEW

**Comment by jgm** [comment]
I'm a bit reluctant to depend on a semi-obscure package like fvextra.
Maybe we could load it if it's available, and only apply this command in that case?
Then people would get the breaking behavior if they have fvextra available, otherwise not.
Or we could put the whole thing under a variable, so people could select `break-code-lines`.

**Comment by jannick0** [comment]
I am not sure what you mean by 'semi-obscure', while the package `fvextra` with precious features is available at ctan and is downloadable for everyone like `verbatim` and `fancyvrb`. Anyways, a flag like `break-code-lines` would be just fine.

Another possible workaround until feature implementation: Insert this header snip (via `--include-in-header`)
```tex
\usepackage{fvextra}
\RecustomVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
```
Thanks.

**Comment by jgm** [comment]
+++ jannick0 [Jan 28 18 19:58 ]:
>   I am not sure what you mean by 'semi-obscure', while the package
>   fvextra with precious features is available at ctan and is downloadable
>   for everyone like verbatim and fancyvrb. Anyways, a flag like
>   break-code-lines would be just fine.

For e.g. debian users, it can be inconvenient if pandoc uses
a package that isn't in texlive-latex-recommended, because
then you may need to install texlive-latex-extra just for
this...

Not a huge issue, perhaps, but I've tried to restrict to
commonly used packages.

**Comment by jannick0** [comment]
Understood. Then a switch for the user's choice and taste looks doable which would not force her / him to apply the package.

**Pull request closed without merging**
