### PR TITLE
pptx: Support footer content defined in the reference doc

### PR DESCRIPTION
**Pull request by undergroundquizscene**
In PowerPoint, you can define footer content (a date, either fixed or automatically updating, arbitrary text content, and the slide number, optionally starting from a specific value) in the master, which is then duplicated across all slides (though can optionally be left off the title slide).

This PR adds support for that footer content: if a footer is specified in the master, it will be reproduced across all slides (except the title slide, if that option is disabled).

### CODE REVIEW

**Comment by undergroundquizscene** [comment]
This PR is WIP for now, as I still need to add tests and documentation.

I also have a question: if the user's reference doc contains a date footer, but they've also specified a date in the YAML metadata block, what should we do? At the moment, this code ignores the YAML date, and includes only the date from the reference doc.

As I see it, there are a couple of other options:

- Use the YAML block date only on the automatically-generated title slide (possibly only if the reference doc footer content says not to display it on the title slide)
- Ignore the date in the reference doc footer, if there's a date in the YAML block
- Ignore only a fixed date in the reference doc footer, if there's a date in the YAML block
  - The other kind of date is an automatic one: one which PowerPoint updates to today's date any time you open the file

**Comment by jgm** [comment]
Not sure about the date issue -- what do you think?  I guess a fixed date in a reference doc wouldn't really be useful.  So I'm happy to have that replaced by metadata date.  But if it's an automatic date, I'm not sure.

**Comment by undergroundquizscene** [comment]
I think we should replace fixed dates in the footer with the date from the YAML block, but leave automatic dates as they are. If the user wants the fixed date from the reference, they can always remove the date from the YAML block, or set it to the same value as the reference doc. On the other hand, automatically updating dates is a feature that isn't available via the markdown source, so I'd rather keep it available via the reference doc.

I'll make that change today but keep it in a separate commit pending any further discussion.

**Comment by undergroundquizscene** [comment]
This PR is pretty much ready to go – there are just two outstanding issues. First, there's a lint failure caused by some other code (so I believe once that's fixed the checks here will all pass), and I'd like to squash the two commits into one if we're happy with the metadata date replacing a fixed date from the reference doc.

**Comment by jgm** [comment]
I fixed the linter issue.

**Comment by undergroundquizscene** [comment]
Thanks, I'll rebase

**Comment by undergroundquizscene** [comment]
This PR fixes https://github.com/jgm/pandoc/issues/5660

**Pull request merged**
