### PR TITLE
Add a GitHub Pull Request template

### PR DESCRIPTION
**Pull request by ickc**
- [Setting guidelines for repository contributors - User Documentation](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
  - move CONTRIBUTING.md to `.github/` to declutter the root directory
  - replace `--` by unicode em-dash `—` (explained in the commit itself)
- [Creating an issue template for your repository - User Documentation](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)
  - excerpt from CONTRIBUTING.md
  - As someone who has abused the issue tracker in the past (and sometimes still do), putting the message right at the place people is typing should be most effective.
- [Creating a pull request template for your repository - User Documentation](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)
  - excerpt from CONTRIBUTING.md
  - As someone who has violated rule no. 1 before (Each patch (commit) should make a single logical change. Not sure how to interpret though. e.g. In this pull request I tried to make a commit for each logical step), putting the message right at the place people is typing should be most effective.

You can see how the issue template and pull request template work in [Demo: ickc/test-dot-github](https://github.com/ickc/test-dot-github):
- try creating an issue
- make a pull request from `pull-request` to `master`

### CODE REVIEW

**Comment by ickc** [comment]
Thinking about putting CONTRIBUTING.md to .github/, there might be a consideration that if in root, it will be easier to discover (before one click into issue/pull request). But, since the README has hyperlinked into it, I think it shouldn't be a big problem. Personally I think a cleaner root is more important. But if that is a problem, I can revert the changes about CONTRIBUTING.md.

**Comment by tarleb** [comment]
Good visibility of `CONTRIBUTING.md` should not be limited to github, its usefulness is not bound to this plattform.

I like the idea oft using templates. Shortening them a bit could increase their usefulness. Otherwise people might just go "TL;DR lol" and post anyway.

Is there a way to let people select the type of issue they want to submit (e.g. bug report, feature request)? Having one template to address all use-cases might prove to be difficult.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Nov 02 16 04:59 ]:
>   Good visibility of CONTRIBUTING.md should not be limited to github, its
>   usefulness is not bound to this plattform.

Agreed, it should live in the root.

>   I like the idea oft using templates. Shortening them a bit could
>   increase their usefulness. Otherwise people might just go "TL;DR lol"
>   and post anyway.
>
>   Is there a way to let people select the type of issue they want to
>   submit (e.g. bug report, feature request)? Having one template to
>   address all use-cases might prove to be difficult.

Yes, that's just my hesitation with this PR.

the problem is that there's no way to select between
different templates for bug reports and enhancement
requests, and what is required for these is completely
different.  Google Code's issue tracker was far better
in this way and many others.

On the other hand, I can't count the number of times
I've had to ask people to say what version of pandoc they're
using in issue reports.

**Comment by ickc** [comment]
I also think that putting the CONTRIBUTING.md in the hidden folder is a stupid idea the day *after* I did that. I reverted it.

I think `ISSUE_TEMPLATE.md` is short enough to be useful. So you can see the 4 checklist items are required. For `PULL_REQUEST_TEMPLATE.md` however, I'm not so sure, so I hided the checklist in HTML comment, and let the one creating the pull request to decide what to do with the checklist.

And unfortunately, this is as much as can be done in GitHub. The non-admin cannot choose labels on the issue/pull request they are making. The only way to classify is the beginning of the title. Sometimes I see some repositories requires people to start their title with "FEATURE REQUEST", "BUG REPORT", etc.

If there's any features that we want from GitHub, "[dear-github/dear-github: An open letter to GitHub from the maintainers of open source projects](https://github.com/dear-github/dear-github)" seems to be the place to voice our opinion. It seems that at least some of the features we are using now originated from there (e.g. emoji reaction?).

**Comment by tarleb** [comment]
A template containing just a simple "If you are reporting a bug, please include the output of running `pandoc -v`" might still safe a lot of time and nerves of everyone involved.  Reopen?

**Comment by ickc** [comment]
I'm working on it. I hard reset it to cleanup the commit histories. I added a question about pandoc version as well.

**Comment by ickc** [comment]
I thought that I was making any mistakes when hard resetting it. But GitHub auto-close this pull request (when I hard reset and has no new commits anymore), and my latest commits won't show up until I manually click reopen (GitHub said it will reopen automatically when I have new commits).

Besides the changes I made previously, I changed the wordings in CONTRIBUTING slightly (and correspondingly, the ISSUE_TEMPLATE.md) to simplify, and to ask for pandoc version.

**Comment by jgm** [comment]
I think we should avoid using HTML comments in this.
The template, if we use one, should be as short and simple
as possible.  With HTML comments you might have situations
where they delete the opening but not the closing delimiter,
e.g.

+++ ickc [Nov 02 16 16:02 ]:

**Comment by ickc** [comment]
@jgm, I see nothing after "e.g.". May be GitHub sanitized your HTML code?

#### HTML Comments or not?

An example on how others use it is in [New Issue · caskroom/homebrew-cask](https://github.com/caskroom/homebrew-cask/issues/new). They did not use HTML comments, so if the user didn't delete the texts, it will show up in the issue they submitted (I think in their pull request they ask the user to delete the texts).

But if we use HTML comments, then the users need not to do anything, and it won't show up in the issue/pull request submitted.

I think the chance that the users didn't delete anything is higher than that they delete the HTML comments *partially* only, especially considering the kind of users the templates is targeting at (advanced users don't need these templates).

#### No HTML comment alternative

Alternatively, we can leave the instruction very minimal, so that it is ok to be included in the actual issue/pull request (I think the default behavior of people is they won't delete it).

#### comment on the pull request template?

And please comment on the pull request template. I leave the whole thing in an HTML comment because the list is quite long and I don't want to make filling the checklist mandatory (as pull request types can be quite diversified).

**Comment by ickc** [comment]
By the way, along the line about issue trackers:

I don't know if you mind of not, I'm interested in helping to clean up the issue tracker. e.g. currently there's about 31 open issues that has no comments nor labels applied, and 206 open issues that has no labels.

And I see that there are some "core contributors/developers" applying labels/closing issues here and there. But there seems not a list that includes them. I'm thinking may be a list of their GitHub accounts can be put in CONTRIBUTING.md, so that people can call for their help before calling `@jgm`, to offload the workload from him. The list might even hinted at for which kind of problems whom should be contacted, etc.

**Comment by ickc** [comment]
Some examples on what I want to do about the issue tracker labels:

- expand the [Fixing bugs from the issue tracker](https://github.com/jgm/pandoc/blob/c46ad7c8db5bb6a8c1666f60b21184f5b75bf3ab/CONTRIBUTING.md#fixing-bugs-from-the-issue-tracker) to be up-to-date.

# Current Labels

- AST change
- beginner friendly
- bug
- closing candidate
- docs
- enhancement
- Format: AsciiDoc
- Format: Docx
- Format: HTML
- Format: LaTeX
- Format: Markdown
- Format: ODT
- Format: Org-mode
- Format: RTF
- in progress
- Major
- Minor
- More discussion needed
- More info needed
- Reader
- Writer

# Renamed Labels

- bug
- Difficultly: beginner friendly
- Difficultly: Minor
- Difficultly: Major
- Difficultly: AST change
- docs
- enhancement
- Format: AsciiDoc
- Format: Docx
- Format: HTML
- Format: LaTeX
- Format: Markdown
- Format: ODT
- Format: Org-mode
- Format: RTF
- Waiting: More info needed
- Waiting: More discussion needed
- Todo: in progress
- Todo: closing candidate
- New Reader
- New Writer

# New labels

- Features: ...

e.g.

- Features: MathJax

- Features: Table

- Features: List

**Comment by tarleb** [comment]
I applied some of your renaming-suggestion, sometimes with minor changes (e.g. *Status* instead of *Waiting*).  Adding feature labels might lead to label bloat, the fulltext search function should be enough to find those specific cases.  I'd be happy to assist you if you plan on labeling or re-labeling existing issues.

**Comment by ickc** [comment]
I split this pull request into 3 to let the seemingly related but slightly different matters seperated, hoping to accerlerate the acceptance: #3252, #3253. They are relatively trivial.

I will edit this pull request very soon to deal with pull request template only, which is more controversial on how to do it right.

**Comment by ickc** [comment]
Done, this pull request is only for the pull request template now.

If you feel that a pull request template is unnecessary, feel free to close this. Although it is an excerpt of `CONTRIBUTING.md`, it is still quite long and diverse. I'm not sure if it would be helpful. (Haskell is hard, I guess more people making pull request are more educated? On the other hand, I can recall there was countless pull request dealing with renaming `README`.)

**Pull request closed without merging**
