### PR TITLE
Added native underline support

### PR DESCRIPTION
**Pull request by 0C4**
Note: pandoc-types pull request #53 added a "Underline" inline constructor. 

Committing to pandoc updates that allows for reading/writing underline markup, where supported. Avoids the span-underline hack that was being used previously. Tests cases were added for underlining. All test pass using current ghc/cabal. Closes issue #5044.

### CODE REVIEW

**Comment by 0C4** [comment]
The above pull-request is twined with pantoc-types pull-request #53 since a new underline inline constructor was added. Check above will fail without the update to pandoc-types.

**Comment by mb21** [comment]
Thanks @0C4, 

Unfortunately, you seem to have missed the following quote in the issue:

> Pandoc doesn't have a native representation for
underlined text in its data model, but we could parse
this as a Span with class "underline", just as we do
with in HTML.

For example:

    $ echo '<span class="underline">foo</span>' | pandoc -f html -t native
    [Plain [Span ("",["underline"],[]) [Str "foo"]]]

That's because changing the AST has the potential to break existing pandoc filters, so it's rarely done. And if it needs to be done, it's in a major release. So there is a change this pull request will be used when other AST changes are done, but this will be minimum a few months, possibly years... @jgm?

P.S. unrelated changes (like typos) should be done in separate pull requests... also saw at least one `undefined` in there, which would have to be replaced...

**Comment by 0C4** [comment]
Makes sense; I see looking at the project history. Applying all the above now.

**Comment by mb21** [comment]
Closing this pull request... but please feel free to make a new one with the things discussed above in mind.

**Pull request closed without merging**
