### PR TITLE
PDF: allow custom writer as format if engine is explicitly specified

### PR DESCRIPTION
**Pull request by tarleb**
Closes: #7898

### CODE REVIEW

**Comment by tarleb** [comment]
The only remaining inconvenience is that a template has to be specified on the command line, e.g.

    pandoc -t pdfa.lua --pdf-engine=context --template=default.context input.md

**Comment by jgm** [comment]
I'm not sure what you mean by "allow an empty template."

Actually, I don't think it's so bad if they have to specify the template.
I wonder, though...would it work if you put `default.pdfa.lua` in the templates subdirectory of userdata, or made this a symlink to default.context?

**Comment by tarleb** [comment]
> I'm not sure what you mean by "allow an empty template."

I meant to set the `writerTemplate` to `Nothing`, despite `--standalone` being implied.

> I wonder, though...would it work if you put `default.pdfa.lua` in the templates subdirectory of userdata, or made this a symlink to default.context?

Yes, that works. However, it's rather fagile:

1. The writer should be in the current working directory, as pandoc will search the template relative to the `$DATADIR/template` directory.
2. the writer name should not contain a `-` or `+`, as everything after these is interpreted as extension. I.e., if the writer is named `pdfa-3a.lua`, then the template must be named `default.pdfa`.

I should probably open a new issue for these things.

**Comment by jgm** [comment]
I'm still not clear on the precise change you have in mind ; maybe clearer if you just add a commit that I can look at!

**Comment by tarleb** [comment]
Right, sorry. I've added another commit.

**Comment by tarleb** [comment]
FWIW, this is the full code for the pdfa.lua writer that's fueling most of my motivation for this. The remaining motivation comes from the crossref-xml.lua writer, but that writer is currently still a collection of filters and hacks.

``` lua
local add_tags = {
  traverse = 'topdown',
  Para = function (p)
    return pandoc.Para(
      {pandoc.RawInline('context', '\\startparagraph\n')} ..
      p.content ..
      {pandoc.RawInline('context', '\n\\stopparagraph')}
    )
  end,
  Note = function (n)
    -- "fixing" paragraphs in footnotes leads to layout issues.
    return n, false
  end
}

function Writer (doc, opts)
  local default = pandoc.template.default('context')
  opts.template = pandoc.template.compile(default)
  opts.variables.pdfa ='3a'
  return pandoc.write(doc:walk(add_tags), 'context', opts)
end
```

**Comment by tarleb** [comment]
The downside of this change is that a custom writer cannot know for certain if pandoc was called with `--standalone` or not.

**Comment by tarleb** [comment]
I'm removing the second commit again, the longer I thought about it the less I liked it.

There are some alternative ideas spooking around in my mind, I'll try to forge a separate PR.

**Pull request merged**
