### PR TITLE
Adding SVG support for PDF & DOCX

### PR DESCRIPTION
**Pull request by Twinside**
This pull request adds the following features:
- Convert SVG to PDF for PDF LaTeX output
- Convert SVG to PNG for Docx output
- Retrieve DPI information from Juicy.Pixels

Introduced dependencies:
- rasterific-svg (rendering module)
- svg-tree svg description types

By transitivity, Lens is required by svg-tree.

### CODE REVIEW

**Comment by jgm** [comment]
This seems to have problems compiling with older versions of ghc.
I'm also a bit worried about the lens dependency, which is big.
But the feature is definitely a good one.  Can you see what is going wrong with older ghc?

**Comment by Twinside** [comment]
I think it's easily fixable for GHC 7.6, do you need 7.4?

**Comment by jgm** [comment]
We could probably stop supporting 7.4, now that 7.6 is in
debian stable.

+++ Vincent [Aug 17 15 00:28 ]:

**Comment by Twinside** [comment]
This was tougher than expected, in order to compile:

  * GHC 7.4 is dropped from travis
  * the travis build now uses a sandbox, allowing for an updated `Cabal >= 1.18` (the library)

The use of a more up to date Cabal library is dictated by an more recent `unix` package stemming from a dependency and entering in a [known bug](http://stackoverflow.com/questions/30687926/should-ghc-be-linking-different-versions-of-the-same-libraries) of double linking for the `Setup.hs` file. The bug can be work-arounded by bumping the cabal version and ensure that a recent Cabal version is installed.

Don't hesitate to ask for clarification, as the build passing on GHC 7.6.3 is a work of painful trial and  error, I may have forgotten to clarify some points.

**Comment by dhimmel** [comment]
Is this PR still alive? The ability for SVG images to render in DOCX of PDF exports would be huge!

**Comment by atejeda** [comment]
Any update on this?

**Comment by mb21** [comment]
@Twinside sorry for the hold-up, I guess @jgm couldn't make up his mind whether to merge in the `JuicyPixels` lib with its dependencies.

But seems like quite a bit of this code could be reused for https://github.com/jgm/pandoc/issues/4058#issuecomment-424613868 (i.e. using the `rsvg2pdf` commandline program instead of the `JuicyPixels` library). I can take a look, or do you want to?

**Comment by Twinside** [comment]
Do what you want, I don't care

**Comment by wilx** [comment]
This still seems like worthy addition...

**Pull request closed without merging**
