### PR TITLE
Docx Writer: Filter out illegal XML characters

### LINKED ISSUE #1992: Docx problems with UTF8 invisible characters - resulting file is corrupted
When trying to convert to .docx, the resulting file produces an error on word for mac 2011. The converter only chokes on files that contain UTF8 'FORM FEED (FF)' (U+000C) character.

screen shot 2015-03-05 at 09 46 57

### PR DESCRIPTION
**Pull request by mpickering**
Fixes #1992

### CODE REVIEW

**Comment by nkalvi** [comment]
Is it a 'Pandoc' Sunday? :)

@mpickering Looks very nice - will be revisiting this when learning Haskell :) 

I'm new to git (as well) - how do I test this?

**Comment by mpickering** [comment]
@nkalvi 

Assuming you have already built pandoc from source.

```
git checkout -b mpickering-7.10 master
git pull https://github.com/mpickering/pandoc.git 7.10
```

**Comment by nkalvi** [comment]
@mpickering Yes, I have. Will try now - thank you.

**Comment by nkalvi** [comment]
@mpickering 

Though not needed, I ran a test and can confirm this works perfectly with the following test file (1.13.2's output will result in error).

```
pandoc utf8_sequence_0-0x1ffff_assigned_including-unprintable-asis.txt -o utf8_sequence_0-0x1ffff_assigned_including-unprintable-asis.docx
```
from https://github.com/bits/UTF-8-Unicode-Test-Documents

**Pull request merged**
