### PR TITLE
Haddock Writer: Use proper haddock math escapes

### PR DESCRIPTION
**Pull request by expipiplus1**
As implemented here: https://github.com/haskell/haddock/pull/465/commits/3f50b955324bd4b42f88a421f0203bc46a3ccf64

### CODE REVIEW

**Comment by wilx** [comment]
@expipiplus1 You need to adjust test cases to match the new output. See the Travis CI results.

**Comment by expipiplus1** [comment]
Hmm, it seems as though the output isn't strictly an improvement...

I certainly prefer `/α/ ∧ /ω/` over `\(\alpha \wedge \omega\)`

This is the test diff:

```
 ------------------------------------------------------------------------
          --- writer.haddock
          +++ /home/travis/build/jgm/pandoc/sourcedist/dist/build/pandoc/pandoc --quiet testsuite.native -r native -w haddock --columns=78 --variable pandoc-version= -s
          + 458 -   \(2+2=4\)
          + 459 -   \(x \in y\)
          + 460 -   \(\alpha \wedge \omega\)
          + 461 -   \(223\)
          + 462 -   \(p\)-Tree
          - 458 -   2 + 2 = 4
          - 459 -   /x/ ∈ /y/
          - 460 -   /α/ ∧ /ω/
          - 461 -   223
          - 462 -   /p/-Tree
          + 464     \\[\frac{d}{dx}f(x)=\lim_{h\to 0}\frac{f(x+h)-f(x)}{h}\\]
          + 465 -   Here’s one that has a line break in it: \(\alpha + \omega \times x^2\).
          - 464     $$\\frac{d}{dx}f(x)=\\lim_{h\\to 0}\\frac{f(x+h)-f(x)}{h}$$
          - 465 -   Here’s one that has a line break in it: /α/ + /ω/ × /x/2.
          ------------------------------------------------------------------------
```

**Comment by expipiplus1** [comment]
It's obviously a big improvement for big blocks of Latex though:

In action here: https://hackage.haskell.org/package/vulkan-2.0.0.0/docs/Graphics-Vulkan-Core10-CommandBufferBuilding.html#v:vkCmdSetDepthBias

**Comment by jgm** [comment]
I suppose we could make the haddock output sensitive to the writerHTMLMathMethod, which is set by flags like `--mathjax`.  This would allow haddock users the option of "faking it with unicode" or including raw latex math.

**Comment by expipiplus1** [comment]
Ah, that is a mistake. I think it should be \\( too.

It would be nice perhaps if there was some simple metric of how faithful the non latex math renders. Lots of the haddock I read is just in ascii form and keeping that clear is useful.

**Comment by expipiplus1** [comment]
Actually, I think that's something to delegate to the tex writer. It could replace things like `\alpha` with `α`.

**Comment by jgm** [comment]
Pandoc uses the texmath for math conversion.  One conversion mode
is to unicode plain text.  This is what is currently used.
However, it will fail when the math gets moderately complex
(e.g. fractions, which can't easily be represented in a unicode
string). For the most uniform results, it's best to use latex
output throughout, probably.

**Comment by jgm** [comment]
I merged this manually, thanks!

**Comment by expipiplus1** [comment]
Thank!

**Pull request closed without merging**
