### PR TITLE
List all styles in manual for --reference-docx

### PR DESCRIPTION
**Pull request by infotroph**
I'm working on the assumption that styles.xml is the canonical list of styles known to the docx writer; if this is wrong, please advise. 

Possibly related to #2048, but only a minor subset of it.

### CODE REVIEW

**Comment by jgm** [comment]
Thanks very much!  However, pandoc.1 shouldn't be modified by hand.  Instead, please modify README.  You can then generate pandoc.1 from README using `make man/pandoc.1`.  Note also that lines should be hard-wrapped as they are currently in README.

**Comment by infotroph** [comment]
Sure thing, but let me make sure I'm following correctly: I should update the PR with the resulting changed versions of both README and pandoc.1, correct? Or do I edit README, test with `make`, and only commit the changes to README?

**Comment by jgm** [comment]
It would be enough to edit README, since I'll update the man
page before the next release.

But if you like, you can regenerate man/pandoc.1 and commit it
too.  (We include this in the repository because adding it
to the build process in a way that works across all
platforms proved frustrating.)

+++ Chris Black [Jul 21 15 12:26 ]:

**Comment by infotroph** [comment]
Here's the edited README. I took a short stab at rebuilding man/pandoc.1, but got errors that look to me like they come from issues with my (freshly-installed, untested) Haskell environment:

```
> make man/pandoc.1
pandoc README -t man -s --template man/pandoc.1.template \
		--filter man/capitalizeHeaders.hs \
		--filter man/removeNotes.hs \
		--filter man/removeLinks.hs \
		-o man/pandoc.1
pandoc: Error running filter man/capitalizeHeaders.hs
fd:4: hPutBuf: resource vanished (Broken pipe)
make: *** [man/pandoc.1] Error 83
```

I'm happy to keep trying on this and update when I have a working build, or if you prefer you can merge now. Sorry for the messy branch!

**Comment by jgm** [comment]
Can you submit a PR with just the README changes, so I can
cleanly merge it?

+++ Chris Black [Jul 21 15 14:38 ]:

**Comment by infotroph** [comment]
Clean version, with rebuilt man page, at #2318. Thanks for the tips and sorry for the extra noise!

**Pull request closed without merging**
