### PR TITLE
Add `--list-formats` option

### PR DESCRIPTION
**Pull request by codebje**
This PR adds a -l/--list-formats option to list the available input and output formats, addressing #2685.

### CODE REVIEW

**Comment by jgm** [comment]
Thanks for your contribution!

I'm not sure why this is needed, however, since `--help` already lists the formats.

I'd prefer not to add another command-line option just to print part of the existing help message.  Is there some specific reason for doing this?

Also, this PR seems to affect `--version` output as well.

**Comment by codebje** [comment]
I added this PR to get my feet wet with the pandoc codebase, based on the linked issue.  The `--version` change seemed apropos given the syntax types were also listed there, but I'm happy to either back out that change, or let the whole PR go if you're satisfied with it being in `--help` only.

**Comment by tarleb** [comment]
Mea culpa.  I misinterpreted what was said in the linked issue, causing me to classify it as beginner friendly instead of closing it.  I'm terribly sorry for wasting your time. :disappointed: 

The change itself looks very nice and clean. We'd be more than happy if you were to continue contributing.  If you still feel like it, may I suggest you take a look at #1775 instead?  It's another issue involving command line options but also leads a little more into the depths of pandoc's internals.

Again, thank you for contributing and apologies for the trouble.

**Comment by jgm** [comment]
@codebje - thanks for getting your feet wet, and as @tarleb says, it's a solid PR.  I'm going to comment on the linked issue with some further ideas about changes that I think would be more useful.

**Comment by codebje** [comment]
No problem at all, I'll close this one and have a look at some other stuff :-)

**Pull request closed without merging**
