### PR TITLE
Combine LaTeX/Beamer templates

### LINKED ISSUE #3878: Synchronize or combine LaTeX/Beamer templates
Some of the recent changes to the LaTeX template need to be merged into the Beamer template, notably the use of `unicode-math` and `luatexja`.

Before working through this, would it indeed make sense to determine whether the two templates should be combined, as suggested in #3873? I haven't tested it, but it should theoretically be possible if the writer set a `beamer` variable to true and several conditionals were included to include and exclude several parts. This would make the template more complex to customize, but it would also make it easier to maintain within the codebase.

### PR DESCRIPTION
**Pull request by adunning**
In this template, the sections needed by Beamer (and that need to be taken out) are taken care of using conditionals with the `beamer` variable, already set by the writer as it turns out. Closes #3878.

This is meant to show what this looks like in practice, to facilitate a decision on whether the simplified internal maintenance outweighs the complexity added to the template. It works with some sample documents I have to hand, but I haven't tested it extensively with the Beamer-specific variables.

Should more conditionals be added to prevent variables not applicable to Beamer from being passed on (`linestretch`, `geometry`, `lof`, `lot`)?

### CODE REVIEW

**Comment by adunning** [comment]
This also now closes #3877. While the `dvipsnames` option could be sent along for Beamer only to avoid loading `xcolor`, this ensures consistency and allows for a wider selection of colours with `svgnames`.

**Comment by jgm** [comment]
We should incorporate the changes in commit 732005456e2b28150943a5a4e11bca6e1566f309, if it still seems a good idea to merge the two templates.

**Comment by adunning** [comment]
Done. After using it for a couple of weeks, my feeling is that the changes don't unnecessarily increase the complexity of the template, and indeed merging the files makes it much easier to maintain a custom template if one uses both standard LaTeX and Beamer.

**Comment by jgm** [comment]
Thanks for doing this!

**Comment by adunning** [comment]
You're most welcome; thanks for the idea!

**Pull request merged**
