### PR TITLE
Manual: Add syntax highlighting

### PR DESCRIPTION
**Pull request by adunning**
Use fenced code blocks to mark language names for code examples.

(Is there a highlighting language for the templates?)

### CODE REVIEW

**Comment by mb21** [comment]
Nice! But aren't we usually using ` ``` ` instead of ` ~~~ ` in the MANUAL?

**Comment by adunning** [comment]
I was doing that on the basis that the tildes are listed as the primary method of fenced code blocks, but I've no preference in the matter.

**Comment by mb21** [comment]
me neither :)

**Comment by jgm** [comment]
I have mixed feelings about this.  I don't really think syntax highlighting is is so important for these short samples, and I think adding the fences detracts from the plain-source readability of the manual.

If we did do it, I think we should probably use backticks, because that's compatible with more implementations.

**Comment by adunning** [comment]
Possibly use syntax highlighting only for extended non-Markdown examples? I think it improves readability most with the examples in YAML, CSS, Lua, etc.

**Comment by jgm** [comment]
I think I'm going to pass on this one.  The vast majority of code samples are markdown.  And I think the aesthetics look funny if some of the code is highlighted and other not.  We already do use highlighting for the lua filters documentation, where I think it makes sense.

**Pull request closed without merging**
