### PR TITLE
CONTRIBUTING.md : update test enabling documentation

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**
On my end, in a clean sandbox, I had to run this before I could run the tests, I'm a cabal / haskell noob so that might not be the best way to do so but :)

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
By the way I've got a significant amount of tests failing here, here's the report summary : 

         Properties   Test Cases    Total        
 Passed  10           558           568          
 Failed  0            91            91           
 Total   10           649           659          
Test suite test-pandoc: FAIL

Is that the expected result ?

**Comment by MathieuDuponchelle** [comment]
I also can't figure out how to run a specific test, would be great to specify that :)

**Comment by jgm** [comment]
No, you shouldn't get test failures.  My guess is that you
may have forgotten to do

    git submodule update --init

after cloning the repository.  If that doesn't do it, post
the test failures.


+++ Mathieu Duponchelle [Feb 05 16 12:31 ]:

**Comment by MathieuDuponchelle** [comment]
OK, pasting here cause for some reason the test results seem to trigger spam protection of both pastebin and fpaste oO

Also I'm not sure what I did but there's actually only 7 tests failing now, I'm pretty sure I had run the submodule init before but :)

**Comment by MathieuDuponchelle** [comment]
Preprocessing library pandoc-1.17...
In-place registering pandoc-1.17...
Preprocessing test suite 'test-pandoc' for pandoc-1.17...
Running 1 test suites...
Test suite test-pandoc: RUNNING...
Old:
  markdown:
    writer:
      basic: [OK]
      tables: [OK]
      lhs to normal: [OK]
      lhs to lhs: [OK]
    reader:
      basic: [Failed]

------------------------------------------------------------------------
--- testsuite.native
+++ /home/meh/devel/pandoc/dist/build/pandoc/pandoc --data-dir ../data testsuite.txt -r markdown -w native -s -S
+ 338 ,Para [Str "AT&amp;T",Space,Str "is",Space,Str "another",Space,Str "way",Space,Str "to",Space,Str "write",Space,Str "it."]
- 338 ,Para [Str "AT&T",Space,Str "is",Space,Str "another",Space,Str "way",Space,Str "to",Space,Str "write",Space,Str "it."]
------------------------------------------------------------------------
      tables: [OK]
      pipe tables: [OK]
      more: [Failed]

------------------------------------------------------------------------
--- markdown-reader-more.native
+++ /home/meh/devel/pandoc/dist/build/pandoc/pandoc --data-dir ../data markdown-reader-more.txt -r markdown -w native -S
+ 147 ,Para [Link ("",[],[]) [Str "link"] ("/&uuml;rl","&ouml;&ouml;!")]
+ 148 ,Para [Link ("",[],[]) [Str "http://g&ouml;&ouml;gle.com"] ("http://g&ouml;&ouml;gle.com","")]
+ 149 ,Para [Link ("",[],[]) [Str "me@ex&auml;mple.com"] ("mailto:me@ex&auml;mple.com","")]
+ 150 ,Para [Link ("",[],[]) [Str "foobar"] ("/&uuml;rl","&ouml;&ouml;!")]
- 147 ,Para [Link ("",[],[]) [Str "link"] ("/\252rl","\246\246!")]
- 148 ,Para [Link ("",[],[]) [Str "http://g\246\246gle.com"] ("http://g\246\246gle.com","")]
- 149 ,Para [Link ("",[],[]) [Str "me@ex\228mple.com"] ("mailto:me@ex\228mple.com","")]
- 150 ,Para [Link ("",[],[]) [Str "foobar"] ("/\252rl","\246\246!")]
------------------------------------------------------------------------
      lhs: [OK]
    citations:
      citations: [OK]
  rst:
    writer:
      basic: [OK]
      tables: [OK]
      lhs to normal: [OK]
      lhs to lhs: [OK]
    reader:
      basic: [OK]
      tables: [OK]
      lhs: [OK]
  latex:
    writer:
      basic: [OK]
      tables: [OK]
      lhs to normal: [OK]
      lhs to lhs: [OK]
    reader:
      basic: [OK]
      lhs: [OK]
  html:
    writer:
      basic: [OK]
      tables: [OK]
      lhs to normal: [OK]
      lhs to lhs: [OK]
    reader: [OK]
  s5:
    s5 writer (basic): [OK]
    s5 writer (fancy): [OK]
    html writer (fragment): [OK]
    html writer (inserts): [OK]
  textile:
    writer:
      basic: [OK]
      tables: [OK]
    reader: [Failed]

------------------------------------------------------------------------
--- textile-reader.native
+++ /home/meh/devel/pandoc/dist/build/pandoc/pandoc --data-dir ../data textile-reader.textile -r textile -w native -s
+ 150 ,Para [Str "*",LineBreak,Str "&amp;"]
- 150 ,Para [Str "*",LineBreak,Str "&"]
------------------------------------------------------------------------
  docbook:
    writer:
      basic: [OK]
      tables: [OK]
    reader: [OK]
    reader: [OK]
  native:
    writer:
      basic: [OK]
      tables: [OK]
    reader: [OK]
  fb2:
    basic: [OK]
    titles: [OK]
    images: [OK]
    images-embedded: [OK]
    math: [OK]
    tables: [OK]
    testsuite: [OK]
  mediawiki:
    writer:
      basic: [OK]
      tables: [OK]
    reader: [Failed]

------------------------------------------------------------------------
--- mediawiki-reader.native
+++ /home/meh/devel/pandoc/dist/build/pandoc/pandoc --data-dir ../data mediawiki-reader.wiki -r mediawiki -w native -s
+  27 ,Para [Str "hi",Space,Str "&amp;",Space,Str "low"]
+  28 ,Para [Str "G&ouml;del"]
-  27 ,Para [Str "hi",Space,Str "&",Space,Str "low"]
-  28 ,Para [Str "G\246del"]
------------------------------------------------------------------------
  dokuwiki:
    writer:
      basic: [OK]
      tables: [OK]
    inline_formatting: [OK]
    multiblock table: [OK]
    external images: [OK]
  opml:
    basic: [OK]
    reader: [OK]
  haddock:
    writer:
      basic: [OK]
      tables: [OK]
    reader: [OK]
  txt2tags:
    reader: [OK]
  epub:
    features: [OK]
    wasteland: [OK]
    formatting: [OK]
  twiki:
    reader: [Failed]

------------------------------------------------------------------------
--- twiki-reader.native
+++ /home/meh/devel/pandoc/dist/build/pandoc/pandoc --data-dir ../data twiki-reader.twiki -r twiki -w native -s
+  25 ,Para [Str "hi",Space,Str "&amp;",Space,Str "low"]
+  26 ,Para [Str "G&ouml;del"]
-  25 ,Para [Str "hi",Space,Str "&",Space,Str "low"]
-  26 ,Para [Str "G\246del"]
------------------------------------------------------------------------
  other writers:
    opendocument:
      basic: [OK]
      tables: [OK]
    context:
      basic: [OK]
      tables: [OK]
    texinfo:
      basic: [OK]
      tables: [OK]
    icml:
      basic: [OK]
      tables: [OK]
    tei:
      basic: [OK]
      tables: [OK]
    man:
      basic: [OK]
      tables: [OK]
    plain:
      basic: [OK]
      tables: [OK]
    rtf:
      basic: [OK]
      tables: [OK]
    org:
      basic: [OK]
      tables: [OK]
    asciidoc:
      basic: [OK]
      tables: [OK]
  writers-lang-and-dir:
    latex: [OK]
    context: [OK]
Shared:
  normalize:
    p_normalize_blocks_rt: [OK, passed 100 tests]
    p_normalize_inlines_rt: [OK, passed 100 tests]
    p_normalize_no_trailing_spaces: [OK, passed 100 tests]
  compactify'DL:
    compactify'DL with empty def: [OK]
  collapseFilePath:
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
    collapse: [OK]
Walk:
  Walk:
    p_walk inlineTrans: [OK, passed 100 tests]
    p_walk blockTrans: [OK, passed 100 tests]
    p_query inlineQuery: [OK, passed 100 tests]
    p_query blockQuery: [OK, passed 100 tests]
Writers:
  Native:
    p_write_rt: [OK, passed 100 tests]
    p_write_blocks_rt: [OK, passed 100 tests]
  ConTeXt:
    inline code:
      with '}': [OK]
      without '}': [OK]
      code property: [OK, passed 100 tests]
    headers:
      level 1: [OK]
    bullet lists:
      nested: [OK]
  LaTeX:
    code blocks:
      in footnotes: [OK]
      identifier: [OK]
      no identifier: [OK]
    definition lists:
      with internal link: [OK]
    math:
      escape |: [OK]
    headers:
      unnumbered header: [OK]
      in list item: [OK]
      in definition list item: [OK]
      containing image: [OK]
    inline code:
      struck out and highlighted: [OK]
      struck out and not highlighted: [OK]
      single quotes: [OK]
  HTML:
    inline code:
      basic: [OK]
      haskell: [OK]
      nolanguage: [OK]
    images:
      alt with formatting: [OK]
  Docbook:
    line blocks:
      none: [OK]
      basic: [OK]
      blockquote: [OK]
      footnote: [OK]
    compact lists:
      bullet:
        compact: [OK]
        loose: [OK]
      ordered:
        compact: [OK]
        loose: [OK]
      definition:
        compact: [OK]
        loose: [OK]
  Markdown:
    indented code after list: [OK]
    list with tight sublist: [OK]
    Shortcut reference links:
      Simple link (shortcutable): [OK]
      Followed by another link (unshortcutable): [OK]
      Followed by space and another link (unshortcutable): [OK]
      Reference link is used multiple times (unshortcutable): [OK]
      Reference link is used multiple times (unshortcutable): [OK]
      Reference link is followed by text in brackets: [OK]
      Reference link is followed by space and text in brackets: [OK]
      Reference link is followed by RawInline: [OK]
      Reference link is followed by space and RawInline: [OK]
      Reference link is followed by RawInline with space: [OK]
      Reference link is followed by citation: [OK]
      Reference link is followed by space and citation: [OK]
  Plain:
    strongly emphasized text to uppercase: [OK]
  AsciiDoc:
    emphasis:
      emph word before: [OK]
      emph word after: [OK]
      emph quoted: [OK]
      strong word before: [OK]
      strong word after: [OK]
      strong quoted: [OK]
    tables:
      empty cells: [OK]
      multiblock cells: [OK]
  Docx:
    inlines:
      font formatting: [OK]
      font formatting with character styles: [OK]
      hyperlinks: [OK]
      inline image: [OK]
      inline image in links: [OK]
      handling unicode input: [OK]
      literal tabs: [OK]
      normalizing inlines: [OK]
      normalizing inlines deep inside blocks: [OK]
      move trailing spaces outside of formatting: [OK]
      inline code (with VerbatimChar style): [OK]
      inline code in subscript and superscript: [OK]
    blocks:
      headers: [OK]
      headers already having auto identifiers: [OK]
      numbered headers automatically made into list: [OK]
      i18n blocks (headers and blockquotes): [OK]
      lists: [OK]
      definition lists: [OK]
      custom defined lists in styles: [OK]
      footnotes and endnotes: [OK]
      blockquotes (parsing indent as blockquote): [OK]
      hanging indents: [OK]
      tables: [OK]
      tables with lists in cells: [OK]
      code block: [OK]
      dropcap paragraphs: [OK]
    metadata:
      metadata fields: [OK]
      stop recording metadata with normal text: [OK]
  RST:
    rubrics:
      in list item: [OK]
      in definition list item: [OK]
      in block quote: [OK]
      with id: [OK]
      with id class: [OK]
    headings:
      normal heading: [OK]
      heading levels: [OK]
      minimal heading levels: [OK]
  TEI:
    block elements:
      para: [OK]
    inlines:
      Emphasis: [OK]
      SingleQuoted: [OK]
      DoubleQuoted: [OK]
      NestedQuoted: [OK]
Readers:
  LaTeX:
    basic:
      simple: [OK]
      space: [OK]
      emphasized: [OK]
    headers:
      level 1: [OK]
      level 2: [OK]
      level 3: [OK]
      emph: [OK]
      link: [OK]
    math:
      escaped $: [OK]
    space and comments:
      blank lines + space at beginning: [OK]
      blank lines + space + comments: [OK]
      comment in paragraph: [OK]
    code blocks:
      identifier: [OK]
      no identifier: [OK]
    tables:
      Single cell table: [OK]
      Multi cell table: [OK]
      Multi line table: [OK]
      Empty table: [OK]
      Table with fixed column width: [OK]
      Table with empty column separators: [OK]
      Table with custom column separators: [OK]
      Table with vertical alignment argument: [OK]
    citations:
      natbib:
        citet: [OK]
        suffix: [OK]
        suffix long: [OK]
        multiple: [OK]
        group: [OK]
        suffix and locator: [OK]
        suffix only: [OK]
        no author: [OK]
        markup: [OK]
      biblatex:
        textcite: [OK]
        suffix: [OK]
        suffix long: [OK]
        multiple: [OK]
        group: [OK]
        suffix and locator: [OK]
        suffix only: [OK]
        no author: [OK]
        markup: [OK]
        parencite: [OK]
    Character Escapes:
      Two-character escapes: [OK]
      One-character escapes: [OK]
  Markdown:
    inline code:
      with attribute: [OK]
      with attribute space: [OK]
    emph and strong:
      two strongs in emph: [OK]
      emph and strong emph alternating: [OK]
      emph with spaced strong: [OK]
      intraword underscore with opening underscore (#1121): [OK]
    raw LaTeX:
      in URL: [OK]
    raw HTML:
      nesting (issue #1330): [OK]
      invalid tag (issue #1820: [OK]
      technically invalid comment: [OK]
      issue 2469: [OK]
    emoji:
      emoji symbols: [OK]
    unbalanced brackets: [OK]
    backslash escapes:
      in URL: [OK]
      in title: [OK]
      in reference link title: [OK]
      in reference link URL: [OK]
    bare URIs:
      http://google.com is a search engine.: [OK]
      <a href="http://foo.bar.baz">http://foo.bar.baz</a>: [OK]
      Try this query: http://google.com?search=fish&time=hour.: [OK]
      HTTPS://GOOGLE.COM,: [OK]
      http://el.wikipedia.org/wiki/Τεχνολογία,: [OK]
      doi:10.1000/182,: [OK]
      git://github.com/foo/bar.git,: [OK]
      file:///Users/joe/joe.txt, and: [OK]
      mailto:someone@somedomain.com.: [OK]
      Use http: this is not a link!: [OK]
      (http://google.com).: [OK]
      http://en.wikipedia.org/wiki/Sprite_(computer_graphics): [OK]
      http://en.wikipedia.org/wiki/Sprite_[computer_graphics]: [OK]
      http://en.wikipedia.org/wiki/Sprite_{computer_graphics}: [OK]
      http://example.com/Notification_Center-GitHub-20101108-140050.jpg: [OK]
      https://github.com/github/hubot/blob/master/scripts/cream.js#L20-20: [OK]
      http://www.rubyonrails.com: [OK]
      http://www.rubyonrails.com:80: [OK]
      http://www.rubyonrails.com/~minam: [OK]
      https://www.rubyonrails.com/~minam: [OK]
      http://www.rubyonrails.com/~minam/url%20with%20spaces: [OK]
      http://www.rubyonrails.com/foo.cgi?something=here: [OK]
      http://www.rubyonrails.com/foo.cgi?something=here&and=here: [OK]
      http://www.rubyonrails.com/contact;new: [OK]
      http://www.rubyonrails.com/contact;new%20with%20spaces: [OK]
      http://www.rubyonrails.com/contact;new?with=query&string=params: [OK]
      http://www.rubyonrails.com/~minam/contact;new?with=query&string=params: [OK]
      http://en.wikipedia.org/wiki/Wikipedia:Today%27s_featured_picture_%28animation%29/January_20%2C_2007: [OK]
      http://www.mail-archive.com/rails@lists.rubyonrails.org/: [OK]
      http://www.amazon.com/Testing-Equal-Sign-In-Path/ref=pd_bbs_sr_1?ie=UTF8&s=books&qid=1198861734&sr=8-1: [OK]
      http://en.wikipedia.org/wiki/Texas_hold%27em: [OK]
      https://www.google.com/doku.php?id=gps:resource:scs:start: [OK]
      http://www.rubyonrails.com: [OK]
      http://manuals.ruby-on-rails.com/read/chapter.need_a-period/103#page281: [OK]
      http://foo.example.com/controller/action?parm=value&p2=v2#anchor123: [OK]
      http://foo.example.com:3000/controller/action: [OK]
      http://foo.example.com:3000/controller/action+pack: [OK]
      http://business.timesonline.co.uk/article/0,,9065-2473189,00.html: [OK]
      http://www.mail-archive.com/ruby-talk@ruby-lang.org/: [OK]
      https://example.org/?anchor=lala-: [OK]
      https://example.org/?anchor=-lala: [OK]
    autolinks:
      with unicode dash following: [OK]
      a partial URL (#2277): [OK]
    links:
      no autolink inside link: [OK]
      no inline link inside link: [OK]
      no bare URI inside link: [OK]
    Headers:
      blank line before header: [OK]
      bracketed text (#2062): [OK]
      ATX header without trailing #s: [OK]
      ATX header without trailing #s: [OK]
      setext header: [OK]
    Implicit header references:
      ATX header without trailing #s: [OK]
      ATX header with trailing #s: [OK]
      setext header: [OK]
    smart punctuation:
      quote before ellipses: [OK]
      apostrophe before emph: [OK]
      apostrophe in French: [OK]
      apostrophe after math: [OK]
    footnotes:
      indent followed by newline and flush-left text: [OK]
      indent followed by newline and indented text: [OK]
      recursive note: [OK]
    lhs:
      inverse bird tracks and html: [OK]
    definition lists:
      no blank space: [OK]
      blank space before first def: [OK]
      blank space before second def: [OK]
      laziness: [OK]
      no blank space before first of two paragraphs: [OK]
      first line not indented: [OK]
      list in definition: [OK]
      in div: [OK]
    +compact_definition_lists:
      basic compact list: [OK]
    lists:
      issue #1154: [OK]
      issue #1636: [OK]
    entities:
      character references: [Failed]

-------------------------------------------------------------- input ---
&lang; &ouml;
------------------------------------------------------------- result ---
- [Para [Str "\10216",Space,Str "\246"]]
+ [Para [Str "&lang;",Space,Str "&ouml;"]]
------------------------------------------------------------------------
      numeric: [OK]
      in link title: [Failed]

-------------------------------------------------------------- input ---
[link](/url "title &lang; &ouml; &#44;")
------------------------------------------------------------- result ---
- [Para [Link ("",[],[]) [Str "link"] ("/url","title \10216 \246 ,")]]
+ [Para [Link ("",[],[]) [Str "link"] ("/url","title &lang; &ouml; ,")]]
------------------------------------------------------------------------
    citations:
      simple: [OK]
      key starts with digit: [OK]
    footnote/link following citation:
      footnote: [OK]
      normal link: [OK]
      reference link: [OK]
      short reference link: [OK]
      implicit header link: [OK]
      regular citation: [OK]
  HTML:
    base tag:
      simple: [OK]
      slash at end of base: [OK]
      absolute URL: [OK]
  Org:
    Inlines:
      Plain String: [OK]
      Emphasis: [OK]
      Strong: [OK]
      Strong Emphasis: [OK]
      Strikeout: [OK]
      Verbatim: [OK]
      Code: [OK]
      Math $..$: [OK]
      Math $$..$$: [OK]
      Math \[..\]: [OK]
      Math \(..\): [OK]
      Symbol: [OK]
      Superscript simple expression: [OK]
      Superscript multi char: [OK]
      Subscript simple expression: [OK]
      Subscript multi char: [OK]
      Linebreak: [OK]
      Inline note: [OK]
      Markup-chars not occuring on word break are symbols: [OK]
      No empty markup: [OK]
      Adherence to Org's rules for markup borders: [OK]
      Quotes are forbidden border chars: [OK]
      Commata are forbidden border chars: [OK]
      Markup should work properly after a blank line: [OK]
      Inline math must stay within three lines: [OK]
      Single-character math: [OK]
      Markup may not span more than two lines: [OK]
      Sub- and superscript expressions: [OK]
      Image: [OK]
      Explicit link: [OK]
      Self-link: [OK]
      Absolute file link: [OK]
      Link to file in parent directory: [OK]
      Empty link (for gitit interop): [OK]
      Image link: [OK]
      Image link with non-image target: [OK]
      Plain link: [OK]
      Angle link: [OK]
      Absolute file link: [OK]
      File link: [OK]
      Anchor: [OK]
      Inline code block: [OK]
      Inline code block with arguments: [OK]
      Inline code block with toggle: [OK]
      Citation: [OK]
      Citation containing text: [OK]
      Inline LaTeX symbol: [OK]
      Inline LaTeX command: [OK]
      Inline LaTeX math symbol: [OK]
      Unknown inline LaTeX command: [OK]
      MathML symbol in LaTeX-style: [OK]
      MathML symbol in LaTeX-style, including braces: [OK]
      MathML copy sign: [OK]
      LaTeX citation: [OK]
    Meta Information:
      Comment: [OK]
      Not a comment: [OK]
      Comment surrounded by Text: [OK]
      Title: [OK]
      Author: [OK]
      Date: [OK]
      Description: [OK]
      Properties drawer: [OK]
      Logbook drawer: [OK]
      Drawer surrounded by text: [OK]
      Drawer start is the only text in first line of a drawer: [OK]
      Drawers with unknown names are just text: [OK]
      Anchor reference: [OK]
      Search links are read as emph: [OK]
      Link to nonexistent anchor: [OK]
      Link abbreviation: [OK]
      Link abbreviation, defined after first use: [OK]
      Link abbreviation, URL encoded arguments: [OK]
      Link abbreviation, append arguments: [OK]
    Basic Blocks:
      Paragraph: [OK]
      First Level Header: [OK]
      Third Level Header: [OK]
      Compact Headers with Paragraph: [OK]
      Separated Headers with Paragraph: [OK]
      Headers not preceded by a blank line: [OK]
      Tagged headers: [OK]
      Untagged header containing colons: [OK]
      Header starting with strokeout text: [OK]
      Comment Trees: [OK]
      Nothing but a COMMENT header: [OK]
      Tree with :noexport:: [OK]
      Subtree with :noexport:: [OK]
      Paragraph starting with an asterisk: [OK]
      Paragraph containing asterisk at beginning of line: [OK]
      Example block: [OK]
      Example block surrounded by text: [OK]
      Horizontal Rule: [OK]
      Not a Horizontal Rule: [OK]
      Comment Block: [OK]
      Figure: [OK]
      Unnamed figure: [OK]
      Figure with `fig:` prefix in name: [OK]
      Footnote: [OK]
      Two footnotes: [OK]
      Footnote followed by header: [OK]
    Lists:
      Simple Bullet Lists: [OK]
      Indented Bullet Lists: [OK]
      Unindented *: [OK]
      Multi-line Bullet Lists: [OK]
      Nested Bullet Lists: [OK]
      Bullet List with Decreasing Indent: [OK]
      Header follows Bullet List: [OK]
      Bullet List Unindented with trailing Header: [OK]
      Simple Ordered List: [OK]
      Simple Ordered List with Parens: [OK]
      Indented Ordered List: [OK]
      Nested Ordered Lists: [OK]
      Ordered List in Bullet List: [OK]
      Bullet List in Ordered List: [OK]
      Definition List: [OK]
      Definition list with multi-word term: [OK]
      Compact definition list: [OK]
      Definition List With Trailing Header: [OK]
      Definition lists double-colon markers must be surrounded by whitespace: [OK]
      Loose bullet list: [OK]
      Recognize preceding paragraphs in non-list contexts: [OK]
    Tables:
      Single cell table: [OK]
      Multi cell table: [OK]
      Multi line table: [OK]
      Empty table: [OK]
      Glider Table: [OK]
      Table between Paragraphs: [OK]
      Table with Header: [OK]
      Table with final hline: [OK]
      Table in a box: [OK]
      Table with alignment row: [OK]
      Pipe within text doesn't start a table: [OK]
      Missing pipe at end of row: [OK]
      Table with differing row lengths: [OK]
      Table with caption: [OK]
    Blocks and fragments:
      Source block: [OK]
      Source block between paragraphs: [OK]
      Source block with rundoc/babel arguments: [OK]
      Source block with results and :exports both: [OK]
      Source block with results and :exports code: [OK]
      Source block with results and :exports results: [OK]
      Source block with results and :exports none: [OK]
      Source block with toggling header arguments: [OK]
      Example block: [OK]
      HTML block: [OK]
      Quote block: [OK]
      Verse block: [OK]
      Verse block with newlines: [OK]
      LaTeX fragment: [OK]
      Code block with caption: [OK]
      Convert blank lines in blocks to single newlines: [OK]
      Non-letter chars in source block parameters: [OK]
    Smart punctuation:
      quote before ellipses: [OK]
      apostrophe before emph: [OK]
      apostrophe in French: [OK]
      Quotes cannot occur at the end of emphasized text: [OK]
      Dashes are allowed at the borders of emphasis': [OK]
      Single quotes can be followed by emphasized text: [OK]
      Double quotes can be followed by emphasized text: [OK]
  RST:
    line block with blank line: [OK]
    field list:
      general: [OK]
      metadata: [OK]
      with inline markup: [OK]
    URLs with following punctuation: [OK]
    Reference names with special characters: [OK]
    literal / line / code blocks:
      indented literal block: [OK]
      line block with 3 lines: [OK]
      quoted literal block using >: [OK]
      quoted literal block using | (not  a line block): [OK]
      class directive with single paragraph: [OK]
      class directive with two paragraphs: [OK]
      class directive around literal block: [OK]
    interpreted text roles:
      literal role prefix: [OK]
      literal role postfix: [OK]
      literal text: [OK]
      code role: [OK]
      inherited code role: [OK]
      custom code role with language field: [OK]
      custom role with unspecified parent role: [OK]
      role with recursive inheritance: [OK]
      unknown role: [OK]
  Docx:
    inlines:
      font formatting: [OK]
      font formatting with character styles: [OK]
      hyperlinks: [OK]
      normalizing adjacent hyperlinks: [OK]
      inline image: [OK]
      VML image: [OK]
      inline image in links: [OK]
      handling unicode input: [OK]
      literal tabs: [OK]
      special punctuation: [OK]
      normalizing inlines: [OK]
      normalizing inlines deep inside blocks: [OK]
      move trailing spaces outside of formatting: [OK]
      inline code (with VerbatimChar style): [OK]
      inline code in subscript and superscript: [OK]
    blocks:
      headers: [OK]
      headers already having auto identifiers: [OK]
      numbered headers automatically made into list: [OK]
      i18n blocks (headers and blockquotes): [OK]
      lists: [OK]
      definition lists: [OK]
      custom defined lists in styles: [OK]
      user deletes bullet after list item (=> part of item par): [OK]
      user deletes bullet after par (=> new par): [OK]
      footnotes and endnotes: [OK]
      links in footnotes and endnotes: [OK]
      blockquotes (parsing indent as blockquote): [OK]
      hanging indents: [OK]
      tables: [OK]
      tables with lists in cells: [OK]
      code block: [OK]
      dropcap paragraphs: [OK]
    track changes:
      insertion (default): [OK]
      insert insertion (accept): [OK]
      remove insertion (reject): [OK]
      deletion (default): [OK]
      remove deletion (accept): [OK]
      insert deletion (reject): [OK]
      keep insertion (all): [OK]
      keep deletion (all): [OK]
    media:
      image extraction: [OK]
    metadata:
      metadata fields: [OK]
      stop recording metadata with normal text: [OK]
  Odt:
    bold: [OK]
    endnote: [OK]
    externalLink: [OK]
    footnote: [OK]
    headers: [OK]
    italic: [OK]
    paragraph: [OK]
    strikeout: [OK]
    underlined: [OK]
    blockquote: [OK]
    orderedListMixed: [OK]
    orderedListRoman: [OK]
    orderedListSimple: [OK]
    referenceToChapter: [OK]
    referenceToListItem: [OK]
    referenceToText: [OK]
    simpleTable: [OK]
    unicode: [OK]
    unorderedList: [OK]
  Txt2Tags:
    Inlines:
      Plain String: [OK]
      Emphasis: [OK]
      Strong: [OK]
      Strong Emphasis: [OK]
      Strikeout: [OK]
      Verbatim: [OK]
      Symbol: [OK]
      No empty markup: [OK]
      Inline markup is greedy: [OK]
      Markup must be greedy: [OK]
      Inlines must be glued: [OK]
      Macros: Date: [OK]
      Macros: Mod Time: [OK]
      Macros: Infile: [OK]
      Macros: Outfile: [OK]
      Autolink: [OK]
      Image: [OK]
      Link: [OK]
      Image link: [OK]
      Invalid link: No trailing space: [OK]
    Basic Blocks:
      Paragraph, lines grouped together: [OK]
      Paragraph, ignore leading and trailing spaces: [OK]
      Comment line in paragraph: [OK]
      Paragraph: [OK]
      First Level Header: [OK]
      Third Level Header: [OK]
      Header with label: [OK]
      Invalid header, mismatched delimiters: [OK]
      Invalid header, spaces in label: [OK]
      Invalid header, invalid label character: [OK]
      Headers not preceded by a blank line: [OK]
      Paragraph starting with an equals: [OK]
      Paragraph containing asterisk at beginning of line: [OK]
      Horizontal Rule: [OK]
      Comment Block: [OK]
    Lists:
      Simple Bullet Lists: [OK]
      Indented Bullet Lists: [OK]
      Nested Bullet Lists: [OK]
      Simple Ordered List: [OK]
      Indented Ordered List: [OK]
      Nested Ordered Lists: [OK]
      Ordered List in Bullet List: [OK]
      Bullet List in Ordered List: [OK]
      Definition List: [OK]
      Loose bullet list: [OK]
    Tables:
      Single cell table: [OK]
      Multi cell table: [OK]
      Multi line table: [OK]
      Empty table: [OK]
      Glider Table: [OK]
      Table with Header: [OK]
      Table alignment determined by spacing: [OK]
      Pipe within text doesn't start a table: [OK]
      Table with differing row lengths: [OK]
    Blocks and fragments:
      Source block: [OK]
      tagged block: [OK]
      Quote block: [OK]
  EPUB:
    EPUB Mediabag:
      features bag: [OK]

         Properties   Test Cases    Total        
 Passed  10           642           652          
 Failed  0            7             7            
 Total   10           649           659          
Test suite test-pandoc: FAIL
Test suite logged to: dist/test/pandoc-1.17-test-pandoc.log
0 of 1 test suites (0 of 1 test cases) passed.

**Comment by MathieuDuponchelle** [comment]
You did not tell me how to run a specific test by the way :)

**Comment by jgm** [comment]
What does 'locale' say on your build machine?

**Comment by MathieuDuponchelle** [comment]
```
(0.6.6_env)[meh@meh-host pandoc]$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
(0.6.6_env)[meh@meh-host pandoc]$
```

**Comment by jgm** [comment]
This is very strange, I can't imagine what causes these test failures.  It's as if your input files contain `&amp;` where the originals have `&`.  All of the failures are like this.  You can try running

    echo "&ouml;" | pandoc -t native

and see what comes out.  If you get `Str "&ouml;"` then that's the same kind of failure we're seeing above.

**Comment by jgm** [comment]
PS To run specific tests by regex match, you should be able to do

    cabal test --test-options='-t table'

but I just tried it and it raises an error related to this:  http://stackoverflow.com/questions/5047626/matching-specific-unicode-char-in-haskell-regexp
It's a deficiency in the test framework I'm using, it seems.

**Comment by MathieuDuponchelle** [comment]
```
(0.6.6_env)[meh@meh-host pandoc]$ echo "&ouml;" | pandoc -t native
[Para [Str "\246"]]
(0.6.6_env)[meh@meh-host pandoc]$
```

I'll try in a clean repo some other time if I remember :)

regarding tests, yeah, I haven't completely wrapped my head around this test framework, using select-tests on the executable itself should let me specify a full name, with no globbing, but I can't find the correct syntax oO

**Pull request merged**
