### PR TITLE
man: removes double inside

### PR DESCRIPTION
**Pull request by wookietreiber**

### CODE REVIEW

**Comment by mb21** [comment]
Thanks! However, that file is generated. You'd need to change it here instead: https://github.com/jgm/pandoc/blob/master/MANUAL.txt#L3781

**Comment by wookietreiber** [comment]
@mb21 Thanks for the update. When I change it in `MANUAL.txt`, should I run some command to regenerate the man page?

**Comment by wookietreiber** [comment]
I've just figured out how to regenerate the man page. It seems someone else didn't do that as well, so these changes to the man page are in here now, too.

**Comment by jgm** [comment]
As you probably discovered, there's a Makefile target
for that.  Normally we only regenerate it right before
a release, so you don't need to do it now; just fix
the bug in MANUAL.txt.

**Pull request merged**
