### PR TITLE
Add missing copyright notices

### PR DESCRIPTION
**Pull request by tarleb**
This fixes most issues mentioned in #4592.

### CODE REVIEW

**Comment by tarleb** [comment]
Years in test files might be a bit off whenever the file was moved around such that git lost track of its origin (mostly test files).

**Comment by jgm** [comment]
I'm of two minds about this.  I actually don't much like all this boilerplate in the source files, and especially in a trivial little thing like the bash completion script.  It's not strictly necessary, since we have a COPYRIGHT file covering everything, and it's one more thing that can get out of sync and need to be updated.  Maybe someone could comment about why this is important.  I do think it makes sense to consistently put these headers on the source files in src/, since we're generally doing that, but I'm more skeptical about the value of adding them in tests/ etc.

**Comment by tarleb** [comment]
CC @jonassmedegaard

**Comment by tarleb** [comment]
I tend to agree, these headers usually annoy me. Maybe we can just use haddock module headers, they are less verbose and contain all the necessary info. Could automatic generation of copyright statements from these headers serve as a solution?

**Comment by jonassmedegaard** [comment]
I recommend to read the section "Why license notices" at https://www.gnu.org/licenses/gpl-howto.html
- and then have in mind that it is _software_ licenses which means they apply to crative works of sotware (i.e. not README files and likely don't apply to e.g. template files if they contain little if any creative changes).

**Comment by jonassmedegaard** [comment]
My understanding (as a non-lawyer but passionate about semantics of licensing) is that a) copyright statements have no legal value and is added only as a courtesy for downstream users to aid their potential detective work in locating true legal origins of creative works, and that b) listing copyright notices and license statements inline (instead of or in addition to project-wide) is also not legally required.

The whole logic is backwards: Nothing is required - but if the user cannot easily locate a) who owns the rights for the works, and b) how the owner(s) license their rights, then the user is given a hard time in an eventual court case.  So if the reason you license code under copyleft is to help users enjoy the freedoms you grant them, then I strongly recommend that you follow the GNU guidelines as they are intended to limit the risk of giving your users headaches and surprises later on!

**Comment by jgm** [comment]
I think the haddock module headers are sufficient to meet the goal of alerting people who come across the file of the copyright and license. Granted, they don't have the text of the GPL, but that's not hard to find.  Example of haddock module header:
```
{- |
   Module      : Text.Pandoc.Readers.CommonMark
   Copyright   : Copyright (C) 2015-2018 John MacFarlane
   License     : GNU GPL, version 2 or above

   Maintainer  : John MacFarlane <jgm@berkeley.edu>
   Stability   : alpha
   Portability : portable

Conversion of CommonMark-formatted plain text to 'Pandoc' document.

CommonMark is a strongly specified variant of Markdown: http://commonmark.org.
-}
```
Removing the GPL boilerplate that we currently have above these would streamline things a bit, I think.  I really can't see why it's necessary, given the motivations outlined in the GNU document.

**Comment by jonassmedegaard** [comment]
In the end that's your call, John :-)

As I wrote, I believe *nothing* is required, really - and I agree Pandoc has already pleanty of hints of its licensing, even if not in the form preferred by the GNU project.

**Comment by tarleb** [comment]
I've updated the PR to use haddock headers with copyright and licensing information instead of the usual licensing boilerplate header.

**Comment by tarleb** [comment]
I was playing it safe for files under src, and for main programs. I'm interpreting your comment in that you'd prefer to use module headers in these cases as well, which is fine by me. I'll update the PR.

**Comment by jgm** [comment]
Yes, I think it makes sense to get rid of this
boilerplate everywhere, except perhaps when there's
no module header.

**Comment by tarleb** [comment]
Should be good now.

**Comment by jgm** [comment]
Great!

**Pull request merged**
