### PR TITLE
Fixes for multiple docx writer style bugs.

### LINKED ISSUE #1607: Docx writer: common class names don't work in different languages.
"Header1" becomes "Overskrift 1", etc. We can solve this by parsing the styles file and applying styles with the correct "name" tags.

### PR DESCRIPTION
**Pull request by lierdakil**
:construction: :warning: **This  PR is work-in-progress. Not ready to merge** :warning: :construction: 

This is intended to fix #1607, #1933 and #1872 

This PR builds a style name → style id mapping based on styles.xml from reference doc, and changes pStyle and rStyle to accept style name as a parameter instead of styleId. There is a fallback mechanic that removes spaces from style name and returns it as style id, but it likely won't help much if there's no relevant style in styles.xml.

It also changes `styleToOpenXML` to skip generation of styles already present in styles.xml.

Style names are matched lower-case, since headings and `footnote text` have lowercase names, and Word doesn't seem to care.

Comments are welcome.

TODO:
- [x] Skip lookup for custom styles, since those are always well-defined
- [x] More efficient implementation? There is a little too much of IO monad for my taste
- [ ] Test cases (not sure on how to test docx writer, but oh well)
- [x] if --no-highlight is explicitly defined, remove *Tok styles.
- [x] Update reference.docx
- [x] Move StyleMap into separate module in Reader
- [ ] Update Reader to work with StyleMap

### CODE REVIEW

**Comment by nkalvi** [comment]
Hi @lierdakil, just to understand (I don't know Haskell yet) what you're doing, are you 

1. Reading the styles.xml from the reference docx
2. Get the localized names for Pandoc's styles used
3. Use these localized style names in the output doc

#### Example illustrating the issue when using Norwegian Word 2013 

Part of source:
```
% Title
  spanning multiple lines
% Author One
  Author Two; Author Three;
  Author Four
 ```

Partial styles.xml (with *Tittel* vs *Title*):
```
  <w:style w:type="paragraph" w:styleId="Tittel">
    <w:name w:val="Title" />
    <w:basedOn w:val="Normal" />
    <w:next w:val="Normal" />
    <w:qFormat />
    <w:rsid w:val="00DE710F" />
    <w:pPr>
      <w:keepNext />
      <w:keepLines />
      <w:spacing w:before="480" w:after="240" />
      <w:jc w:val="center" />
    </w:pPr>
    <w:rPr>
      <w:rFonts w:asciiTheme="majorHAnsi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" w:cstheme="majorBidi" />
      <w:b />
      <w:bCs />
      <w:color w:val="C0504D" w:themeColor="accent2" />
      <w:sz w:val="36" />
      <w:szCs w:val="36" />
    </w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Undertittel">
    <w:name w:val="Subtitle" />
    <w:basedOn w:val="Tittel" />
    <w:next w:val="Normal" />
    <w:qFormat />
    <w:pPr>
      <w:spacing w:before="240" />
    </w:pPr>
    <w:rPr>
      <w:sz w:val="30" />
      <w:szCs w:val="30" />
    </w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:customStyle="1" w:styleId="Author">
    <w:name w:val="Author" />
    <w:next w:val="Normal" />
    <w:qFormat />
    <w:rsid w:val="00DE710F" />
    <w:pPr>
      <w:keepNext />
      <w:keepLines />
      <w:jc w:val="center" />
    </w:pPr>
    <w:rPr>
      <w:color w:val="548DD4" w:themeColor="text2" w:themeTint="99" />
    </w:rPr>
  </w:style>
```

Portion from the produced docx using the above as reference docx:
```
 <w:body>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Title" />
      </w:pPr>
      <w:r>
        <w:t xml:space="preserve">Title</w:t>
      </w:r>
      <w:r>
        <w:t xml:space="preserve"></w:t>
      </w:r>
      <w:r>
        <w:t xml:space="preserve">spanning</w:t>
      </w:r>
      <w:r>
        <w:t xml:space="preserve"></w:t>
      </w:r>
      <w:r>
        <w:t xml:space="preserve">multiple</w:t>
      </w:r>
      <w:r>
        <w:t xml:space="preserve"></w:t>
      </w:r>
      <w:r>
        <w:t xml:space="preserve">lines</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Author" />
      </w:pPr>
      <w:r>
        <w:t xml:space="preserve">Author</w:t>
      </w:r>
```

**Comment by lierdakil** [comment]
@nkalvi 
Notice how there is child element `w:name` for each style with `w:val` set to english equivalent.
```xml
  <w:style w:type="paragraph" w:styleId="Tittel">
    <w:name w:val="Title" /> <!-- here -->
    ...
  </w:style>
  <w:style w:type="paragraph" w:styleId="Undertittel">
    <w:name w:val="Subtitle" /> <!-- and here -->
    ...
  </w:style>
  <w:style w:type="paragraph" w:customStyle="1" w:styleId="Author">
    <w:name w:val="Author" /> <!-- and even here -->
    ...
  </w:style>
```
This is quite universal. I parse all styles from reference doc's `styles.xml` and build a map from `name.val` to `style.styleId`. For a given example it would look something like this (in sudo js, to spare you haskellisms):
```javascript
styleMap = {
  "title": "Tittel",
  "subtitle": "Undertittel",
  "author": "Author"
}
```
Note that keys are lowercase. This is because Word doesn't care for `name` case, so neither do I.

Now I can reference styles by their english `name`. When creating, e.g. a paragraph with a `Title` style, I do something like this (again, in sudo js):
```javascript
paraNode = new ParaNode({"style": styleMap[lowercase("Title")], ...})
```
This will produce something like
```xml
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Tittel" />
      </w:pPr>
      ...
    </w:p>
```

In practice, there are two style `type`s: paragraph and character. They can be applied to different sets of elements, so I actually create *two* maps (which are stored as `stParaStyles` and `stCharStyles` in writer state). The rest is support code and changes from style ID to style name

Headings are a bit of special case. To make long story short, I construct heading `name` as 
```javascript
"Heading "+level
```
where `level` is integer heading level (`level=1,2,3...`)

That's what I'm doing in a nutshell.

**Comment by nkalvi** [comment]
Thank you very much for kindly explaining this! This solution will be very useful for many international Pandoc users and others (including myself :)

**Comment by lierdakil** [comment]
After some investigation about Word styles, here is what I found. This is a list of all styles, used by docx writer or defined in default reference.docx, except token styles.

| Name                   | Id                   | custom | word | type | alt                              |
|:-----------------------|:---------------------|:------:|:----:|:----:|:---------------------------------|
| Title                  | Title                |        |  +   |  p   |                                  |
| Subtitle               | Subtitle             |        |  +   |  p   |                                  |
| Author                 | Author               |   ?    |      |  p   | ?                                |
| Date                   | Date                 |        |  +   |  p   |                                  |
| Abstract               | Abstract             |   ?    |      |  p   | ?                                |
| Bibliography           | Bibliography         |        |  +   |  p   |                                  |
| Heading 1              | Heading1             |        |  +   |  p   |                                  |
| Heading 2              | Heading2             |        |  +   |  p   |                                  |
| Heading 3              | Heading3             |        |  +   |  p   |                                  |
| Heading 4              | Heading4             |        |  +   |  p   |                                  |
| Heading 5              | Heading5             |        |  +   |  p   |                                  |
| Compact                | Compact              |   ?    |      |  p   | ?                                |
| Image Caption          | ImageCaption         |        |      |  p   | caption                          |
| First Paragraph        | FirstParagraph       |        | ???  |  p   |                                  |
| Body Text              | BodyText             |        |  +   |  p   |                                  |
| Block Quote            | BlockQuote           |        |      |  p   | Intense Quote, Block Text, Quote |
| Source Code            | SourceCode           |   +    |      |  p   |                                  |
| Table Caption          | TableCaption         |        |      |  p   | caption                          |
| Definition Term        | DefinitionTerm       |   ?    |      |  p   | ?                                |
| Definition             | Definition           |   ?    |      |  p   | ?                                |
| Verbatim Char          | VerbatimChar         |   +    |      |  c   |                                  |
| Footnote Ref           | FootnoteRef          |   +    |      |  c   | footnote reference               |
| Footnote Text          | FootnoteText         |        |  +   |  p   |                                  |
| Link                   | Link                 |   +    |      |  c   | Hyperlink                        |
| Normal                 | Normal               |        |  d   |  p   |                                  |
| Default Paragraph Font | DefaultParagraphFont |        |  d   |  c   |                                  |
| Normal Table           | TableNormal          |        |  d   |  t   |                                  |
| Body Text Char         | BodyTextChar         |   +    |      |  c   |                                  |

Custom column is whether style is set as custom in default reference.docx. '?' means it probably should be, but isn't.

Word column is whether Word 'understands' a style. 'd' means it's default style, '???' means I couldn't test.

Type is style type, 'p' is for paragraph, 'c' is for character, 't' is for table.

Alt is Word's built-in styles that serve the same purpose as pandoc-defined ones. Maybe we should switch to those. '?' means that I feel like there probably should be one, but couldn't find it.

As you can see, there are a few ambiguous styles, that are neither defined as custom, nor recognized by Word. We need to decide what to do with those.

There are also 'Link' and 'Footnote Ref' styles that are essentially the same as Word-defined 'Hyperlink' and 'footnote reference', and could be possibly dropped.

Here is a list of styles I'm most concerned about:

| Name            | ambiguous | type | can be replaced by               |
|:----------------|:---------:|:----:|:---------------------------------|
| Author          |    yes    |  p   | ?                                |
| Abstract        |    yes    |  p   | ?                                |
| Compact         |    yes    |  p   | ?                                |
| Image Caption   |    yes    |  p   | caption?                          |
| Block Quote     |    yes    |  p   | Intense Quote, Block Text, Quote |
| Table Caption   |    yes    |  p   | caption?                         |
| Definition Term |    yes    |  p   | ?                                |
| Definition      |    yes    |  p   | ?                                |
| Link            |    no     |  c   | Hyperlink                        |
| Footnote Ref    |    no     |  c   | footnote reference               |

these are either ambiguous (again, meaning that they are neither custom, nor Word defaults), duplicate default Word styles, or both.

So the question is, what should be done with them? I've got the following options:

* Update reference.docx to define ambiguous styles as custom. Do nothing more. This is a quick-and-dirty solution.
* Replace styles in reference with word-recognized ones to the best of our ability. This is a longer path, but leading to hopefully better user experience.
* Do nothing at all, and hope for the best. This will likely lead to 'surprises' in the future, and not the pleasant kind, I fear.

First two options require updates to reference.docx though. @jgm, @jkr, @mpickering, what do you think?

**Comment by nkalvi** [comment]
@lierdakil Good job! :)

Using 'Block Text' for 'Block Quote' may be better since the other styles are not available in Word 2003; that is if the style's name is replaced. 

I feel that taking care of the ones with '+' in the 'word' column would satisfy most users.

**Comment by lierdakil** [comment]
@nkalvi, it will be backwards-compatible if we actually define said styles in reference doc (and if not, it won't work as expected anyway). It just means that word 2003 won't recognize these styles semantically, while later versions would.

I agree that 'Block Text' seems like a good choice though, since it's only one that's left-aligned by default. 'Intense Quote' and 'Quote' are center-aligned.

The question is not really about those styles that Word recognizes. They're pretty much handled fine already. I just feel that if I'm going to do this anyway, I should do it properly this time. Previous attempt addressed only part of the problem, so now I want to make sure I won't have to come back to this.

**Comment by nkalvi** [comment]
@lierdakil @jkr @jgm @mpickering 

This is certainly not efficient and perhaps not as elegant, but I'm wondering about this:

1. Read localized/preferred style names in 'front-matter' either in the document or as an option (f.ex. --stylenames=styles-norsk.yaml). This is regardless of specifying reference.docx. Set a flag if mapping is done. 

		styleName:
			Title: Tittel
			Subtitle: Undertittel

2. If style names are not specified, but a reference.docx is specified, see whether mapping is needed and set a flag.
4. Then in (docx writer's) **renderXML** function, map the names based on the flag.

BTW, my preferred way is to use variables for style/base names and map them from default if needed.
I'll take the feedback as learning experience :)

**Comment by lierdakil** [comment]
@nkalvi I think this actually should be a separate feature, not a substitute for a bugfix. This would allow users to use custom styles in reference docx, which could be nice, but it does not fix issues at hand (although provides a workaround). I could work on it after I'm done with this one. Would you care to create a topic for this proposal in pandoc-discuss?

**Comment by mpickering** [comment]
I've not been following closely but it looks like you are working towards a more robust solution. 

Could you perhaps distil what's in this ticket into a new page on the wiki so that the behaviour is properly documented somewhere?

**Comment by lierdakil** [comment]
@mpickering If you're talking to me, and not @nkalvi, then I'm a little lost as to what should I document. This PR keeps the same workflow, but fixes some issues (referenced in first post in this PR). @nkalvi's proposal, which got mixed in in discussion, is another matter, but I'm not implementing it right now.

And while we're at it, what are your thoughts on updating default reference.docx to correspond with Word more closely? I really can't move this forward until we decide on that...

**Comment by nkalvi** [comment]
@lierdakil @mpickering 
Here's the feature request:
https://groups.google.com/forum/#!topic/pandoc-discuss/oLhedoPmMIs

**Comment by mpickering** [comment]
I replied to both posts on the mailing list. To summarise I think that @lierdakil's solution will work well.

There is already some support for international handling in the docx reader, will this work surpass that?

**Comment by mpickering** [comment]
PS. I think it would be good to move the reading of the `styles.xml` into a separate module. (Probably in the `src/Text/Pandoc/Readers/Docx` folder).

**Comment by jgm** [comment]
@lierdakil - thanks for your detailed analysis. Marking styles as custom is certainly a good idea.  As for the more radical change of switching to standard Word styles, I'm positively inclined, but (as I noted on pandoc-discuss) I did have an earlier difficulty that led me to use "Footnote Ref" and "Link" instead of the Word styles.  I never did really understand what was going on with this, but I wanted to note that the issue had come up.

**Comment by lierdakil** [comment]
@mpickering
As for Reader, kind of. Reader is slightly more complicated, because it needs to get information about base styles as well. I was thinking about merging this codes, but ultimately decided against it, since intent and handling is very different. I will, however, try to implement similar method in reader later.
Moving reading code into separate module is a good idea, but probably not Reader, for reasons explained above. I will think about this idea though, and may come up with a solution. Thank you.

@jgm
I already answered in pandoc-discuss, but for posterity's sake, answering here as well. I'll keep this in mind, and maybe try to fix underlying issues if I stumble upon them. Thank you for bringing this to my attention.

**Comment by lierdakil** [comment]
So I've been thinking hard about tests for docx writer, and here is my best idea so far.

Ideally, docx reader should read writer's output. So, to avoid fumbling around with docx validation, I could utilise existing reader tests to verify that it is indeed the case.

Testing procedure would go something like this:
1. Generate docx from native format
2. Read docx obtained in (1) into native format
3. Compare initial data against one obtained from (2)

This is good in that it could potentially highlight problems in both Reader and Writer. It's bad in that it does not test Writer independently, so "even errors" would fly under the radar, if those are not caught by reader tests.

At the very least, this is better than no tests at all, and alternatives are significantly more involved (basically boiling down to writing custom XML validator)

@jgm, what do you think?

As a side note, I couldn't reproduce issues with `Footnote Reference` and `Hyperlink` styles with current pandoc and Word 2014. I will test with other Word versions when I can get my hands on those (it will require some going around asking for favors, I fear). There is, however, a slight chance that said issues were fixed by something already.

**Comment by jgm** [comment]
+++ Nikolay Yakimov [Mar 01 15 12:24 ]:
>So I've been thinking hard about tests for docx writer, and here is my best idea so far.
>
>Ideally, docx reader should read writer's output. So, to avoid fumbling around with docx validation, I could utilise existing reader tests to verify that it is indeed the case.
>
>Testing procedure would go something like this:
>1. Generate docx from native format
>2. Read docx obtained in (1) into native format
>3. Compare initial data against one obtained from (2)
>
>This is good in that it could potentially highlight problems in both Reader and Writer. It's bad in that it does not test Writer independently, so "even errors" would fly under the radar, if those are not caught by reader tests.
>
>At the very least, this is better than no tests at all, and alternatives are significantly more involved (basically boiling down to writing custom XML validator)
>
>@jgm, what do you think?

Tests that don't separate reader and writer bugs are certainly better than no tests at all!

Note that, in general, pandoc readers and writers don't successfully round-trip, for a variety of reasons.  So you'd have to look into whether the kind of round-trip tests you have in mind do work for docx.

**Comment by lierdakil** [comment]
I added some rudimentary tests. @jgm was right, not everything survives writer-reader roundtrips, and although I'd prefer it would, I worked around those mostly.

Please note that build fail has nothing to do with tests failing or anything, but with some problem on Travis CI side, namely
```
WARNING: The following packages cannot be authenticated!
  cabal-install-1.18 ghc-7.8.4
E: There are problems and -y was used without --force-yes
The command "sudo apt-get install cabal-install-1.18 ghc-7.8.4" failed.
```
see https://travis-ci.org/jgm/pandoc/jobs/53507864

I will need to add tests for mangled reference.docx and update reader code a bit, but for the most part I think it's done, although test coverage could probably be better.

Requesting comments on code style etc.

**Comment by jgm** [comment]
Great, I'm going to go ahead and merge this, before it gets stale.  Thanks!

**Comment by lierdakil** [comment]
Okay, I'll create a new PR for reader changes and test updates then, when I find some time for it. Sorry I didn't complete this earlier, but I suddenly became insanely busy at work.

**Pull request merged**
