### PR TITLE
Make #+pandoc-emphasis-pre work as expected (#8059)

### LINKED ISSUE #8059: Org-mode reader: `#+pandoc-emphasis-pre` doesn't work as expected
**Explain the problem.**
Adding characters to `#+pandoc-emphasis-pre` as [described in the manual](https://pandoc.org/org.html#emphasis-rules) doesn't work as expected. Interestingly, adding to `#+pandoc-emphasis-post` does.

Minimal working example `test.org`:
```
#+pandoc-emphasis-pre: "-\t ('\"{T"
#+pandoc-emphasis-post: "-\t\n .,:!?;'\")}[t"

1. T/est/ with T allowed as pre
2. /Tes/t with t allowed as post
3. Normal /emphasis/, and in {/brackets/}
```

Command: `pandoc -o test.md test.org`

Expected `test.md` result:
```markdown
1.  T*est* with T allowed as pre
2.  *Tes*t with t allowed as post
3.  Normal *emphasis*, and in {*brackets*}
```

Actual result:
```markdown
1.  T/est/ with T allowed as pre
2.  *Tes*t with t allowed as post
3.  Normal *emphasis*, and in {*brackets*}
```

Exporting to Pandoc AST confirms that the problem is with the reader.

Also completely replacing the strings with `"T"` and `"t"` respectively achieves the same result.

**Pandoc version?**
Pandoc 2.18 on Manjaro Linux (`pandoc-2.18-linux-amd64.tar.gz` from the [release page](https://github.com/jgm/pandoc/releases/tag/2.18)). Also happens on https://pandoc.org/try

### PR DESCRIPTION
**Pull request by adql**
The main issue with the original implementation is that it kept the assumption that no emphasis markers may occur directly after most non-whitespace chars, e.g. in the middle of the word (in Pandoc terms: following native `Str`). But with the possibility to modify which chars are allowed around emphasized text, Pandoc should remain indifferent in that respect.

These commits allow it and modify some tests accordingly. This is both:

1. in accordance with Org-mode's behavior when customizing `org-emphasis-regexp-components`.
2. reasonable in many languages[^1] (but rare in English).

Resolves #8059.

[^1]: which is the case in Hebrew and German, both of which I speak.

### CODE REVIEW

**Comment by adql** [comment]
By the way, I originally used `*>` in `updatePositions'`, but `hlint` suggested to replace it with `$>`. This is very strange because it's wrong. Replacing with `>>` eliminated the suggestion. Any explanation to that?

**Comment by tarleb** [comment]
Thank you, this is excellent. `hlint` sometimes suggests functions that'd need a separate import; this would work though: `updatePositions str' = str' <$ update...`.

The function `T.last` is partial and throws an error when passed `""`. While we know that this can never happen, but we have the general policy of avoiding partial functions if possible: could you change the code to use `T.unsnoc` to replace `T.last`?

**Comment by adql** [comment]
> this would work though: `updatePositions str' = str' <$ update...`.

Yes, I see how this expression is useful. Makes it clear that we're here for the side effect.

**Comment by tarleb** [comment]
Thank you!

**Comment by adql** [comment]
My pleasure :)

**Pull request merged**
