### PR TITLE
LaTeX Reader: check for block-level newcommand aliases in blockCommand

### PR DESCRIPTION
**Pull request by lierdakil**
This came to be in response to #1866. I'm creating a pull request to facilitate the process somewhat.

Comments are welcome.

### CODE REVIEW

**Comment by jgm** [comment]
Question:  what happens if a paragraph begins with a macro that is meant to be inline-level? For example,
```
\newcommand{\wbal}{The Wikibook about \LaTeX}

\wbal is a good resource for learning \LaTeX.
```
Running your code in my head (which is not very reliable!), I worried that your code might parse this as a Plain or Para with "The Wikibook about LaTeX" followed by another Para with "is a good resource for learning LaTeX", rather than as a single paragraph.  What does it do with this input?  (Cf. @mpickering's suggestion in #1866 to treat a macro as block only if it doesn't parse as inlines.)

**Comment by lierdakil** [comment]
That is a good point, thanks.

It is relatively simple to guard against (by following @mpickering's suggestion more closely), although it does introduce more backtracking. I'll push relevant changes shortly.

**Comment by lierdakil** [comment]
A small style change. I believe it's easier to grasp what's going on this way.

As a side note, code style in LaTeX reader seems quite inconsistent, and could use some cleanup maybe.

**Comment by jgm** [comment]
@lierdakil, code cleanup is always welcome!  (I note that some parts of the pandoc code date from when I was first learning Haskell. Gradually it improves, but it's a big code base.)

**Pull request merged**
